### PR TITLE
Closes #3307: Add reset order button to draggable views.

### LINKED ISSUE #3307: Add alphabetical reset to AZ Person reorder view
## Motivation
I reordered the person view once, now I have a lot of people and want to order them alphabetically.

### Is your feature request related to a problem? Please describe.
A client reordered once, added a bunch more people, and can't get them to an alphabetical order easily now.

### Describe the solution you'd like
I want an option to reset my manual person order.

### Describe alternatives you've considered
Could a reset button reset the order to `0` or an order that coincides with the alphabetical

## Additional context
Clear documentation will be needed. Ie. If this button is pushed, _all_ reordering will be reset to an alphabetical listing.

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
Adds reset button to draggable reorder view via patch.
Adds button definitions to footer of view.

## Related issues
Closes #3307 

## How to test
1. Add person content
2. Reorder view display of people on `/admin/az-person/reorder-people`
3. Observe save/reorder button help text
4. Ensure order is reflected on front end
5. Click the reset button
6. Ensure order is reset to alphabetical on the front end

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [x] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [x] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sanjanans — APPROVED** [review]
Works perfectly. Thank you Dana!

**Comment by joeparsons** [comment]
Confirmed that this adds a reset button to all draggable views (which I think is good).  Are we sure the footer help text on the person view is needed?  If so, do we need to add something similar to the other reorder views (e.g. carousel)?

**Comment by danahertzberg** [comment]
> Confirmed that this adds a reset button to all draggable views (which I think is good). Are we sure the footer help text on the person view is needed? If so, do we need to add something similar to the other reorder views (e.g. carousel)?

I do think the footer help text is needed on person reordering. I am impartial to the necessity of the footer help text on the carousel reorder view `/admin/az-carousel/reorder-carousel-items`

**Review by trackleft — APPROVED** [review]

**Comment by danahertzberg** [comment]
Attempted to add help text here, but apparently it's not a view? I'm not sure how to edit.
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3363.probo.build/admin/az-carousel/reorder-carousel-items

**Review by joeparsons — APPROVED** [review]

**Review by sanjanans — APPROVED** [review]

**Comment by tadean** [comment]
My testing found no regressions in the functionality for `az_curated_views`.

**Review by tadean — APPROVED** [review]

**Pull request merged**
