### PR TITLE
Fixes #407: AZ Person view contextual filter updates

### LINKED ISSUE #407: Add in contextual filter for term category on AZ_Person
## Motivation
We need to be able to filter People by Taxonomy term for use on Taxonomy pages or when using Arguments on the Persons Views. 

### Describe the solution you'd like
There should be a contextual filter added that will allow for filtering by either of the Taxonomy Terms.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
  - Should be able to assign taxonomy terms to people
  - Should be able to add those taxonomy terms as arguments to the Person views to filter the view.
- Content administrator
- Administrator

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
This a re-evaluation of how we handle contextual filters on the AZ Person views.

**New goal:** Make person views more user friendly to how people are already using views by providing expected outcomes when adding the view paragraph type.
- Expected outcome without any filters is to display all people in alphabetical order
- Expected outcome with a filter is to display only people associated with that filter
- Current experience without filters is display all people by category
- Current experience with filters requires second contextual filter to show only that filter
- If someone wants one page with people in category order, they can add multiple views
- Implementing second filter on D9 cannot be done in the same way as D7 because relationships are not available for selection by the `Content: Has taxonomy term ID` filter

#### AZ Person view
1. Removed `Content: Has taxonomy term ID (with depth)` filter
2. Removed grouping by category
3. Removed force using fields
4. Removed category sort criteria
5. Added `Content: Has taxonomy term ID` filter

#### Views reference paragraph type
1. Added custom `Title` field (H2)
2. Enabled `Display view title` checkbox

## Related Issue
Closes https://github.com/az-digital/az_quickstart/issues/407 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Getting this PHPUnit test error, but not sure how to fix.

> EEEEEEEE 8 / 8 (100%)PHP Warning:  file_put_contents(/src/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/.phpunit.result.cache): failed to open stream: Permission denied in /src/az-quickstart-scaffolding/vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 108

**Comment by trackleft** [comment]
> Getting this PHPUnit test error, but not sure how to fix.
> 
> > EEEEEEEE 8 / 8 (100%)PHP Warning:  file_put_contents(/src/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/.phpunit.result.cache): failed to open stream: Permission denied in /src/az-quickstart-scaffolding/vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 108

Looks like a dependency is missing for `field.field.paragraph.az_view_reference.field_az_title`
 https://github.com/az-digital/az_quickstart/pull/623/files#diff-ce2f656936154cc5cd16500b6fcbf0a6fffc76940efcf1ac7b41fcb07ce3030aR5

**Comment by trackleft** [comment]
@danahertzberg if you add az_paragraphs as a dependency it will be resolved, but I'm not sure that is what you want?

**Comment by danahertzberg** [comment]
Looks like it already is a dependency..
https://github.com/az-digital/az_quickstart/blob/issue/407/modules/custom/az_paragraphs/az_paragraphs_view/az_paragraphs_view.info.yml

**Comment by trackleft** [comment]
Looks like you have sorted it out.

**Comment by danahertzberg** [comment]
Test page: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-623.probo.build/views-test

**Review by smayden — APPROVED** [review]
great improvements to be clearer and more useful for content editors

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Pull request merged**
