### PR TITLE
Closes #1566: Prepare Quickstart for Drupal 9.4.x.

### LINKED ISSUE #1566: Prepare Quickstart for Drupal 9.4.x
## Motivation

Drupal 9.4.0 is scheduled to be released in June 2022.  We should plan to upgrade Quickstart to 9.4.x ASAP.

9.4.0-alpha1 was released earlier this month and its release notes page contains a good overview of what has changed:
https://www.drupal.org/project/drupal/releases/9.4.0-alpha1

## Proposed Resolution
- Make any changes necessary for 9.4.x compatibiliy
- Upgrade Quickstart to Drupal 9.4.x ASAP

### PR DESCRIPTION
**Pull request by joeparsons**
## Description

- Updates Drupal core to ~9.4.0~ 9.4.1
- Changes minimum PHP version constraint in composer.json from 7.3 to 7.4 (consistent with Drupal 9.4.0)
- Updates PHP version used in various CI configs to 8.1
- Applies various changes to comply with Drupal 9.3.x/9.4.x updated coding standards (most notably [this change](https://www.drupal.org/node/3249380))
- Removes core patches that are no longer needed
- Updates core patches for 9.4.x compatibility

## Related issues
Closes #1566

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [x] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [x] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
```
74Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/Entity/Query/Condition.php on line 39
75
76Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/Entity/Query/Condition.php on line 39
77
78Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/Entity/Query/Condition.php on line 39
79
80Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/Entity/Query/Condition.php on line 39
81
82Deprecated: Return type of Drupal\xmlsitemap\XmlSitemapWriter::openUri($uri) should either be compatible with XMLWriter::openUri(string $uri): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/web/modules/contrib/xmlsitemap/src/XmlSitemapWriter.php on line 85
83
84Deprecated: Return type of Drupal\xmlsitemap\XmlSitemapWriter::startElement($name, $root = false) should either be compatible with XMLWriter::startElement(string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/web/modules/contrib/xmlsitemap/src/XmlSitemapWriter.php on line 176
85
86Deprecated: Return type of Drupal\xmlsitemap\XmlSitemapWriter::writeElement($name, $content = null) should either be compatible with XMLWriter::writeElement(string $name, ?string $content = null): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/web/modules/contrib/xmlsitemap/src/XmlSitemapWriter.php on line 209
87
88Deprecated: Return type of Drupal\xmlsitemap\XmlSitemapWriter::startDocument($version = '1.0', $encoding = 'UTF-8', $standalone = null) should either be compatible with XMLWriter::startDocument(?string $version = "1.0", ?string $encoding = null, ?string $standalone = null): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/web/modules/contrib/xmlsitemap/src/XmlSitemapWriter.php on line 109
89
90Deprecated: Return type of Drupal\xmlsitemap\XmlSitemapWriter::endDocument() should either be compatible with XMLWriter::endDocument(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/web/modules/contrib/xmlsitemap/src/XmlSitemapWriter.php on line 256
91
92Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 220
93
94Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /src/az-quickstart-scaffolding/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 225
```

**Comment by joeparsons** [comment]
9.4.0 was released today.  This should be ready for serious review / testing and hopefully merging.

**Comment by joeparsons** [comment]
Final 9.4.0 release notes:
https://www.drupal.org/project/drupal/releases/9.4.0

**Comment by joeparsons** [comment]
https://www.drupal.org/project/drupal/releases/9.4.1

**Review by tadean — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
