### PR TITLE
Closes #746: Adds bottom margin to Person, News, Events

### LINKED ISSUE #746: Content butts up against footer
## Problem/Motivation
For our news, events, and person content types (and possibly some paragraphs on page) the content area butts up agains the footer with no padding.

##  Screenshots
image

### PR DESCRIPTION
**Pull request by cpoff**
Person, News, Events need some bottom margin on the body so they don't stack directly on top of the footer. 

## Description
I added mb-5 to the row or container/wrapper on each display type or twig.

## Related issues
#1648 directly references this issue, as I spent a little time trying to dig up how to complete Person (it sits in a twig)

## How to test
-Add content to Person, News, and Event. 
-Scroll down to the footer and see if there's adequate spacing between the body content and the footer.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Wish we had this https://www.drupal.org/project/entity_type_behaviors

**Comment by joshuasosa** [comment]
Available to try at: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1656.probo.build/user

**Review by bberndt-uaz — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Comment by cpoff** [comment]
Changed single group wrapper name. Ready for approvals and merge.

**Comment by cpoff** [comment]
Security dependency error involves guzzlehttp/guzzle (6.5.6).

**Review by trackleft — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Pull request merged**
