### PR TITLE
#133 Event Content Type

### PR DESCRIPTION
**Pull request by tadean**
This PR adds an event content type. `smart_date` is used as the contrib module for handling recurring dates.

## Description

- [x] Selection of range-recurrence date module, (eg `smart_date`, `date_recur`, etc)
- [x] Compatibility of Date AP Style with selected range-recurrence module
- [x] Row display mode
- [x] User permissions for events
- [x] Additional themeing
- [x] Event image styles
- [x] Basic event view

## Related Issue
#133 
#351 
#303 
#302 

## How Has This Been Tested?

- Create event
- Upload media for event and create a Large crop to test cropping
- Verify full content is rendered appropriately
- Verify that `/calendar` view contains the content

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
Issue discussing the current status of token replacements in the link URL field located [here (drupal.org)](https://www.drupal.org/project/drupal/issues/2903336).

**Comment by tadean** [comment]
- Added user permissions
- Added "Month" and "Day" Pseudo fields that render the current month or day of the contained date
- Themed default display
- Themed row display
- Added basic view with contextual filter
- Added Date AP Style settings
- Added Smart Dates for recurrence rules
- Added Date AP style compatibility patch

image

image

**Followup work needed:**
**Node tokens:**
`[node:title]` and `[node:url]` tokens do not seem to work in many fields; these are needed for QS1 parity.

**View needs additional work to split the recur instances into separate view results to avoid the following:**
image

**Comment by tadean** [comment]
- [ ] Solve node context `[node:title]` and `[node:url]` tokens for fields
- [ ] Split recurring events into multiple results in views (with only the delta-specific date)
- [ ] Refactor some storage from `az_news` etc to shared storage to remove unnecessary cross dependencies

**Comment by tadean** [comment]
Sort from Today - ascending based

**Comment by trackleft** [comment]
QS1 reference for limiting the number of dates shown using the content view plugin for views https://bitbucket.org/ua_drupal/ua_quickstart/src/1376b32b48164de0f9f9039de36fe8334e35f83e/modules/custom/uaqs_event/uaqs_event.module#lines-47:76

**Comment by trackleft** [comment]
Apparently that hook was deprecated in favor of https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Entity!entity.api.php/function/hook_entity_display_build_alter/8.3.x

**Comment by tadean** [comment]
- Added Event view description (`Use this view to manage Event content`)
- Added Event view no results behavior (`There are no upcoming events listed.`)
- Changed view to `>= now` filtering
- Changed view to ascending sorting on date

**Comment by tadean** [comment]
> Apparently that hook was removed in favor of https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Entity!entity.api.php/function/hook_entity_display_build_alter/8.3.x

Thanks @trackleft !

**Review by camikazegreen — DISMISSED** [review]

**Comment by danahertzberg** [comment]
Can we make the `Short title` and `Event description` fields optional instead of required?

**Comment by smayden** [comment]
Agree with Dana that Short title should not be required. Should we do the same as we did on News and not use short title in the view mode until the token issue is fixed? On News we put the title there.

Other suggestions/questions:
- Make default URL for event nodes events/title
- Is there a way to enter a location without specifying a URL? I couldn't seem to do so (and don't think it is in QS1
- I know we moved contacts out of scope for news work into a separate ticket. We'll need to prioritize for events at some point (maybe soon?) to meet accessibility needs

**Comment by danahertzberg** [comment]
> Agree with Dana that Short title should not be required. Should we do the same as we did on News and not use short title in the view mode until the token issue is fixed? On News we put the title there.
> 
> Other suggestions/questions:
> 
> * Make default URL for event nodes events/title
> * Is there a way to enter a location without specifying a URL? I couldn't seem to do so (and don't think it is in QS1
> * I know we moved contacts out of scope for news work into a separate ticket. We'll need to prioritize for events at some point (maybe soon?) to meet accessibility needs

@smayden This PR already doesn't use the short title field. So just making it optional I think solves those issues.

I agree with making the URL for location optional.

The build was reaped again!! I didn't check for the URL updates.

**Comment by smayden** [comment]
> @smayden This PR already doesn't use the short title field. So just making it optional I think solves those issues.

@dana I wish I took a screen shot, but the text I entered in for Short Title did appear on the /calendar view/page. So if it isn't required I'm unclear what will show there?

**Comment by danahertzberg** [comment]
> > @smayden This PR already doesn't use the short title field. So just making it optional I think solves those issues.
> 
> @dana I wish I took a screen shot, but the text I entered in for Short Title did appear on the /calendar view/page. So if it isn't required I'm unclear what will show there?

Ah, I see. The title display not the destination. Yes, I agree it _should_ be the node title once the short title is not required/used.

**Comment by tadean** [comment]
- Added url alias pattern
- Removed short title
- Made the description field not required

**Comment by tadean** [comment]
> * Is there a way to enter a location without specifying a URL? I couldn't seem to do so (and don't think it is in QS1

We probably will need to identify a general contrib module that allows some kind of `no link` route for this - it probably has other uses than just this pull request also.

**Review by smayden — APPROVED** [review]
This is working well and looking good! 

I think the location URL issue can be addressed in another ticket. For future work, we may want to consider not making end date/time required as content editors often only know the start time.

**Comment by smayden** [comment]
Also, successfully able to pull events by tag into a page using the view paragraph type and an argument matching the tag! For future, we may want to consider the name of the page on the view to be recognizable for content editors.

image

**Review by camikazegreen — APPROVED** [review]

**Pull request merged**
