### PR TITLE
Close #3861 Change scope of spaceless filter from all elements to AZ Person headings

### LINKED ISSUE #3861: Create New Templates for Heading Elements in field_group
## Problem/Motivation

Some content editors have been relying on a bug in `field-group-html-element.html.twig` to add space between elements. Currently, blocks embedded in content are output using the `field-group-html-element.html.twig`, which applies the spaceless filter to all rendered HTML. 

The spaceless filter was applied in this commit: https://github.com/az-digital/az_quickstart/commit/a119b5cd314a38992e7f24589fe86134860a0fdd#diff-85998c378764d17df837312a6a3594e772f590e5ef1f3311eaf4252c886ff3f7

### Describe the bug
The spaceless filter is too aggressive in the `field-group-html-element.html.twig` template, resulting in unintended removal of spaces that content editors may rely on for layout purposes. 

## Proposed resolution
I propose creating new templates specifically for heading elements that do not utilize the spaceless filter. This will allow content editors to maintain the necessary spacing for headings while still benefiting from the existing functionality for other elements.

Proposed files:
`field-group-html-element.h1.twig`
`field-group-html-element.h2.twig`
`field-group-html-element.h3.twig`
`field-group-html-element.h4.twig`

##  Screenshots
image

## Additional context
This issue is most prevalent with inline buttons within embedded content blocks.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Instead of forcing the spaceless filter on all elements we can target specific elements.
This PR add 4 new templates to apply the spaceless filter to specific heading elements `h1 h2 h3 h4`

**Update Nov 8, 2024:** This PR now applies the spaceless filter only to heading elements `h1 h2 h3` on AZ Person nodes. For the 'h4' element or for AZ News heading elements, the filter does not appear to be needed or it wouldn't have any effect, but further discussion and investigation would be helpful.

#### Questions:

1. Is there a use case for which the spaceless filter needs to be applied to AZ News headings?
2. No content type displays of AZ Person use an h4 element (only the `h4` class is used). Is it correct that we don't need to apply the spaceless filter to h4 elements on AZ Person nodes?

## Related issues
 - #3861

## How to test
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3867.probo.build

These templates are used in entity view modes that utilize the field_group module to build displays.
Specifically, any html element field group that sets the element to any of h1 h2 h3 h4

Examples are the az person default display Name/Title output, or az news headline in default display.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by bberndt-uaz** [comment]
Per AZ Digital discussion, let's try to target AZ Person specifically. We can use the template suggestion for the field group name if possible.

**Comment by bberndt-uaz** [comment]
@tadean I have moved the templates to the az_person module and I added a theme hook to ensure that they are used correctly. I believe the h4 heading is not used by AZ Person.

I tried to use a theme suggestions hook as shown below, but it didn't seem to work without the theme hook I added. Since the theme hook on its own results in the correct template file being used, I removed the theme suggestions hook. The issue may have something to do with the template files being in the module folder instead of the AZ Barrio theme folder.

```
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function az_person_theme_suggestions_field_group_html_element_alter(&$suggestions, $variables) {
  if (isset($variables['element']['#bundle']) && $variables['element']['#bundle'] === 'az_person'
    && isset($variables['element']['#wrapper_element']) && in_array($variables['element']['#wrapper_element'], ['h1','h2','h3'])) {
    $suggestions[] = 'field_group_html_element__' . $variables['element']['#entity_type'] . '__az_person__' . $variables['element']['#wrapper_element'];
  }
}
```

I'd appreciate any feedback! If the current approach looks OK generally, I'll update the title and description for this PR.

**Comment by tadean** [comment]
This approach seems sensible to me, thanks @bberndt-uaz ! In regards to the template suggestion question, I think that templates within a module are not used unless the module does something to alter the theme registry (or implements `hook_theme`).

**Review by danahertzberg — APPROVED** [review]

**Comment by danahertzberg** [comment]
Needs discussion about the spaceless filter for AZ News necessity

**Pull request merged**
