### PR TITLE
#348: Update to Drupal 9.1.0.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
- Updated Drupal core to ~9.1.0-rc3~ 9.1.0
- Removed @akslay's core patch that already exists in 9.1.x (from https://www.drupal.org/i/3153394)
- Replaced patch for https://www.drupal.org/i/784672 with Drupal 9.1.x compatible version
- Replaced Claro tabledrag patch from https://www.drupal.org/i/3092181 with one from https://www.drupal.org/i/3083051
- Fixed various coding standards issues identified by newer PHPCS version used by 9.1.x
- Fixed various new deprecation warnings identified by phpstan
- Removes phpstan-contrib (deprecation checks) from ProboCI build steps

## Related Issue
#348 

## How Has This Been Tested?
Locally with Lando

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
Depends on corresponding scaffolding repo PR: az-digital/az-quickstart-scaffolding#35

**Comment by joeparsons** [comment]
Most of the contrib PHPstan failures are due to these recent test method deprecations:

https://www.drupal.org/node/3129738
https://www.drupal.org/node/3168858

**Comment by joeparsons** [comment]
Updated Drupal core to 9.1.0.

Worth noting that I noticed one of the issues in the list of changes since 9.1.0-rc3 (that has not yet been included in a 9.0.x release) "in action" while reviewing Chris' Bootstrap update PR (in the fieldsets on the AZ Barrio theme settings form):
[#3183425 Google Chrome 87 renders fieldset with grey artefacts](https://www.drupal.org/project/drupal/issues/3183425)

Screen Shot 2020-12-03 at 4 53 44 PM

**Review by mmunro-ltrr — DISMISSED** [review]
No immediately obvious problems (on a local build), though I've not looked at the Claro tabledrag issue.

**Review by jwmoore1 — DISMISSED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by jwmoore1 — APPROVED** [review]

**Pull request merged**
