### PR TITLE
Closes #2549 remove horizontal scroll in mobile browsers when off canvas nav buttons appear on the page.

### LINKED ISSUE #2549: Page renders larger than view port in safari mobile. (A horizontal scroll appears in mobile browsers on pages with off canvas nav buttons.)
In Safari mobile, I can scroll side to side on pages where I should not be able to.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Added css  to address #2549 

Buttons for offcanvas nav that appear in the red bar at the top of the page were causing this issue.

image

## Related issues
Closes #2549 

## How to test
Test on an actual phone using a mobile browser.

[Visit the Probo Site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2673.probo.build/)

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by akslay — DISMISSED** [review]

**Review by joeparsons — DISMISSED** [review]
Tested with iPhone 11 Pro Max on Safari.

- Confirmed issue on https://demo.quickstart.arizona.edu
- Confirmed fix on [Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2673.probo.build/) for this PR

**Review by bberndt-uaz — APPROVED** [review]
Tested in Chrome on a Samsung Galaxy Android phone. Confirmed the issue on https://demo.quickstart.arizona.edu and confirmed the fix on the [Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2673.probo.build/) for this PR.

**Comment by joshuasosa** [comment]
I think this change is more of a band-aid than a fix for the underlying issue. It does work, but I wonder if this other issue I see come up sometimes is related.

Sometimes on mobile, the menu button goes to a second line. When it does so, it stops doing the slight horizontal scroll. This is using Edge on Samsung. I can get it to recur just by refreshing on Edge, but can't get it to happen on Chrome or Firefox. Edge might be rendering slightly differently, but it might just be displaying that underlying issue with those buttons in a different way.

Current live after loading then refreshing https://demo.quickstart.arizona.edu/
SmartSelect_20230822-095850_Edge

This PR after loading then refreshing https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2673.probo.build/
SmartSelect_20230822-095948_Edge

**Comment by trackleft** [comment]
Thanks @joshuasosa, I was thinking that overflow hidden was a band-aid as well.  I'll try to determine the exact cause of this.

Possibly the container is a fixed width and the buttons overflow the container?

**Comment by joshuasosa** [comment]
@trackleft It looks like either margin option would work to remove the horizontal scroll from my testing.

But on mobile Edge, the buttons continue to weirdly stack regardless of how I changed the buttons. I fixed it by adding `d-flex` to the div that has `redbar-buttons d-lg-none` in [page.html.twig](https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/layout/page.html.twig#L103). With that change, the buttons continue to look as expected on Chrome and Firefox in my Samsung testing.

**Comment by trackleft** [comment]
@joshuasosa I'll try that, thanks!

**Review by ejsamboy — APPROVED** [review]
Tested this PR on an actual phone (iPhone: Chrome and Safari). The horizontal scroll is gone.

https://github.com/az-digital/az_quickstart/assets/92047381/2e918299-01f3-4e72-bead-27bd0d609f63

**Review by joeparsons — APPROVED** [review]

**Comment by trackleft** [comment]
Test here: https://41ccdf29-406c-4d0d-a9b9-9f59d3d7ebc7.probo.build/
Before https://demo.quickstart.arizona.edu

**Review by joshuasosa — APPROVED** [review]
Looks good on mobile Edge, thanks!

**Pull request merged**
