### PR TITLE
Closes #1481: Increase soft limit widths to 1920px for az_full_width_bg_large image style.

### LINKED ISSUE #1481: image quality 1920
## Problem/Motivation
We need a patch fix for this issue to gain better quality of images in text on media pargraphs.

### Describe the bug
soft limit width is set to 1190 which is less than the standard 1080p monitor (1920px)

## Proposed resolution
Change soft limit width to 1920

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Changing soft limit width(s) for az_full_width_bg_large image style / crop type.

## Related issues
Closes #1481

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Need to add Lighthouse performance comparison (Pantheon to Pantheon)

**Comment by smayden** [comment]
Interestingly... My initial lighthouse test of Probo vs Probo the one with this PR applied had better performance.

Before:
image


After:
image

**Review by smayden — APPROVED** [review]

**Comment by smayden** [comment]
Also only seeing a slight dip in performance on pages with multiple text on media elements, but definite visual improvements.

This PR: https://f18fe7da-1f44-4292-b54d-a3742e13dc80.probo.build/pages/text-media
Lighthouse performance: 86

Other Probo: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1478.probo.build/pages/text-media
Lighthouse performance: 88

**Review by danahertzberg — APPROVED** [review]

**Comment by bberndt-uaz** [comment]
> Also only seeing a slight dip in performance on pages with multiple text on media elements, but definite visual improvements.
> 
> This PR: https://f18fe7da-1f44-4292-b54d-a3742e13dc80.probo.build/pages/text-media Lighthouse performance: 86
> 
> Other Probo: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1478.probo.build/pages/text-media Lighthouse performance: 88

@smayden It looks like this PR's Probo is the one that starts with 7b5?

I also did some Lighthouse tests using the home page of the two Probo sites above.

[7b5 home page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1482.probo.build/) (this PR):
Desktop: 91, 92, 92
Mobile: 65, 64, 65

[f18 home page](https://f18fe7da-1f44-4292-b54d-a3742e13dc80.probo.build/) (a different PR):
Desktop: 88, 84, 88
Mobile: 61, 60, 60

I'll attach a PDF for one of the 7b5 mobile reports:
[7b5 Mobile Lighthouse report.pdf](https://github.com/az-digital/az_quickstart/files/8498215/7b5.Mobile.Lighthouse.report.pdf)

**Comment by smayden** [comment]
Yes. I think I mixed up the Probo URLs in my last comment, but not the performance numbers. So interesting that this PR seems to improve performance slightly.

Double win?!?

**Comment by smayden** [comment]
This screenshot shows the image improvement for a hero image used on the Arizona.edu homepage recently.

image

Left side - This PR, Right side - the image how it displayed on Arizona.edu

**Review by jwmoore1 — APPROVED** [review]

**Comment by joeparsons** [comment]
Question from @akslay: Does this break the edit-ability of content containing images with <1920px widths?

**Comment by bberndt-uaz** [comment]
> Yes. I think I mixed up the Probo URLs in my last comment, but not the performance numbers. So interesting that this PR seems to improve performance slightly.
> 
> Double win?!?

It looks like there are multiple Probo builds that start with 7b5... that you can get to from the "View Site" button, so actually your URLs were correct! Sorry about that! I didn't realize each Probo build has a "permalink" and another link for the latest version.

**Comment by joeparsons** [comment]
> Question from @akslay: Does this break the edit-ability of content containing images with <1920px widths?

@danahertzberg Confirmed that smaller images can still be used (doesn't prevent content from being saved).

**Review by bberndt-uaz — APPROVED** [review]

**Pull request merged**
