### PR TITLE
Closes: #1005 Refactoring captions on news to use image caption

### PR DESCRIPTION
**Pull request by smayden**
## Description
Based on our earlier discussion about what to do with the caption field on news, this PR refactors the news content type to use the caption field from the image instead.

- Removes the the caption from the news default entity view display
- Keeps the caption from the media entity view display in place (note any styling is controlled via figcaption in boostrap)
- Updates the demo content by removing az_caption data for news and adding image 

Still to do (depending on further discussion)

- remove az_caption from the news form display
- remove az_caption from the fields on news content type
- update starter content
- update migrations
- database update (maybe?)

## Related Issue
#1005 

## How Has This Been Tested?
Locally and in Probo

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by smayden** [comment]
I've deleted the captions field from the news content type and associated entity forms.

I think this is ready for the database update @joeparsons  and migration piece @trackleft

**Comment by joeparsons** [comment]
@smayden #1116 Should be ready to merge into this PR's branch with the DB update(s).

**Comment by joeparsons** [comment]
Question:  Do we also want to remove the `field_az_caption` node field storage config?  I'm thinking probably not because doing so would definitely be riskier than just deleting the field config from `az_news` as its possible that custom content types might be using the `field_az_caption` storage config.  That being said, `az_news` was the only Quickstart content type using this field (I believe) and we could have the database update only delete the field storage config if no other content types are using it.

**Comment by trackleft** [comment]
> Question: Do we also want to remove the `field_az_caption` node field storage config? I'm thinking probably not because doing so would definitely be riskier than just deleting the field config from `az_news` as its possible that custom content types might be using the `field_az_caption` storage config. That being said, `az_news` was the only Quickstart content type using this field (I believe) and we could have the database update only delete the field storage config if no other content types are using it.

Actually I think you are right, since media will have its own storage config

**Comment by joeparsons** [comment]
> Actually I think you are right, since media will have its own storage config

If we do want to remove it, we'll need to update the DB update(s) PR as well.

**Comment by trackleft** [comment]
Let's remove it. I wish the update descriptions could be longer, probably best to add an additional update that says we are deleting that.

**Comment by smayden** [comment]
My assumption was that captions on media used the same field storage config. Should it have?

Happy to delete it on my PR if we want.

**Comment by trackleft** [comment]
@smayden I think there is a separate storage config for each type of media even if the field is named the same.

**Comment by trackleft** [comment]
This might work to list field instances 

```
$field_config = \Drupal\field\Entity\FieldStorageConfig::loadByName('node', 'field_machine_name');
```

**Review by joeparsons — APPROVED** [review]

**Comment by camikazegreen** [comment]
This one turned into a monster! Glad it's looking like it should be ready to merge on Friday.

**Review by trackleft — APPROVED** [review]

**Review by camikazegreen — APPROVED** [review]
Looks good on the front end.

**Pull request merged**
