### PR TITLE
Closes #679: Update Drupal core to 9.2.0.

### LINKED ISSUE #679: Upgrade to drupal version 9.2
## Conditions of satisfaction
- [ ] Drupal version should be 9.2
- [ ] All tests should pass.
- [ ] All dependencies should resolve.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
This is based on @trackleft's original [9.2.x-dev branch/PR](https://github.com/az-digital/az_quickstart/pull/680) with a few modifications:

- Updated to 9.2.0 (since it is out now)
- Back-ported [installer performance improvement from core standard install profile](https://www.drupal.org/project/drupal/issues/3086307)
- Back-ported various upstream changes to JS tooling config files
- Merged latest changes from main branch

## Related Issue
#679 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
sweet, I'll be back on the upstream.

**Comment by trackleft** [comment]
Can we downgrade drupal-check here: https://github.com/az-digital/az-quickstart-dev/blob/044426f400649eced898f0a01beb684a9fbd7032/composer.json#L24
?

**Comment by joeparsons** [comment]
> Can we downgrade drupal-check here: https://github.com/az-digital/az-quickstart-dev/blob/044426f400649eced898f0a01beb684a9fbd7032/composer.json#L24
> ?

I replaced drupal-check with phpstan-drupal and phpstan-deprecation-checks in this related PR since we we're calling phpstan directly (instead of drupal-check) in all of our CI configs now, anyway:
https://github.com/az-digital/az-quickstart-dev/pull/15

**Review by trackleft — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
Moved the `az-quickstart-dev` CI changes into a separate issue (#876) and PR (#877).

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Comment by trackleft** [comment]
We've tested the version leading up to this one fairly extensively in the admissions project so I think it can be merged.

**Review by jwmoore1 — APPROVED** [review]

**Pull request merged**
