### PR TITLE
Closes #2442: Update drupal/bootstrap_barrio from 4.30 to 5.1.10.

### LINKED ISSUE #2442: Upgrade drupal/bootstrap_barrio to 5.1.x
Needed for D10 compatibility.

## Conditions of satisfaction
- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

### PR DESCRIPTION
**Pull request by joeparsons**
## Description

- Updates bootstrap_barrio to latest version with Bootstrap 4 compatibility
- Re-rolled @trackleft's old patch for  https://www.drupal.org/project/bootstrap_barrio/issues/3217958 to work with bootstrap_barrio 5.x (@trackleft's patch contains config schema changes not found in any of the d.o. patches or in what has been committed in more recent versions of the theme)
- New patch: https://gist.github.com/joeparsons/7d36cefca83823e93b44cb5b36374b04/

## Related issues

Closes #2442
Also needed for D10 compatibility (#2081)

## How to test

- General front end testing to make sure front-end theme still looks/works as expected
- Test saving changes to theme settings form

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [x] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
FYI, there is a new select menu for "Load library" 
image

**Comment by joeparsons** [comment]
> We should remove that setting in az_barrio.

Good catch @trackleft, thanks!

PR updated.

**Comment by joeparsons** [comment]
We should probably merge az-digital/arizona-bootstrap-packagist#20 together with this one.

Might be necessary to create a new Arizona Bootstrap release to take advantage of that change, though.

**Review by joshuasosa — APPROVED** [review]
Seems to look and work ok all around. Note that if there's ever a decision to use Display Suite, either on an individual site or in the project, `_bootstrap_barrio.layouts.yml` may need to be [copied over](https://www.drupal.org/docs/8/themes/barrio-bootstrap-4-drupal-89-theme/bootstrap-barrio-installation/upgrade-barrio-to-5x).

**Review by bberndt-uaz — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
