### PR TITLE
Closes #692: Add version to info.yml during release action.

### LINKED ISSUE #692: Maintain version reference in az_quickstart.info.yml
## Problem/Motivation
The `version` [property of az_quickstart.info.yml](https://github.com/az-digital/az_quickstart/blob/main/az_quickstart.info.yml#L4) is currently set to `0.0.1`.

The value is displayed in the Drupal install UI and in the site status report and is confusing to developers and site builders.

## Proposed resolution
We should update this value and also add steps to our release workflow(s) to update this value automatically each time we create new releases.

##  Screenshots
Screen Shot 2021-04-27 at 4 02 16 PM
Screen Shot 2021-04-27 at 3 54 56 PM

## Additional context
We used to do something similar in D7 Quickstart (see our old [release.sh script](https://bitbucket.org/ua_drupal/ua_quickstart/src/b6f173f04f28c85ccbd32d08b9611c5b2af50986/release.sh#lines-102:118)).

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Based on the [script steps](https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.0-alpha6/release.sh) we used to use to update info files in Quickstart 1 (a long time ago).  Needs to be tested (probably in a sandbox repo).

## Related issues
Closes #692 

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [x] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
The order of operations makes sense to me.

**Comment by trackleft** [comment]
Any update on the main branch protection rules issue?

**Comment by joeparsons** [comment]
> Any update on the main branch protection rules issue?

Based on the testing that @KyleClements13 and I have done in his sandbox repo, I think we should be good.  I think the best thing at this point may be to merge this and address any issues that come up next time we create a release.

**Review by trackleft — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Comment by joeparsons** [comment]
@trackleft Pointed out we'll need to backport this change into both of our supported release branches as well.

**Review by tadean — APPROVED** [review]

**Pull request merged**
