### PR TITLE
Fixes #537 Relative paths in Cards link field

### LINKED ISSUE #537: Can't use relative paths in Cards link field (related to token issues)
Can’t use relative links in the link field (only allows absolute links)--not good for new sites since the URL changes from dev to live (relative links preferred as an option)

Original documentation: https://docs.google.com/document/d/1NlE2MqbG19mbDmYf3BggrpKKcVBZsrYHe2XnYStZuPE/edit#heading=h.2whr3gihc8cw

### PR DESCRIPTION
**Pull request by tadean**
This pull request adds the ability for cards to use internal paths in the link field.

## Description
This pull request adds the ability for cards to use internal paths in the link field. This requires using a custom validation function because the Form API `url` element does not support internal paths.

Core uses an autocomplete field (that finds entities by titles) for internal paths and we may want to consider this in the future for general availability.

The Card Formatter has had its style of dependency injection updated because the path validator service was being added to it.

**This PR is based on my other card branch (not main) and that PR should be merged first. This PR is fairly small; the large delta is because it is based on `feature/427` and not `main`.**

Consequently, the other card changes will also appear in this branch.

## Related Issue
#537 

## How Has This Been Tested?

- Create a page
- Create cards
- Add links for cards.
- Verify that external links and internal links both work (eg `<front>`, `/node/2/`. `http://www.google.com`) all continue to work.
- Verify that linking to an internal path that doesn't exist produces an error message.
- Create a link to a privileged page, e.g. `/admin/content` and verify that when the card is saved, the link is not rendered for an anonymous user looking at the page.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
image

**Review by smayden — DISMISSED** [review]
Tested as content editor for cards with external links, internal links (node id, friendly url, <front>), admin links, unpublished content links. Working as outlined in ticket.

For future consideration: For links to unpublished pages, I'll be curious to see how that plays with moderation (e.g. when you send a hashed review link for someone to review who is not signed in). We may also want to test with content editors to see if this creates any confusion (seeing the link when they edit pages, but not seeing it when not signed in)

**Comment by joeparsons** [comment]
Link to see just changes specific to this PR:
https://github.com/az-digital/az_quickstart/compare/feature/427...bug/537

**Review by geijutsuka — APPROVED** [review]
Works for me. :)

**Comment by tadean** [comment]
Updated with most recent changes from #634 .

**Review by smayden — APPROVED** [review]
tested again as content editor. All working as expected.

**Review by trackleft — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Review by camikazegreen — APPROVED** [review]

**Pull request merged**
