### PR TITLE
Closes #2529: Remove DB updates added before 2.6.0.

### LINKED ISSUE #2529: Remove database updates older than 2.6.0 ahead of 2.7.0
It would be nice to remove old database updates ahead of releasing 2.7.0.

Drupal provides a hook to facilitate this:
[`hook_update_last_removed()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_update_last_removed/8.2.x)

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Uses [`hook_update_last_removed()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_update_last_removed/8.2.x) to remove DB updates added before 2.6.0.

## Related issues

Closes #2529 

## How to test

- Verify that applying DB updates to a site that was running 2.6.0 or later works correctly.
- Verify that applying DB updates to a site that was running <2.6.0 causes Drupal to complain.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [x] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Did a search https://github.com/search?q=repo%3Aaz-digital%2Faz_quickstart+_update_&type=code&p=1
Found all of the relevant updates included in this PR.

**Review by trackleft — DISMISSED** [review]

**Comment by trackleft** [comment]
I'd like to see a message like `Upgrade to drupal 2.5.8 first` or something.

**Comment by joeparsons** [comment]
This is what it looked like when I tried updating directly from `2.5.0` to `2.7.2-rc2` with these changes applied.

Trying to run DB updates through Admin UI:
Screenshot 2023-06-28 at 12 51 55 PM

Trying to run DB updates through drush:
```
 [error]   (Currently using Removed core modules You must add the following contributed modules and reload this page.
 * Color [1]
 * RDF [2]

These modules are installed on your site but are no longer provided by Core.
For more information read the documentation on deprecated modules. [3]

[1] https://www.drupal.org/project/color
[2] https://www.drupal.org/project/rdf
[3] https://www.drupal.org/node/3223395#s-recommendations-for-deprecated-modules
) 
 [error]  The installed version of the /Quickstart Person/ module is too old to update. 
Update to an intermediate version first (last removed version: 920501, 
installed version: 8000).
```

**Comment by joeparsons** [comment]
FWIW, Drush still allows the updates to be attempted.

```
 Requirements check reports errors. Do you wish to continue? (yes/no) [yes]:
 > y

 ------------------------ --------------------------- --------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Module                   Update ID                   Type            Description                                                                                                                                                                          
 ------------------------ --------------------------- --------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  az_news                  1020701                     hook_update_n   1020701 - Add two new fields to az_news content type to allow overriding news thumbs. Create field_az_featured_image_as_thumb on az_news content type. Create                        
                                                                       field_az_media_thumbnail_image on az_news content type. @see https://github.com/az-digital/az_quickstart/issues/2504                                                                 
  az_paragraphs            920601                      hook_update_n   920601 - Replace broken migrated paragraph_behavior settings with defaults.                                                                                                          
  az_quickstart            920601                      hook_update_n   920601 - Uninstall the deprecated media_library_theme_reset module.                                                                                                                  
  az_quickstart            920602                      hook_update_n   920602 - Change Arizona Bootstrap CDN references.                                                                                                                                    
  az_quickstart            920603                      hook_update_n   920603 - Uninstall deprecated Drupal core modules.                                                                                                                                   
  az_quickstart            920604                      hook_update_n   920604 - Ensure block_class module is installed.                                                                                                                                     
  az_quickstart            920701                      hook_update_n   920701 - Ensure media_entity_file_replace module is installed.                                                                                                                       
  az_quickstart            920702                      hook_update_n   920702 - Enable az_paragraphs_splitscreen module by default.                                                                                                                         
  better_exposed_filters   8003                        hook_update_n   8003 - Provide upgrade path from 8.x-4.x to 8.x-5.x.                                                                                                                                 
  draggableviews           8105                        hook_update_n   8105 - Update varchar length of arg field from 255 to 1024.                                                                                                                          
  google_tag               8200                        hook_update_n   8200 - Update permissions from old google tag module. @param mixed $sandbox   Sandbox. @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException @throws           
                                                                       \Drupal\Component\Plugin\Exception\PluginNotFoundException @throws \Drupal\Core\Entity\EntityStorageException                                                                        
  google_tag               8201                        hook_update_n   8201 - Updates google tag entities from old google tag module. @param mixed $sandbox   Sandbox. @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException @throws  
                                                                       \Drupal\Component\Plugin\Exception\PluginException @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException @throws \Drupal\Core\Entity\EntityStorageException             
  user                     10000                       hook_update_n   10000 - Remove non-existent permissions created by migrations.                                                                                                                       
  az_news                  after_1020701               post-update     Set the new Use Featured Image as Thumbnail field on all news nodes.                                                                                                                 
  block_content            entity_changed_constraint   post-update     Clear the entity type cache.                                                                                                                                                         
  text                     allowed_formats             post-update     Add allowed_formats setting to existing text fields.                                                                                                                                 
  user                     sort_permissions            post-update     No-op update.                                                                                                                                                                        
  user                     sort_permissions_again      post-update     Ensure permissions stored in role configuration are sorted using the schema.                                                                                                         
 ------------------------ --------------------------- --------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 Do you wish to run the specified pending updates? (yes/no) [yes]:
 > 
```

**Comment by joeparsons** [comment]
Some of the updates fail if run with Drush:
```
 [notice] Module color has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>.
 [notice] Module rdf has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>.
>  [notice] Update started: az_quickstart_update_920601
>  [notice] Update completed: az_quickstart_update_920601
>  [notice] Update started: az_quickstart_update_920602
>  [notice] Update completed: az_quickstart_update_920602
>  [notice] Update started: az_quickstart_update_920603
>  [notice] Update completed: az_quickstart_update_920603
>  [notice] Update started: az_quickstart_update_920604
>  [notice] Update completed: az_quickstart_update_920604
>  [notice] Update started: az_quickstart_update_920701
>  [error]  The module color does not exist. 
>  [error]  Update failed: az_quickstart_update_920701 
>  [notice] Update started: google_tag_update_8200
>  [notice] Update completed: google_tag_update_8200
>  [notice] Update started: az_news_update_1020701
>  [notice] Update completed: az_news_update_1020701
>  [notice] Update started: az_paragraphs_update_920601
>  [notice] Paragraph behavior settings fixed on 0 paragraphs.
>  [notice] Paragraph behavior settings fixed on 0 paragraphs.
>  [notice] Update completed: az_paragraphs_update_920601
>  [notice] Update started: better_exposed_filters_update_8003
>  [error]  The module color does not exist. 
>  [error]  Update failed: better_exposed_filters_update_8003 
>  [notice] Update started: draggableviews_update_8105
>  [notice] Update completed: draggableviews_update_8105
>  [notice] Update started: google_tag_update_8201
>  [notice] Update completed: google_tag_update_8201
>  [notice] Update started: user_update_10000
>  [notice] Update completed: user_update_10000
 [error]  Update aborted by: az_quickstart_update_920701, better_exposed_filters_update_8003 
 [error]  Finished performing updates. 
```

**Review by tadean — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
