### PR TITLE
Fixes #3013 Filter Publication Type in Search View

### LINKED ISSUE #3013: Publication Type select list filter: The filter (Drupal View exposed filter) should show only the Publication Types that are being used.
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Motivation
Publication Type select list filter is set to display all publication types. It should only display the Publication Types that are being used.

### Is your feature request related to a problem? Please describe.
The Publication Type select list filter has more than 30 different types, but most of the time Publications only use two or three of them. The filter should show the Publication Types in use only.

## Additional context
https://cancercenter.arizona.edu/biblio

Screenshot 2023-12-13 at 10 49 20 AM
Screenshot 2023-12-13 at 10 54 00 AM

### PR DESCRIPTION
**Pull request by tadean**
## Description
This PR adds functionality to the publication search that trims the list of options to only those which have results.

Presently this is accomplished by adding a new view filter plugin (`az_publication_list_field`) which behaves as a normal ListField filter plugin, except with the additional step that rendering the exposed value form clones the view, executes it, inspects the results, and trims the list of options to only the ones encountered.

Since this PR re-exports the publication view, it also turns on the reset button for the search form, which is a requirement of #3059 

## Related issues
#3013 
#3059 

## How to test

- Enable `az_publication`
- add publications of various types
- Add the search view to a page
- Verify that the list of available options are those that were created

**Note:** this PR should be tested with a large volume of publications to make sure that the performance is acceptable.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
Refactor to integrate with @trackleft upcoming changes to publication type.

**Comment by camikazegreen** [comment]
Here's an example of this applied to a site with many publications:
https://issue-3013-azs-pharmacy.pantheonsite.io/research-outreach/publications

**Comment by trackleft** [comment]
It seems as this PR is no longer necessary, or should be implemented as a database update to change the `status` of the new `az_publication_type` config entities that do not have any referencing entities to `false`.

**Comment by tadean** [comment]
> It seems that this PR is no longer necessary, or should be implemented as a post update hook to change the `status` of the new `az_publication_type` config entities that do not have any referencing entities to `false`.
> 
> See: #2574

I agree. With customizable publication types, this PR is no longer necessary.

**Comment by trackleft** [comment]
Fixed as part of #2574

**Pull request closed without merging**
