### PR TITLE
Closes #2702: Add unpublished content layout to Marketing Cloud

### LINKED ISSUE #2702: Have "Unpublished content" render with view in email for unpublished content
## Conditions of satisfaction
When rendering a Marketing Cloud email, if I insert a URL to an unpublished item, I want to have the rendered "Page not found" message to be specific to the layout.
- Placeholder image
- Unpublished content as header
- Overview about publishing content
- Button with no destination

Desired to have layout match selection (different unpublished page per layout)

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
When rendering a Marketing Cloud email, if I insert a URL to an unpublished item, I want to have the rendered "Page not found" message to be specific to the layout.

## Related issues
Closes #2702

## How to test
1. Enable the `Quickstart for Marketing Cloud` module
2. Unpublish a news and/or event item
3. View the `Content for email` content page
4. Test the rendered links to ensure they show the unpublished content when not logged in

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Hm. Changed the permission settings to allow the unpublished page content to show in Marketing Cloud (anonymous users). But I think there may be a conflict with actual unpublished content permissions. I want to show static public content using the unpublished state rather than actually show unpublished data.

**Comment by danahertzberg** [comment]
Ready for review!

**Comment by bberndt-uaz** [comment]
This looks good! It might be good either in this PR or a follow-up to adjust the twig files so that the HTML is not repeated: you could set variables at the beginning and then use those in the code instead. Setting the variables might look something like this:
```
{% if node.isPublished() %}
  {% set image_src = images.az_marketing_cloud_hero_layout %}
  {% set heading = content.smart_title %}
  {% set summary = content.field_az_summary %}
  {% set button_url = az_canonical_url %}
  {% set button_text = az_canonical_summary_link_title %}
{% else %}
  {% set image_src = '/profiles/custom/az_quickstart/modules/custom/az_marketing_cloud/images/hero-layout-unpublished.png' %}
  {% set heading = 'Unpublished content' %}
  {% set summary = 'This URL will be updated with real content once the item is published on the website.' %}
  {% set button_url = '' %}
  {% set button_text = 'Button' %}
{% endif %}
```

**Review by bberndt-uaz — DISMISSED** [review]

**Comment by danahertzberg** [comment]
Could potentially have custom 404 page content for these paths. Goal is to fix the views sql access check.

**Comment by danahertzberg** [comment]
@bberndt-uaz is taking this on.

**Comment by danahertzberg** [comment]
Approved by me (I can't officially approve because I opened the PR)

**Review by trackleft — APPROVED** [review]

**Review by sanjanans — APPROVED** [review]

**Comment by danahertzberg** [comment]
Before making module standard instead of experimental, ensure documentation about this is created and apparent. Disclosure of unpublished content potentially becoming published is created.

**Pull request merged**
