### PR TITLE
Closes #3102 Some CKEditor editable tags are removed and can't be restored

### LINKED ISSUE #3102: Some CKEditor editable tags are removed and can't be restored
## Problem/Motivation
With Quickstart 2.9, the `class` attribute on `<div>` elements is being stripped from the HTML output for text areas that use a text format with CKEditor 5 as the text editor. The `class` attribute is also removed in the editor source view, and saving the node or block with the text area will remove the `class` attribute from the content in the database as well. This appears to be happening everywhere except for Bootstrap grids from the [CKEditor Bootstrap Grid](https://www.drupal.org/project/ckeditor_bs_grid).

### Describe the bug
This bug seems to be caused by this Drupal core issue:

- [[10.2 regression] CKEditor 5 breaks when “Source”/Source editing button is added and “Manually editable HTML tags” are specified](https://www.drupal.org/project/drupal/issues/3410100)

When trying to add the `class` tag back to the `<div>` element in the "Manually editable HTML tags" for the Standard text format, you get this error message:

> **Error message**
> The following attribute(s) are already supported by enabled plugins and should not be added to the Source Editing “Manually editable HTML tags” field: _Bootstrap Grid (\<div class\>)_.

### To Reproduce

1. Create a page with a Text paragraph set to the Standard text format.
2. Switch to source view and attempt to add a div element with a class.
3. Switch to normal view and back to source view and observe that the class has been removed from the div element.

## Proposed resolution
TBD

### Expected behavior

The Manually editable HTML tags for each CKEditor-based text format in Quickstart should remain consistent from 2.8 to 2.9.

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description

Restores the CKEditor "Manually editable HTML tags" for the Standard text format to the set of tags allowed in Quickstart 2.8.

Possible additional step: Add help text that warns Administrator users not to modify the Manually editable HTML tags until this Drupal core issue is resolved: [[10.2 regression] CKEditor 5 breaks when “Source”/Source editing button is added and “Manually editable HTML tags” are specified](https://www.drupal.org/project/drupal/issues/3410100).

## Related issues

#3102 

## How to test

Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3107.probo.build

Edit a text area, switch to source view, and test some of the [restored elements/attributes](https://github.com/az-digital/az_quickstart/pull/3107/files), such as:

- `<div class="(various test classes)">`
- `<a class="(various test classes)">`
- `<ul class="(various test classes)">`
- `<hr class="(various test classes)">`

The class attribute for these elements should not be removed by the editor and your test classes should be present in the HTML for the page. (For example, if you use the `bg-sky` class, you should see that text with a light blue background.)

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
Given that this is a known 10.2.x regression, I think your approach to revert the changes we made to the editor config in #2968 makes a lot of sense.

I also really like your idea of temporarily adding help text or some kind of notice for Admin users.

**Review by trackleft — APPROVED** [review]

**Comment by bberndt-uaz** [comment]
Due to the Drupal core issue, the entire Standard text format cannot be edited in the UI: the error message about the Manually editable HTML tags blocks any changes to the format until the offending tags are removed. I'm not sure if adding help text about this is sufficient.

Also, it seems that `<hr class>` is not supported, even if it is allowed in both the CKEditor Manually editable HTML tags field and the HTML filter Allowed HTML Tags field. Disabling the HTML filter ("Limit allowed HTML tags and correct faulty HTML") allows classes to be used on `<hr>` elements.

**Comment by bberndt-uaz** [comment]
Troy: Could change validation callback function or make it not happen

**Review by tadean — APPROVED** [review]

**Comment by bberndt-uaz** [comment]
Create one or more follow-up issues regarding the Standard text format not being editable and/or tracking the original Drupal core issue. Also follow-up issue on the `<hr class>` issue.

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
