### PR TITLE
Add ability to place header 1 and header 2 regions in the off-canvas region with a theme setting

### PR DESCRIPTION
**Pull request by michaelhagedon**
## Description

This adds a theme setting to display the header 1 and header 2 regions in the off-canvas region. 

Currently, this only works for `ul` elements in those regions, like the Utility links menu block. Other header 1 and 2 region contents are not supported.

## Related issues

#1358

## How to test

First, enable the theme settings at Components > Navbar with Off Canvas Drawer for mobile devices > Fold header blocks into Off Canvas.

To test header 1, add links to the Utility links menu. Then view the site at medium breakpoint or lower and trigger the off-canvas menu.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [x] New feature
   - [x] Breaking or visual change to existing behavior (not breaking since it's optional, but it does have a visual component)
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation. (Maybe?)
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
@michaelhagedon In order for the ProboCI checks to work, PRs have to be created a from a branch on the main `az-digital/az_quickstart` repo (rather than a fork).  You should have access to push a branch to `az-digital/az_quickstart` directly, but let me know if you run into any trouble.

**Comment by trackleft** [comment]
Now that probo seems to work with outside PRs, I think this is a composer issue more than anything. What if we changed this line? https://github.com/az-digital/az_quickstart/blob/main/.probo.yaml#L16

**Comment by michaelhagedon** [comment]
> @michaelhagedon In order for the ProboCI checks to work, PRs have to be created a from a branch on the main `az-digital/az_quickstart` repo (rather than a fork). You should have access to push a branch to `az-digital/az_quickstart` directly, but let me know if you run into any trouble.

Oh, thanks @joeparsons, we didn't know that. That does put a wrinkle in this workflow that I just made up without asking anyone (fork in ualibraries org to open it up to more library contributors)...

**Comment by michaelhagedon** [comment]
> Now that probo seems to trigger with outside PRs, I think this is a composer issue more than anything. What if we changed this line? https://github.com/az-digital/az_quickstart/blob/main/.probo.yaml#L16

Oh, so this was a probo issue that could maybe be changed? @trackleft 

Possibly also there are other workflows we should follow. Me pushing branch from forks to AZ Digital repos might turn into a bit of a bottleneck. Might be a discussion topic.

**Comment by trackleft** [comment]
> > Now that probo seems to trigger with outside PRs, I think this is a composer issue more than anything. What if we changed this line? [https://github.com/az-digital/az_quickstart/blob/main/.probo.yaml#L16](https://github.com/az-digital/az_quickstart/blob/main/.probo.yaml?rgh-link-date=2022-04-07T22%3A26%3A59Z#L16)
> 
> Oh, so this was a probo issue that could maybe be changed? @trackleft
> 
> Possibly also there are other workflows we should follow. Me pushing branches from forks to AZ Digital repos might turn into a bit of a bottleneck. Might be a discussion topic.

I just checked probo env vars, nothing real useful for this in there
image

**Comment by michaelhagedon** [comment]
> I just checked probo env vars, nothing real useful for this in there 

Weird, `BRANCH_LINK` is wrong?

**Comment by joeparsons** [comment]
Probo's ENV variables assume the branch/PR originated in the same repo.  We'd need to engage Probo support to see whether they could change this.

**Comment by michaelhagedon** [comment]
> Probo's ENV variables assume the branch/PR originated in the same repo. We'd need to engage Probo support to see whether they could change this.

Ah, well unless others want to fix this too, I think we should take this to Friday discussion. There are workarounds, and maybe some are better than what I'm doing here anyway. We're not in a rush on this feature...

**Comment by michaelhagedon** [comment]
So I pushed to `issue/1358` in the az-quickstart repo, and now checks above are passing, so I guess ProboCI just cuts off the fork name. But I guess we'll stay on this PR for discussion.

**Comment by michaelhagedon** [comment]
> So I pushed to `issue/1358` in the az-quickstart repo, and now checks above are passing, so I guess ProboCI just cuts off the fork name. But I guess we'll stay on this PR for discussion.

Except wait, that means GitHub / reviewers will be working off the fork commits, but Probo will be working off this repo's branch. Probably means I need to continue with the new PR: #1478

**Comment by michaelhagedon** [comment]
Declining this in favor of #1478.

**Pull request closed without merging**
