### PR TITLE
Closes #2576 Line breaks converted to HTML in embedded entities

### LINKED ISSUE #2576: Line breaks converted to HTML in embedded entities
## Problem/Motivation
Embedding a menu block within a flexible block can result in extra \<p\> elements due to the way that CKEditor processes embedded entities.

### Describe the bug
Our Standard text format includes a number of filters that are used to process the content of a text field in a specific order. @trackleft identified that the "Convert line breaks into HTML (i.e. \<br\> and \<p\>)" filter is applied AFTER the "Display embedded entities" filter, so any line break in the output of the embedded entity results in extraneous \<p\> elements being added to the final HTML markup.

**Current processing order:**

image

### To Reproduce

1. Create a test menu block (e.g., Second Level Menu)
2. Create a test flexible block and embed the test menu block in the text area, leaving the text format as Standard
3. Add the test flexible block to the site's block layout in a sidebar region
4. Visit a page where the menu block should be displayed and the page will be linked within a nested list of links (e.g. a third-level page)
5. Observe the extra space above each nested list of links

## Proposed resolution
Move the "Display embedded entities" filter to the last place in the filter processing order for the CKEditor Standard text format.

### Expected behavior
Embedded entities should not have any additional formatting applied to them. 

##  Screenshots

**An example of the bug:**

image

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description
Moves the "Display embedded entities" filter to the last place in the filter processing order for the az_standard text format.

## Related issues

#2576 

## How to test

Comparison page showing the extra spaces in the menu block:

 - https://pre-release-azs-quickstart.pantheonsite.io/brian-test-page

Probo page with the fix (steps 1-3 below completed):

 - https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2577.probo.build/pages/text/text-child-page/text-grandchild-page

1. Create a test menu block (e.g., Second Level Menu)
2. Create a test flexible block and embed the test menu block in the text area, leaving the text format as Standard
3. Add the test flexible block to the site's block layout in a sidebar region
4. Visit a page where the menu block should be displayed and where the page will be linked within a nested list of links (e.g. a third-level page)
5. Confirm that no additional \<p\> or \<br\> elements are added to the menu block
6. Confirm that media embeds in blocks (on any page) still work as expected

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ejsamboy — APPROVED** [review]
I ran several tests, and no issues were found.

**Comment by bberndt-uaz** [comment]
Note: linked images in flexible blocks do not work in this PR and in the 2.7.0-rc3 release: the \<a\> element that should be surrounding the image is instead placed in a separate \<p\> element above the div for the image. This appears to be an existing issue.

**Review by joeparsons — APPROVED** [review]

**Comment by joeparsons** [comment]
Should this change be back-ported to 2.6.x?

**Comment by bberndt-uaz** [comment]
I tested a couple sites on 2.6.5 and this issue did not affect them. The filter processing order was updated in [this recent PR for 2.7 as part of a solution to enable linked images](https://github.com/az-digital/az_quickstart/pull/2480).

**Review by tadean — APPROVED** [review]

**Pull request merged**
