### PR TITLE
Bug fix: remove whitespace on cards with no body or link.

### PR DESCRIPTION
**Pull request by mrbeiley**
A bug emerged causing whitespace to show under cards with no body or link. This PR restores the proper behavior. Now, whitespace will only show if a body and/or link is present.

## Description
fixed check for body and/or link. code written by @mrbeiley, @joshuasosa, @bberndt-uaz

## Related issues

Closes: https://github.com/az-digital/az_quickstart/issues/2736

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bberndt-uaz** [comment]
Is the goal to hide the white space only on cards which have no body content and no link content? The use case from the associated issue seems to be about clickable cards, which have a link in the Card Link URL field but nothing in the Card Link Title field. Currently, the PR still shows the extra white space for clickable cards with a URL since that `link` variable in the twig file is not empty.

If it's desired to remove the white space for clickable cards, the `card-body` class could be selectively removed from the div element on line 32 using an if statement such as `{% if title_style == 'title-on-image' and body['#text'] == '' and link['#title'] == '' %}`.

**Comment by joshuasosa** [comment]
Looks good! I'd be in favor of the additional proposed change to make it so clickable cards can eschew the body space when there's no body and no link title.

**Comment by mrbeiley** [comment]
Updated the code to remove whitespace from clickable cards with no body and no link title 
------
Screenshot 2023-11-16 at 4 41 23 PM

**Comment by joeparsons** [comment]
We'll be merging #2940 instead because the numeric branch name of this PR didn't work for Probo / composer.

**Pull request closed without merging**
