### PR TITLE
Fixes #54 Transpiler Architecture

### LINKED ISSUE #54: ES6 Transpiler Architecture
## Motivation
It was noticed in #42 that the existing eslintrc file in use by Drupal core that provides our lint settings is rather geared towards ES6 and transpiled ES5, rather than standard ES5. This lead to the realization that Drupal core's process for how they develop javascript has changed in Drupal 8/9:

- Developers edit and work with `*.es6.js` files
- Development environment uses `yarn` and `babel` to transpile the `es6.js` files to `.js` files, which are what is actually used by the Drupal theme infrastructure
- `.js` files are not intended to be editable by humans
- transpiled `.js` files are a committed part of the codebase; they are not transpiled on the fly during site operation.

More information:
https://www.drupal.org/node/2815083

As documented at https://confluence.arizona.edu/pages/viewpage.action?pageId=105505925 we elected that it would be good to follow this same path, and that we should update our tooling to allow for usage of this process. Going forward, this means we would write our javascript in es6, and allow babel to create the browser-usable versions.

A good first step in that regard would be to update our Lando and DDEV workflows to allow for yarn to be installed and have tooling to run a babel transpile process on our install profile's future `.es6.js` files.

Please see Drupal core's `core/package.json` for necessary dependencies.

### Is your feature request related to a problem? Please describe.
It's currently difficult to write ES5 javascript code that passes the drupal core eslint settings.

### Describe the solution you'd like
Yarn tooling integrated into Lando/DDEV set up with scripts to transpile .es6.js files. It would also be nice if there was "watch" functionality to transpile whenever files change. It's possible that lack of true `inotify` support in VMs may complicate watch functionality - TBD.

### Describe alternatives you've considered
Available alternatives:

- Continue to write ES5 javascript with a custom `eslintrc.json` to avoid problematic eslint sniffs that are difficult to avoid in readable ES5.

## Additional context
This avenue was chosen due to desiring to follow core-friendly workflows, and the knowledge that ES6 will gradually become the browser standard as time goes on.

### PR DESCRIPTION
**Pull request by tadean**
This pull request provides the ability for local development users to transpile es6 javascript to es5 javascript.

## Description
This pull request sets up the local development environments to be able to use es6 transpilation in following the conventions of Drupal core, which now uses [ES6 Transpilation](https://www.drupal.org/node/2815083) for all of its javascript.

In the case of Lando, this involves adding a Node container to the toolstack. DDev already has yarn and node installed in its web containers. For both DDev and Lando, commands have been added for `yarn` and `eslint`. 

Because Drupal core [does not currently support transpiling contrib code](https://www.drupal.org/project/drupal/issues/2957390), some of those scripts and infrastructure are reproduced here with necessary modifications. Some of these files could be removed after the contrib issue is resolved.

## Related Issue
#54 

## How Has This Been Tested?
**Lando:**
```
git clone https://github.com/az-digital/az_quickstart.git foldername
cd foldername
git checkout feature/54
lando start
lando install
lando eslint .
lando yarn build (one time build)
lando yarn watch (watches for changes)
```

**DDev:**
```
git clone https://github.com/az-digital/az_quickstart.git foldername
cd foldername
git checkout feature/54
ddev config --project-type php
ddev start
ddev install
ddev eslint .
ddev yarn build (one time build)
ddev yarn watch (watches for changes)
```

Output should resemble the following:
```
user@hostname:~/ddev-example$ ddev eslint .

/usr/local/quickstart-install-profile/modules/custom/az_blocks/js/az_blocks_az_accordion.es6.js
   9:2   warning  Unexpected unnamed function  func-names
  17:30  warning  Unexpected unnamed function  func-names
  25:19  warning  Unexpected unnamed function  func-names

3 problems (0 errors, 3 warnings)

user@hostname:~/ddev-example$ ddev yarn build
yarn run v1.22.4
$ yarn build:js
$ cross-env BABEL_ENV=quickstart node ./scripts/js/babel-es6-build.js
[23:51:03] './modules/custom/az_blocks/js/az_blocks_az_accordion.es6.js' is being processed.
[23:51:04] './modules/custom/az_blocks/js/az_blocks_az_accordion.es6.js' is finished.
Done in 0.48s.
user@hostname:~/ddev-example$ ddev yarn watch
yarn run v1.22.4
$ yarn watch:js
$ cross-env BABEL_ENV=quickstart node ./scripts/js/babel-es6-watch.js
[23:51:08] Watching './**/*.es6.js' for changes.
[23:59:39] 'modules/custom/az_blocks/js/az_blocks_az_accordion.es6.js' is being processed.
[23:59:39] 'modules/custom/az_blocks/js/az_blocks_az_accordion.es6.js' is finished.
```
**NOTE:** Drupal core's current processes for how this functionality works [does not currently work with contrib modules](https://www.drupal.org/project/drupal/issues/2957390). That is why some of the infrastructure (`package.json` etc) is reproduced here in this pull request. This is something that should be considered before this is a candidate for merging. Ideally, once core supports the compilation of contrib module js, these files should be removed and leave only the container toolings.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
Changed Eslint step on probo test because our original invocation wasn't actually using the `.eslintignore` that is intended to only run on `.es6.js` files (transpiled ES5 doesn't meet Drupal's lint requirements by design).

**Comment by tadean** [comment]
Looks like in the latest version of `drupal-check` there's a new bit of deprecated code in `cas`:
```
 ------ --------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/cas/src/Plugin/Validation/Constraint/CasProtectedUserFieldConstraintValidator.php  
 ------ --------------------------------------------------------------------------------------------------- 
  55     Call to deprecated method getStorage() of class Drupal\Core\Entity\EntityManager:                  
         in drupal:8.0.0 and is removed from drupal:9.0.0.                                                  
         Use \Drupal\Core\Entity\EntityTypeManagerInterface::getStorage() instead.                          
 ------ ---------------------------------------------------------------------------------------------------
```

**Comment by tadean** [comment]
Lando and DDev take different approaches to installation of Node and friends - DDev's webserver  images have node and yarn already installed as a convenience, and Lando encourages the workflow of adding an extra node container; Lando's default web containers don't have node and yarn.

This means that in general, Lando's node container doesn't have access to the composer vendor packages, since those are inside the web container and not shared with the host. This means that currently, some files from core need to be duplicated into the profile (package.json etc, js scripts) so Lando's node container can access them.

A point of discussion for this PR would be whether or not an alternate solution should be looked into for that. Some possibilities:

- Deciding duplicating some of core's js tool configuration is okay, or an opportunity to customize for Quickstart.
- Install node/yarn onto Lando's appserver image at build time to not need a separate node container, in order to use core's js files.(might be a little messy)
- Swap out lando's regular image for another one that includes node/yarn.
- Create a custom image based on the Lando ones that also installs node/yarn.

**Comment by tadean** [comment]
- [ ] Refactor existing .es6.js file to be true es6 js

**Comment by tadean** [comment]
Merged in the latest changes to master to include @joeparsons patch for CAS deprecation warnings.

**Comment by joeparsons** [comment]
More review would be helpful.  Especially:
- Make sure this doesn't introduce any problems to the lando and ddev build processes
- Check that the yarn watch functionality detects file system changes on macOS / Windows (@tadean has only been able to test on Linux)

**Comment by tadean** [comment]
I'm leaning towards refactoring the existing accordion js file to theme calls, since Drupal already has some functions for unique ids/classes.

**Pull request merged**
