### PR TITLE
Closes #682: Added Better Exposed Filters module.

### LINKED ISSUE #682: Add Better Exposed Filters module
https://www.drupal.org/project/better_exposed_filters

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Adds Better Exposed Filters module and dependencies.  Does not enable module by default.

## Related Issue

#682 

## How Has This Been Tested?

Locally with lando

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Here are a few items from my first pass at using this module on probo.

https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-683.probo.build/dana-test-events

- I had to enable other modules for this to work: 
     - You must enable the jQuery UI, jQuery UI Slider, jQuery UI Touch Punch, jQuery UI Datepicker modules to install Better Exposed Filters.
- Disabling the block feature allowed me to see the functionality working as expected. 
     - I can't click on the category name to select (but that might be fixable with CSS?).
- I was unable to view my placed the BEF block in the sidebar first region. 
- I also noticed there are 2 "Content type" tabs with block settings. (Not related to this PR) image

**Comment by danahertzberg** [comment]
Issue related to block visibility: https://www.drupal.org/project/drupal/issues/1932810

**Comment by joeparsons** [comment]
This core issue is probably related to the weird block visibility issues:
https://www.drupal.org/project/drupal/issues/1932810

**Review by trackleft — APPROVED** [review]

**Comment by danahertzberg** [comment]
Is there another D9 module that achieves the same goals? 

This add-on module for BEF might also be useful, but can be addressed separately. https://www.drupal.org/project/selective_better_exposed_filters

**Comment by danahertzberg** [comment]
Just verified the block appears in the sidebar as expected. (Path needs a / in front of it in D9) As long as we are okay with adding this module and its dependencies, this PR is ready to merge from my perspective.

**Review by danahertzberg — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
Per discussion in 2021-05-28 meeting discussion, we would like to research what it would take to provide the checkboxes / autosubmit functionality without adding this module before merging.

**Comment by danahertzberg** [comment]
Should probably consider merging this, then investigating other replacement solutions

**Comment by danahertzberg** [comment]
Moving to September 2021 release to address later

**Pull request closed without merging**
