### PR TITLE
Closes #1490: Adding content admin/editor permissions for node clone, block classes, metatag, reports

### LINKED ISSUE #1490: Expand permissions for content admin role
## Motivation
In the ramp up to launch Arizona.edu in Quickstart 2 there were several key functions/permissions needed that currently cannot be addressed in the content admin role.

### Is your feature request related to a problem? Please describe.
Content admins need access to:

- Site Information (set homepage, 403, 404)
- Configure block css classes
- Tag Manager configuration (add Tag Manager ID)
- Reports (view reports related to search, 403, 404, etc)
- Metatag module configuration (configure defaults for different content types)
- Quick Node Clone

### Describe the solution you'd like
Expand content admin role to include permissions to the areas outlined above. 

### Roles and Permissions considerations
- Content administrator - would expand permissions

### PR DESCRIPTION
**Pull request by smayden**
## Description
This PR adds several permissions to the content admin role:
- Administer block classes
- Administer Meta Tag
- View Site Reports
- Edit terms for page categories (I noticed this was missing when reviewing permissions)

It also add the following to the Arizona Quickstart Settings page that content admins can already access
- Set front page
- Set error pages (403/404)

The PR also gives permissions for content editors to clone pages (using Quick Node Clone).

## Related issues
#1490

## How to test
Test site: https://f9acc535-3b5b-46b0-aedf-a06ac37afc39.probo.build/

Log in as admin and make sure the following modules are enabled:
- Quick Node Clone
- Block Class
- Metatag

Log in as azcontentadmin:
- Verify that you can see Reports
- Verify that you can add a class to a block
- Verify that you can edit global Metatag settings
- Go to Arizona Quickstart Settings and verify you can set homepage, 404 page and 403 page

Log in as azcontenteditor:
- Verify that you can clone a page

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
I bet you could add stuff to the quickstart settings form like we do here:
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php#L92-L97

And  here: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php#L160-L162

**Comment by joeparsons** [comment]
We should be able to copy the `site_403` and `site_404` form elements from this form as well as the validation:

https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php

**Comment by joeparsons** [comment]
> We should be able to copy the `site_403` and `site_404` form elements from this form as well as the validation:
> 
> [git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php](https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php)

Relavent lines:
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php#L135-153
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php#L179-199
https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/system/src/Form/SiteInformationForm.php#L213-214

**Review by trackleft — APPROVED** [review]
Even though I a mildly hesitant to add the Google Tag Manager Role to az_content_admin for arizona sites, I defer to marketing.

Only because if someone deletes the GTM container they will be in effect opting out of the az comprehensive google tag.

**Review by trackleft — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Pull request merged**
