### PR TITLE
Fixes #2512 Cursor missing in new text area on Chrome

### LINKED ISSUE #2512: CKEditor: Cursor is missing on Chrome when a new line has not text -Textarea- (2.7 RC1)
### Describe the bug
The cursor is missing on Chrome when a new line (Textarea) has no content.

### To Reproduce

1. Login at https://pre-release-azs-quickstart.pantheonsite.io/
3. Go to content > add content > page
4. Add a Text paragraph feature (Text format: Standard or Basic HTML) under "Main Content"
5. Click in the text area.

## Proposed resolution
A proposed solution can be found at https://www.drupal.org/project/ckeditor/issues/3340103

### Expected behavior
The cursor should appear when you click in the text area with or without content.

##  Screenshots

Screenshot 2023-06-21 at 4 50 46 PM

### PR DESCRIPTION
**Pull request by trackleft**
## Description
CSS Only fix for ckeditor, specifically for chrome.

## Related issues
Fixes #2512 

## How to test
Using Chrome browser
Create a new page
Add a text area
See if cursor appears when selecting the text area.

Using Other browsers
Create a new page
Add a text area
See if cursor appears when selecting the text area.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Patch seems to work.

**Review by joeparsons — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]
Tested successfully as azcontenteditor

**Comment by trackleft** [comment]
Probo link https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2513.probo.build/

**Comment by ejsamboy** [comment]
Looks good on Chrome. Thank you, Chris!

https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2513.probo.build/

**Review by ejsamboy — APPROVED** [review]
I ran several tests, and it is working on Chrome!

**Pull request merged**
