### PR TITLE
Fixes #139 Create Sidebar Menu Block

### LINKED ISSUE #139: Create Side Menu Block
In Structure > Blocks

### PR DESCRIPTION
**Pull request by tadean**
This pull request modifies the existing sidebar menu block to add settings for the `menu_block` contrib module to more closely reflect the appearance of the sidebar menu in D7 `ua_quickstart`.

## Description
This pull request adds the `menu_block` contrib module, swaps the existing system block plugin for the sidebar block for the `menu_block` plugin version, and [adds a patch](https://www.drupal.org/files/issues/2020-05-03/2809699-162-dynamic-block-titles.patch) to address the need for the block title of the sidebar to be the root parent of the current page (for ua_quickstart parity)

## Related Issue
#139 

## How Has This Been Tested?
- Add content pages
- Add content pages to the main menu
- Navigate to the content pages
- Verify that their active trail displays correctly in the lefthand sidebar
- Verify the sidebar does not display on the front page
- Verify that sidebar descendant children do not display before they should (e.g. before their parent is selected)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
The following items still need resolution:

- [ ] Whole active trail is currently highlighted rather than only the active link (in D9 the active link is handled client side by js)
- [ ] Each item of the current level should receive its own box.
- [ ] Presence of the actual main menu and the sidebar menu seems to confuse Drupal when twig debugging is on.

**Comment by tadean** [comment]
image

**Comment by joeparsons** [comment]
Looks like some PHPunit tests are failing due to this issue:
https://www.drupal.org/project/menu_block/issues/3182983

**Comment by tadean** [comment]
> Looks like some PHPunit tests are failing due to this issue:
> https://www.drupal.org/project/menu_block/issues/3182983
> 
> ```
> Drupal\Tests\az_cas\Functional\AzCasAdminSettingsTest::testPasswordResetBehavior with data set #0 (false)
> Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' constraint (9.1.3) requires the 'core' key not be set in modules/contrib/menu_block/tests/modules/menu_block_test/menu_block_test.info.yml
> ```
> 
> https://app.probo.ci/#/dashboard/build/89a984eb-a64c-4ac2-9b17-54b4d1a5f8d8/task/5e18d54686400001
> 
> Oops, you already mentioned this in your summary comment. Sorry.

Thanks for finding that patch @joeparsons ! Due to it being against dev, an intermediary patch was also needed where the `core_version_requirement` property got added to the test module: https://www.drupal.org/files/issues/2020-11-11/3146665_7.patch

**Comment by danahertzberg** [comment]
In D7, we updated the styles in bootstrap (nav-stacked pills) http://uadigital.arizona.edu/ua-bootstrap/components.html#nav

Should we do the same for the style updates you applied here? (indentation, borders, etc.)

**Comment by tadean** [comment]
> In D7, we updated the styles in bootstrap (nav-stacked pills) http://uadigital.arizona.edu/ua-bootstrap/components.html#nav
> 
> Should we do the same for the style updates you applied here? (indentation, borders, etc.) We might even have a ticket to update styles already.

I think either updating the bootstrap styles or adding necessary class components here would be okay - I think the main question would be which class to pin the styles on, since I think in Bootstrap 4, `nav-stacked` which was used in D7, might no longer exist.

**Comment by danahertzberg** [comment]
I'm seeing we are already using `nav` `nav-pills` and `flex-column` classes which align with the BS4 vertical nav element already. The nested menu ul has a custom `menu` class on it. I would recommend we keep the same classes for all levels (`nav` `nav-pills` `flex-column`) and we can style that in bootstrap similar to how I defined styles in BS3.

**Comment by tadean** [comment]
Updated:

- Reverted styles with the exception of the flex-column and pills wrapper.
- Deleted a stray twig `dump()` statement from the original main menu that was causing recursion when twig debugging was turned on if and only if both the main menu and menu block were present on the same page.

**Review by joeparsons — APPROVED** [review]

**Review by smayden — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Pull request merged**
