### PR TITLE
UADIGITAL-2110 Add az_cas module for CAS integration and configuration.

### PR DESCRIPTION
**Pull request by joeparsons**
This is @trackleft's PR copied from BitBucket.

- [ ] Consider excluding CAS module from drupal-check temporarily
- [x] Create d.o. issue for CAS module PHPunit deprecation warnings
- [x] resolve merge conflict(s)

### CODE REVIEW

**Comment by joeparsons** [comment]
Comments/tasks copied from BitBucket:

Look like we need to create a new Drupal.org issue for the CAS module PHPunit deprecation warnings (if one doesn’t already exist).

[ ] - Consider excluding CAS module from drupal-check temporarily
[ ] - Create d.o. issue for CAS module PHPunit deprecation warnings

**Comment by joeparsons** [comment]
@trackleft is going to make sure the latest commits on BitBucket are pushed here.

**Comment by trackleft** [comment]
Opened an issue on Drupal.org regarding drupal 9 readiness errors.
https://www.drupal.org/project/cas/issues/3110204

**Comment by barrettbaffert** [comment]
- [ ] resolve merge conflict(s)

**Comment by trackleft** [comment]
Moved here: https://github.com/az-digital/az_quickstart/pull/53

**Pull request closed without merging**
