### PR TITLE
#444 Updating sidebar nav heading styles

### LINKED ISSUE #444: Add .nav-stacked styles to Arizona Bootstrap
Update the heading on sidebar navs to contain the classes `h4` `mt-md-5`

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
Add bootstrap classes to sidebar nav heading to align with title and make smaller font size

## Related Issue
Closes #444 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Halp please! 🙏🏻

**Comment by trackleft** [comment]
I've updated this PR, hopefully it is correct.... See https://c3bd172a-d131-4f00-922a-7939fa60e647.probo.build/people

**Review by trackleft — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Review by smayden — APPROVED** [review]
This works as I would expect, although like Chris I may not be remembering why we originally were wanting/needing this to be region specific.

**Review by trackleft — APPROVED** [review]
Checked and the hook suggestion is sidebar and the template works in all regions.
Screen Shot 2021-07-01 at 3 44 39 PM

**Review by tadean — APPROVED** [review]

**Pull request merged**
