### PR TITLE
Fixes #3737 SlevomatCodingStandards

### LINKED ISSUE #3737: SlevomatCodingStandards errors
## Conditions of satisfaction
Standards from `slevomat/coding-standard` appear to be throwing an error now, presumably from a change somewhere in the non-pinned `drupal/core-dev`.

We should resolve the sniff issues involved.

### PR DESCRIPTION
**Pull request by tadean**
## Description
This PR attempts to resolve sniff errors that are being raised from `slevomat/coding-standard` - it seems like these may have come in from an update to our non-pinned `drupal/core-dev`?

## Related issues
#3737 

## How to test

- Verify migrations that look up paths still work correctly
- Verify HTTP Cached migrations still work
- Verify that Trellis Event Search/Importer works
- Verify that paragraphs that have behavior settings still work

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [x] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by tadean** [comment]
Seems like maybe the raised errors are due to a chance in case sensitivity?

**Comment by tadean** [comment]
This was due to the change in `drupal/coder` that was [released this week](https://www.drupal.org/project/coder/releases/8.3.25)

This comes in from our dependency on `drupal/core-dev`

**Review by bberndt-uaz — APPROVED** [review]
I tested in Probo:

- **Verify migrations that look up paths still work correctly:** Since the demo content was installed correctly, I believe this is verified?
- **Verify HTTP Cached migrations still work:** I successfully imported courses using the Quickstart Course module with Quickstart HTTP installed.
- **Verify that Trellis Event Search/Importer works:** I successfully searched for and imported Trellis events.
- **Verify that paragraphs that have behavior settings still work:** Verified on a test page.

**Review by trackleft — APPROVED** [review]
Thanks, I like this better.

**Pull request merged**
