### PR TITLE
Issue/333 add proxima nova to barrio

### LINKED ISSUE #333: Update Barrio theme to include Arizona Bootstrap's centrally managed proxima nova font
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

Follow up https://github.com/az-digital/arizona-bootstrap/issues/154

- [x] admin/appearance/settings/az_barrio shows a dropdown with proxima nova (include everything)
- [x] ensure icons appear in just one area of admin/appearance/settings/az_barrio (currently in two accordions) 
- [x] font loads as expected

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Add the ability to add the centrally managed proxima nova font via a checkbox within the az_barrio subtheme.

## Related Issue
Closes #333 

## How Has This Been Tested?
Locally and on Probo
When I go to the the theme settings on az barrio and navigate to the fonts and icons section, there is a checkbox that allows me to enable or disable proxima nova, additionally, there is some new description text and a link to the documentation for the font on arizona bootstrap.

This setting is on by default. And allows other subthemes to easily remove the setting or use a different typekit project.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by barrettbaffert — APPROVED** [review]
This is what I expected to see with this ticket. Thanks @trackleft !

**Comment by trackleft** [comment]
In this PR:

- Add the centrally managed proxima nova font as a library for az_barrio to use.
- Rename the theme setting for material design icons to `use_material_design_sharp_icons`
- Add both, font and icons as dependencies of arizona-bootstrap if they are enabled.
- Set defaults for both font and icons to tru
- Move az-brand-icons settings to the icons tab
- Remove the material design icons section from the theme settings page
- Remove bootstrap barrio inherited theme settings from config form
- Updated external docs links for fonts and icons to open in new tabs.

**Comment by joeparsons** [comment]
I think we should also add your new config settings to the config schema here:
https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/config/schema/az_barrio.schema.yml

**Comment by trackleft** [comment]
Add new settings to config schema file

**Review by tadean — DISMISSED** [review]

**Review by barrettbaffert — APPROVED** [review]

**Review by joeparsons — DISMISSED** [review]

**Review by jwmoore1 — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
