### PR TITLE
Closes #1307: Allow unpublishing of published content and allow the latest revision to be a draft.

### LINKED ISSUE #1307: Cannot unpublish content when it is under moderation.
Currently we can not unpublish content if it is under moderation.

## Problem/Motivation
There is no way to unpublish content once it has transitioned to the published moderation state.

### Describe the bug
Because you can not set a revision that is a draft to the default revision it is not possible to unpublish content.

### To Reproduce

Turn on content moderation module
Add some content and set the moderation state to published.
Try to unpublish it, and not be able to.

## Proposed resolution
Allow draft revisions to be set as the default revision.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Add an unpublished state
Allow content in draft transition to unpublished which unpublishes the content (default_revision).
Allow drafts to remain just drafts (can't be the default_revision)
Allow published  to remain published (default_revision)
Allow content in published state to have drafts that aren't published (default_revision)

## Related Issue
Closes #1307 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by joeparsons — DISMISSED** [review]
Seems reasonable to me.

**Review by smayden — CHANGES_REQUESTED** [review]
Tested as admin, content editor and content admin.

This worked well as an admin, but content admin does not seem to be able to the unpublish state.

**Comment by trackleft** [comment]
> Tested as admin, content editor and content admin.
> 
> This worked well as an admin, but content admin does not seem to be able to the unpublish state.

Oh man, forgot permissions.

**Comment by smayden** [comment]
I think both content admins and content editors should have permission

**Comment by trackleft** [comment]
updated

**Comment by camikazegreen** [comment]
> I think both content admins and content editors should have permission

Is this the kind of change that we will need to add a DB update during install for after we upgrade to 9.3?

**Review by smayden — DISMISSED** [review]
Now works as content editor and content admin. Thanks!

**Comment by trackleft** [comment]
> > I think both content admins and content editors should have permission
> 
> Is this the kind of change that we will need to add a DB update during install for after we upgrade to 9.3?

This would need a database update if people have the content moderation module enabled.

**Review by smayden — APPROVED** [review]
tested again across all editor roles, looks good

**Review by danahertzberg — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]
Seems OK from a code changes perspective.

**Pull request merged**
