### PR TITLE
Closes #3438: Image captions visible in AZ News - Recent News Marquee paragraph

### LINKED ISSUE #3438: Image captions visible in AZ News - Recent News Marquee paragraph
## Problem/Motivation
Image captions are visible when the top story has an image with captions set. This looks visually unappealing and can be difficult to work with if the captions are lengthy. The following 3 news items (also included with the Recent News Marquee display) do not display captions. Should captions be displayed uniformly among these 4 news items?

### Describe the bug
Captions are displaying in a teaser display when perhaps they should not be.

### To Reproduce

1. Create at least one AZ News node.
2. Ensure that your new News node has a Featured Image set and that it has captions.
3. Place a View paragraph on any Flexible page and set View to be AZ News and Display to be Recent News Marquee.
4. You should see the captions displayed and they push down the date/title/CTA.
5. If you add additional News nodes, you will notice the following 3 stories displayed do not have captions visible.

## Proposed resolution
Adjust the Marquee view mode of AZ News to not display captions. Also, verify that this view mode is only used for this purpose.

### Expected behavior

No captions should display for these teaser views. Or, all captions should display for these teaser views.

##  Screenshots

Screenshot 2024-05-20 at 9 19 23 AM

Screenshot 2024-05-22 at 8 54 16 AM

### PR DESCRIPTION
**Pull request by djcelaya**
## Description

Removes the image caption on Recent News Marquee view paragraphs.

### Release notes

If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)

Make sure to add the `release notes` label to this PR.

```
Image captions are no longer displayed on the top AZ News story when using the Recent News Marquee display option of the View paragraph.
```

## Related issues

#3438 

## How to test

1. Navigate to the [Pages > News Views page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3937.probo.build/pages/news-view-paragraphs) and scroll to the bottom.
2. In the Recent News Marquee section, verify that the [top story (Could Man's Best Friend Be Man's Best Medicine)](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3937.probo.build/news/could-mans-best-friend-be-mans-best-medicine) is not displaying any image captions. You can see what the image caption should be by looking at the [full story](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3937.probo.build/news/could-mans-best-friend-be-mans-best-medicine).

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [X] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [X] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by djcelaya** [comment]
@danahertzberg Does the spacing look OK underneath the corgi image?
Screenshot 2024-12-11 at 8 40 28 AM

**Comment by bberndt-uaz** [comment]
**Quick comparison:**

https://demo.quickstart.arizona.edu/pages/news-view-paragraphs

(loads an 1140 x 763 px image)

image
<p> </p>

https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3937.probo.build/pages/news-view-paragraphs

(loads a 568 x 426 px image)

image

**Review by trackleft — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Comment by djcelaya** [comment]
To address the documentation, I propose changing this page: https://quickstart.arizona.edu/create-content/adding-news-pages
Screenshot 2025-04-14 at 2 54 29 PM

Change this line:
Photo is the image used in the preview mode
Photo is the image used in the preview mode. The captions associated with this photo are not displayed in preview modes.

**Comment by djcelaya** [comment]
Documentation has been updated.

**Pull request merged**
