### PR TITLE
Closes #1567 Adds Admin Toolbar modules and enables by default.

### LINKED ISSUE #1567: Add Admin Toolbar module and enable by default
## Motivation
Coffee module was previously added to enable quick admin path navigation.

Adding Admin Toolbar would further enhance the UI/UX for site builders and content maintainers by providing quick access dropdowns for the Toolbar. This module reduces clicks and page loads needed for those users.

### Describe the solution you'd like
Enable the following modules by default:
 - [Admin Toolbar](https://www.drupal.org/project/admin_toolbar)
   - Admin Toolbar Extra Tools (submodule)
   - Admin Toolbar Links Access Filter (submodule)
 - [Admin Toolbar Content](https://www.drupal.org/project/admin_toolbar_content)

### PR DESCRIPTION
**Pull request by joshuasosa**
## Description
Adds and enables:

- [Admin Toolbar](https://www.drupal.org/project/admin_toolbar)
  - Admin Toolbar Extra Tools (submodule)
  - Admin Toolbar Links Access Filter (submodule)
- [Admin Toolbar Content](https://www.drupal.org/project/admin_toolbar_content)

## Related issues
Closes #1567.

## How to test
Install AZQS and it is enabled for admins right away. Hover over admin toolbar elements to see dropdown options.

Tested locally on DDEV.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [x] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joshuasosa** [comment]
Available to try at: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1656.probo.build/user

**Comment by camikazegreen** [comment]
@joshuasosa We reviewed this PR and discussed whether or not we should add and maintain these modules in the Quickstart codebase. We decided to leave it up to the discretion of the site owner/developer whether or not they would like to add the admin toolbar to their sites, so we are closing this PR without merging.

**Comment by joshuasosa** [comment]
> @joshuasosa We reviewed this PR and discussed whether or not we should add and maintain these modules in the Quickstart codebase. We decided to leave it up to the discretion of the site owner/developer whether or not they would like to add the admin toolbar to their sites, so we are closing this PR without merging.

That's unfortunate. Can we disable and uninstall Coffee module then since it's in the same line of interest: a convenience tool for site builders?

**Comment by camikazegreen** [comment]
That is a fair point, but we are not opposed to adding convenience tools for site builders. There have been many features added to improve the user experience of developers, site builders and content administrators.

The factor that weighed on this decision was that we couldn't come to a consensus about whether or not this user experience was considered an improvement. Some site builders actively did not want this change while others did. Quickstart is designed to be extendable so that it can meet the needs of both.

**Comment by joshuasosa** [comment]
None of my site users use Coffee after learning about it. Most of them use admin_menu for a much easier and more sensible user experience than remembering keyboard shortcuts. Admin Toolbar provides a significantly better user experience than Coffee for regular site builders and content maintainers.

**Pull request closed without merging**
