### PR TITLE
Closes #1043 | Add pronoun field to AZ Person

### LINKED ISSUE #1043: Add "pronoun" field to AZ Person content type
## Motivation
Campus partners frequently request that a "pronoun" field be added to the Person content type. Given how common the request is, it would be good to add it to the Person content type by default.

## Proposed Resolution

- [ ] Add `field_az_pronoun` to the Person content type
- [ ] Add the field to the main display of the content type (after name)
- [ ] Add the field to the card display of the content type (after name)
- [ ] Add the field to the row display of the content type (after name)

### PR DESCRIPTION
**Pull request by akslay**
## Description
Many site editors request the addition of a "pronoun" field (both on Quickstart 1.0 and 2.0). This is something many sites could benefit from due to its common use. Changes include:

- Adds `field_az_pronoun` field to the Person content type
- Updates the default display template to include the field
- Updates the card display template to include the field
- Updates the row display template to include the field
- Updates the entity form display (`az_person`) to include the field
- Updates the entity form display (`az_seo`) to include the field
- Adds a README file to `az_person` to document the fact that the entity form display must be updated in 2 places if a field is ever added to the content type.

The field is added to the tertiary information to match the ordering that Brand utilizes on their [email signature generator](https://brand.arizona.edu/generator/email-signature).

Review pages:

- Grid: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1053.probo.build/people
- Row: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1053.probo.build/people-list
- Node: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1053.probo.build/person/jose-anersen 

## Related Issue
Closes #1043 

## How Has This Been Tested?
Tested locally. Pending test on Probo.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
I'm seeing an empty parenthesis on people. 
image

**Comment by akslay** [comment]
> I'm seeing an empty parenthesis on people.

Looks like it wants the `.0` for the field. Updating the PR. Thanks for finding that @trackleft

**Comment by akslay** [comment]
Question: is it necessary to maintain 2 copies of the Person entity form display file? It looks like `az_seo` is on by default, so that version of the entity form display file will always be used since it's the override. Would we be able to get away with just maintaining one copy by adding `az_metatag` as a dependency of Person?

**Comment by joeparsons** [comment]
Nitpick:  wouldn't `field_az_pronouns` (plural) be a more accurate machine name for the field?

**Review by geijutsuka — APPROVED** [review]

**Review by camikazegreen — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by smayden — APPROVED** [review]

**Comment by akslay** [comment]
Follow-up tasks/tickets:

- [ ] Demo content to include pronouns
- [ ] Confirm placement, format, and label usage with John Denker and Ivy Banks

**Review by geijutsuka — APPROVED** [review]

**Pull request merged**
