### PR TITLE
Fixes #72 Add Chromedriver to Tooling Stack

### LINKED ISSUE #72: Figure out ChromeDriver dependencies for tooling stack
## What is the problem that we want to solve?
We need to be able to run D8 Javascript Functional Tests both locally and on our CI tools.

We should look into what Drupal.org is doing for this and also at what tools are already installed/available on ProboCI's docker images.

UC Davis' SiteFarm project has Functional Javascript tests and they use ProboCI.

## Conditions of satisfaction
- [ ] Test dependencies are documented
- [ ] Lando/ddev support is considered

### PR DESCRIPTION
**Pull request by tadean**
This pull request adds Chromedriver to our local development tool stack so we can write javascript tests. A javascript test is included (for cards).

## Description
WIP.

- needs more investigation on ddev and probo.
- security sandbox issue - perhaps this can be gotten around by running as a specific user

## Related Issue
#72 

## How Has This Been Tested?
Run php unit tests in ddev or lando.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
This PR started inexplicably not working the other day. After a lot of trial and error I located this in the chromedriver log:
```
[1622821247.417][INFO]: [44bdec901ade8452da307168b8b94151] RESPONSE InitSession ERROR session not created: This version of ChromeDriver only supports Chrome version 91
```

The effect of this is that all javascript tests were passing even if they should not. Looks like on probo we'll need to pin the chromedriver version to the chrome version somehow.

**Comment by tadean** [comment]
Updated to attempt to figure out which version of chromedriver we should be using to match the probo machine's chrome binary.
```
Chromedriver version is 90.0.4430.24.
```

With a compatible version now, the deliberately broken test is now (correctly) failing:
image

**Comment by tadean** [comment]
Removed (WIP) tag. Ready for review.

**Review by joeparsons — APPROVED** [review]
This looks good to me.  Nice job @tadean.  Thanks!

**Review by kevcooper — APPROVED** [review]

**Comment by joeparsons** [comment]
Latest Probo build didn't have any issues.

**Pull request merged**
