### PR TITLE
Closes #572 - Add reorder carousel items view display

### LINKED ISSUE #572: Create Reorder Carousel view
## Motivation
Provide ability to reorder carousel content type items

## Conditions of satisfaction
- [ ] Should be restricted to authenticated users
- [ ] Should use row weights or draggable weights
- [ ] Should update the order of carousel items on save

### PR DESCRIPTION
**Pull request by akslay**
## Description
 PR adds a view display to reorder Carousel Items in the AZ Carousel view.

Review link: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-664.probo.build/

## Related Issue
Closes #572

## How Has This Been Tested?
- Tested locally
- Probo build test (pending)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by akslay** [comment]
Need some guidance from the group on how best to proceed with this change. The "AZ Reorder" view currently lives inside the `az_person` module. I'm attempting to move it outside of `az_person` but am running into dependency issues since AZ Person is on by default, but AZ Carousel is not. So whenever AZ Carousel isn't turned on, it's causing a dependency error.

Do we need to completely remove the AZ Reorder view and separate out everything into individual view displays within their respective content type's view?

**Comment by joeparsons** [comment]
Looks like the site install actually wasn't totally successful.  There was a config dependencies error that appears to be related to the reorder view getting moved to az_core:

```
In UnmetDependenciesException.php line 98:
                                                                               
  [Drupal\Core\Config\UnmetDependenciesException]                              
  Configuration objects provided by az_core have unmet dependencies: views.view.az_reorder (field.storage.node.field_az_carousel_short_summary, field.storage.node.field_az_person_category, node.type.az_carousel_item, node.type.az_person, draggableviews)                                                                    
                                                                               

Exception trace:
  at /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
 Drupal\Core\Config\UnmetDependenciesException::create() at /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:511
 Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall() at /src/az-quickstart-scaffolding/web/modules/contrib/config_provider/src/ProxyClass/ConfigProviderConfigInstaller.php:132
 Drupal\config_provider\ProxyClass\ConfigProviderConfigInstaller->checkConfigurationToInstall() at /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:162
 Drupal\Core\Extension\ModuleInstaller->install() at /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
 Drupal\Core\ProxyClass\Extension\ModuleInstaller->install() at /src/az-quickstart-scaffolding/web/core/includes/install.core.inc:1878
 _install_module_batch() at /src/az-quickstart-scaffolding/web/core/includes/batch.inc:295
 _batch_process() at /src/az-quickstart-scaffolding/web/core/includes/form.inc:950
 batch_process() at /src/az-quickstart-scaffolding/web/core/includes/install.core.inc:647
 install_run_task() at /src/az-quickstart-scaffolding/web/core/includes/install.core.inc:565
 install_run_tasks() at /src/az-quickstart-scaffolding/web/core/includes/install.core.inc:118
 install_drupal() at /src/az-quickstart-scaffolding/vendor/drush/drush/includes/drush.inc:213
 drush_call_user_func_array() at /src/az-quickstart-scaffolding/vendor/drush/drush/includes/drush.inc:197
 drush_op() at /src/az-quickstart-scaffolding/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php:149
 Drush\Commands\core\SiteInstallCommands->install() at n/a:n/a
 call_user_func_array() at /src/az-quickstart-scaffolding/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /src/az-quickstart-scaffolding/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /src/az-quickstart-scaffolding/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /src/az-quickstart-scaffolding/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:311
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /src/az-quickstart-scaffolding/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /src/az-quickstart-scaffolding/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /src/az-quickstart-scaffolding/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /src/az-quickstart-scaffolding/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /src/az-quickstart-scaffolding/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /src/az-quickstart-scaffolding/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /src/az-quickstart-scaffolding/vendor/drush/drush/drush.php:72
 require() at /src/az-quickstart-scaffolding/vendor/drush/drush/drush:4
```

**Comment by joeparsons** [comment]
> Do we need to completely remove the AZ Reorder view and separate out everything into individual view displays within their respective content type's view? Or is there a way/is it possible to have the "Person Reorder" view display on and have the "Reorder Carousel Items" one off until the content type is enabled––and once the AZ Carousel module is enabled, the "Reorder Carousel Items" view display is also enabled?

I'm thinking we may need to maintain content type specific views...

**Comment by akslay** [comment]
> I'm thinking we'll need to maintain content type specific re-order views. I like your idea of making them be a display within the respective content type's views. I don't think there is any way we can have specific displays of a shared view only be enabled if their config dependencies are met, unfortunately.

Should we separate everything out in this PR? Or maybe only separate out the view display for the Carousel Items, and then handle the Person content type changes in a separate PR?

**Comment by danahertzberg** [comment]
> Should we separate everything out in this PR? Or maybe only separate out the view display for the Carousel Items, and then handle the Person content type changes in a separate PR?

We should separate out Carousel items in this PR. And have the Person reorder be a PR associated with the separate ticket https://github.com/az-digital/az_quickstart/issues/408 (but follow the same model)

**Review by danahertzberg — APPROVED** [review]

**Review by smayden — APPROVED** [review]
Tested successfully as content editor

**Review by geijutsuka — APPROVED** [review]
Works for me... We may want to consider an automatic destination after save (currently have to click "back to site" after save).

**Review by trackleft — APPROVED** [review]

**Pull request merged**
