### PR TITLE
Closes #3228: Change featured image to thumbnail image in Marketing Cloud layouts

### LINKED ISSUE #3228: Use thumbnail image in Marketing Cloud newsletters
## Motivation
When I pull in content to Marketing Cloud via the Content for Email page, the only image option is the featured image. Using a thumbnail image allows for more flexibility on the News item in Quickstart.

## Proposed Resolution
Change use of featured image to thumbnail image.

## Additional context
Feedback from the Marketing Cloud workshop put on by @camikazegreen on 2/27/2024.

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
This PR changes the Marketing Cloud layouts to use the thumbnail image instead of the featured image.

_Question: If the thumbnail image is not populated, should we fill it in with the placeholder image or the featured image?_
_Answer: Need help with populating with featured image if no thumbnail, and placeholder if no featured image._

### Release notes

```
Marketing Cloud layouts now use the Thumbnail Image field for news images, replacing the previously used Featured Image field, and setting the Featured Image field as the fallback.
```

## Related issues
Closes #3228 

## How to test

1. Install the AZ Marketing Cloud module
2. Change the thumbnail image on a news item
3. View that news item's marketing cloud layout to observe thumbnail use

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by HenryzGreenberg** [comment]
If the thumbnail image is unavailable, using the featured image as a fallback is best. This ensures that the content remains visually consistent.

**Comment by trackleft** [comment]
What do you think of this for the release notes?
```
Marketing Cloud layouts now use the Thumbnail field for news images, replacing the previously used Featured Image field.
```

**Comment by danahertzberg** [comment]
Dana to send to Paul Fini for review

**Review by bberndt-uaz — APPROVED** [review]
Looks good! Potential future improvement: in the "Content for email" admin view, disable links for news layouts with images (Hero, 50/50, etc.) for news nodes that don't have a featured or thumbnail image.

**Review by djcelaya — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Comment by danahertzberg** [comment]
Talked with Paul yesterday and no concerns were brought up

**Pull request merged**
