### PR TITLE
Closes #1544: Add workaround and patch for Paragraphs 1.14 migrate plugin issues.

### LINKED ISSUE #1544: Paragraphs 1.14 issues
## Problem/Motivation
The [dependabot PR](1504)  for upgrading Paragraphs from 8.x-1.12 to 8.x-1.14 fails our Migration tests.

### Describe the bug

```
[error]  Migration az_node_news did not meet the requirements. Missing migrations az_paragraph_column_image. requirements: az_paragraph_column_image. 

In MigrateToolsCommands.php line 983:
                                  
  az_node_news migration failed.  
```

These failures sound similar to those reported in a [Paragraphs module issue on Drupal.org](https://www.drupal.org/project/paragraphs/issues/3268555)

## Proposed resolution
Identify problem, create patch to fix issue and add patch to Quickstart so we can upgrade Paragraphs. Contribute patch to d.o. if possible.

### Expected behavior

Our migration tests shouldn't fail.

## Additional context
There is also a [Drupal core issue](https://www.drupal.org/project/drupal/issues/2797505) describing similar problems.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Testing patch for Paragraphs 1.14 migrate plugin issues.

## Related issues
Closes #1544

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [x] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Do you think that making these optional would fix this? https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/migrations/migrate_plus.migration.az_node_news.yml#L268-L278

**Comment by joeparsons** [comment]
I was able to create a [Paragraphs module patch](https://www.drupal.org/project/paragraphs/issues/3268555#comment-14542829) based on a [workaround described in the Drupal core issue](https://www.drupal.org/comment/14014495#comment-14014495) that seems to work to solve this issue although it requires adding an extra process step to the affected migration yml files.  If this approach seems OK with everyone, we may want to add this process step to all of our paragraphs migrations until the core issue is resolved.

**Comment by trackleft** [comment]
Tested like this
```
mkdir -p azs-honors

lando init --service pantheon
<selected site>

composer require "az-digital/az_quickstart:dev-issue/1544 as 2.3.0" -W

git remote add upstream https://github.com/az-digital/az-quickstart-pantheon.git

git checkout upstream/issue/83 .lando.upstream.yml scripts/lando/migrate-db-import.sh scripts/lando/migrate-setup-from-pantheon.sh

lando start

lando pull -d live -f live -c none

lando composer update

lando migrate-setup-from-pantheon -s  <sourcesitename.env>

lando migrate-db-import database.sql.gz

 lando drush updb -y

lando drush mim --group=az_migration

 ----------------------------------------- ----------------------------------------- -------- ------- ---------- ------------- --------------------- 
  Group                                     Migration ID                              Status   Total   Imported   Unprocessed   Last Imported        
 ----------------------------------------- ----------------------------------------- -------- ------- ---------- ------------- --------------------- 
  AZ Quickstart Migrations (az_migration)   az_user                                   Idle     53      38         0             2022-06-02 02:38:20  
  AZ Quickstart Migrations (az_migration)   az_files                                  Idle     1374    1374       0             2022-06-02 02:38:20  
  AZ Quickstart Migrations (az_migration)   az_media                                  Idle     1405    1373       0             2022-06-02 02:42:00  
  AZ Quickstart Migrations (az_migration)   az_node_carousel                          Idle     0       0          0             2022-06-02 02:42:02  
  AZ Quickstart Migrations (az_migration)   az_paragraph_contact                      Idle     48      48         0             2022-06-02 02:42:08  
  AZ Quickstart Migrations (az_migration)   az_event_categories                       Idle     2       2          0             2022-06-02 02:42:10  
  AZ Quickstart Migrations (az_migration)   az_node_event                             Idle     98      98         0             2022-06-02 02:42:25  
  AZ Quickstart Migrations (az_migration)   az_paragraph_callout                      Idle     0       0          0             2022-06-02 02:42:26  
  AZ Quickstart Migrations (az_migration)   az_paragraph_carousel                     Idle     1       1          0             2022-06-02 02:42:28  
  AZ Quickstart Migrations (az_migration)   az_flexible_page_categories               Idle     0       0          0             2022-06-02 02:42:29  
  AZ Quickstart Migrations (az_migration)   az_news_tags                              Idle     8       8          0             2022-06-02 02:42:31  
  AZ Quickstart Migrations (az_migration)   az_person_categories                      Idle     7       15         -8            2022-06-02 02:42:34  
  AZ Quickstart Migrations (az_migration)   az_person_categories_secondary            Idle     0       0          0             2022-06-02 02:42:35  
  AZ Quickstart Migrations (az_migration)   az_paragraph_chucks_view                  Idle     23      20         0             2022-06-02 02:42:39  
  AZ Quickstart Migrations (az_migration)   az_paragraph_column_image                 Idle     37      37         0             2022-06-02 02:42:46  
  AZ Quickstart Migrations (az_migration)   az_paragraph_extra_info                   Idle     0       0          0             2022-06-02 02:42:47  
  AZ Quickstart Migrations (az_migration)   az_paragraph_file_download                Idle     2       2          0             2022-06-02 02:42:49  
  AZ Quickstart Migrations (az_migration)   az_paragraph_full_width_bg_wrapper        Idle     9       8          0             2022-06-02 02:42:51  
  AZ Quickstart Migrations (az_migration)   az_paragraph_full_width_media_row         Idle     3       1          0             2022-06-02 02:42:54  
  AZ Quickstart Migrations (az_migration)   az_paragraph_gallery                      Idle     0       0          0             2022-06-02 02:42:55  
  AZ Quickstart Migrations (az_migration)   az_paragraph_headed_text                  Idle     383     367        0             2022-06-02 02:43:46  
  AZ Quickstart Migrations (az_migration)   az_paragraph_html                         Idle     4       4          0             2022-06-02 02:43:49  
  AZ Quickstart Migrations (az_migration)   az_paragraph_jumbotron                    Idle     0       0          0             2022-06-02 02:43:51  
  AZ Quickstart Migrations (az_migration)   az_paragraph_panel_group                  Idle     46      45         0             2022-06-02 02:43:59  
  AZ Quickstart Migrations (az_migration)   az_paragraph_plain_text                   Idle     0       0          0             2022-06-02 02:44:01  
  AZ Quickstart Migrations (az_migration)   az_paragraph_single_card                  Idle     1       1          0             2022-06-02 02:44:03  
  AZ Quickstart Migrations (az_migration)   az_paragraph_well                         Idle     3       3          0             2022-06-02 02:44:05  
  AZ Quickstart Migrations (az_migration)   az_paragraph_card_deck                    Idle     32      31         0             2022-06-02 02:44:11  
  AZ Quickstart Migrations (az_migration)   az_paragraph_flexible_page_sub            Idle     248     2          0             2022-06-02 02:44:25  
  AZ Quickstart Migrations (az_migration)   az_paragraph_content_marquee              Idle     0       0          0             2022-06-02 02:44:27  
  AZ Quickstart Migrations (az_migration)   az_node_flexible_page                     Idle     248     248        0             2022-06-02 02:45:27  
  AZ Quickstart Migrations (az_migration)   az_node_news                              Idle     229     229        0             2022-06-02 02:46:00  
  AZ Quickstart Migrations (az_migration)   az_node_person                            Idle     182     182        0             2022-06-02 02:46:33  
  AZ Quickstart Migrations (az_migration)   az_paragraph_uaqs_basic_page_to_az_page   Idle     0       0          0             2022-06-02 02:46:35  
  AZ Quickstart Migrations (az_migration)   az_node_uaqs_basic_page_to_az_page        Idle     0       0          0             2022-06-02 02:46:37  
  AZ Quickstart Migrations (az_migration)   az_exclude_node_title                     Idle     1       1          0             2022-06-02 02:46:40  
  AZ Quickstart Migrations (az_migration)   az_redirects                              Idle     332     188        0             2022-06-02 02:47:07  
  AZ Quickstart Migrations (az_migration)   az_site_frontpage                         Idle     1       1          0             2022-06-02 02:47:10  
  AZ Quickstart Migrations (az_migration)   az_cas_user                               Idle     52      37         0             2022-06-02 02:47:18  
  AZ Quickstart Migrations (az_migration)   az_menu_links                             Idle     99      99         0             2022-06-02 02:47:45  
 ----------------------------------------- ----------------------------------------- -------- ------- ---------- ------------- --------------------- 

```

Site link https://dev-azs-honors.pantheonsite.io/

**Comment by joeparsons** [comment]
Those results look good to me @trackleft.  Looks like many paragraphs were skipped which probably means that the source site has "orphan" paragraphs in the DB.

**Comment by trackleft** [comment]
> Those results look good to me @trackleft. Looks like many paragraphs were skipped which probably means that the source site has "orphan" paragraphs in the DB.

Yep 
``` 
----------------------------------------- -------------------------- -------- ------- ---------- ------------- --------------------- 
  Group                                     Migration ID               Status   Total   Imported   Unprocessed   Last Imported        
 ----------------------------------------- -------------------------- -------- ------- ---------- ------------- --------------------- 
  AZ Quickstart Migrations (az_migration)   az_paragraph_chucks_view   Idle     23      20         0             2022-06-02 02:42:39  
 ----------------------------------------- -------------------------- -------- ------- ---------- ------------- --------------------- 
➜  azs-honors git:(master) ✗ lando drush mmsg az_paragraph_chucks_view
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  Source ID(s)   Destination ID(s)   Level   Message                                                                          
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  5              :                   4       az_paragraph_chucks_view:keep_row: Could not determine parent entity. Skipping.  
  257            :                   4       az_paragraph_chucks_view:keep_row: Could not determine parent entity. Skipping.  
  333            :                   4       az_paragraph_chucks_view:keep_row: Could not determine parent entity. Skipping.  
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
 ➜  azs-honors git:(master) ✗ lando drush mmsg az_paragraph_full_width_bg_wrapper
 -------------- ------------------- ------- ------------------------------------------------------------------------------------------- 
  Source ID(s)   Destination ID(s)   Level   Message                                                                                    
 -------------- ------------------- ------- ------------------------------------------------------------------------------------------- 
  256            :                   4       az_paragraph_full_width_bg_wrapper:keep_row: Could not determine parent entity. Skipping.  
 -------------- ------------------- ------- ------------------------------------------------------------------------------------------- %
 ➜  azs-honors git:(master) ✗ lando drush mmsg az_paragraph_headed_text
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  Source ID(s)   Destination ID(s)   Level   Message                                                                          
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  54             :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  253            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  259            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  260            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  359            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  362            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  585            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  590            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  636            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  684            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  772            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  773            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  804            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  811            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  812            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
  813            :                   4       az_paragraph_headed_text:keep_row: Could not determine parent entity. Skipping.  
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
➜  azs-honors git:(master) ✗ lando drush mmsg az_paragraph_panel_group
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  Source ID(s)   Destination ID(s)   Level   Message                                                                          
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
  715            :                   4       az_paragraph_panel_group:keep_row: Could not determine parent entity. Skipping.  
 -------------- ------------------- ------- --------------------------------------------------------------------------------- 
➜  azs-honors git:(master) ✗ lando drush mmsg az_paragraph_card_deck
 -------------- ------------------- ------- ------------------------------------------------------------------------------- 
  Source ID(s)   Destination ID(s)   Level   Message                                                                        
 -------------- ------------------- ------- ------------------------------------------------------------------------------- 
  25             :                   4       az_paragraph_card_deck:keep_row: Could not determine parent entity. Skipping.  
 -------------- ------------------- ------- ------------------------------------------------------------------------------- 

```

**Review by trackleft — APPROVED** [review]

**Review by cpoff — APPROVED** [review]

**Pull request merged**
