### PR TITLE
Closes #3850: Update Quickstart content type views to have sticky at top of lists respected

### LINKED ISSUE #3850: Add sticky to top of lists in sort criteria
## Motivation
The Sticky at top of lists checkbox appears on the News item, but when checked, users are frustrated that it doesn't do anything.

### Is your feature request related to a problem? Please describe.
Views should respect the sticky at top of lists sort criteria

### Describe the solution you'd like
Check all content type views for sticky at top of lists sort criteria.
- AZ News
- AZ Page
- AZ Events (?)
- AZ Person (?)

### Describe alternatives you've considered
Remove the sticky at top of lists checkbox from content types.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
This adds a stick at top of lists sort criteria to all views.

### Release notes

If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)

Make sure to add the `release notes` label to this PR.

```
Views of AZ Person, AZ News, AZ Event, and AZ Page are updated to respect the "Sticky at top of lists" setting found on an individual piece of content. Content with this setting will now appear at the top of views.
```

## Related issues
Closes #3850

## How to test

1. Modify content to check the "Sticky at top of lists" box
2. Add a page with a view of that same content type
3. Observe selected content at the top of the list

Changed view displays include:
- AZ Events 
   - Grid view
   - Grid view with images
- AZ News
   - Feature view
   - Paged row view
   - Small row view
   - Grid view
   - Grid view with filter
   - Teaser grid page
   - Recent news marquee
   - Row attachment
- AZ Pages
   - Row page
   - Grid page
- AZ Person
   - Grid page
   - Grid - modal
   - Row page
   - Grid - 3 col
   - Grid - Modal 3 col

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Review by bberndt-uaz — COMMENTED** [review]
In Probo, I'm only seeing the "Sticky at top of lists" sort criterion on the AZ News Feature view display (and it does seem to be working there). I wonder if you need to add that criterion to the view displays individually.

**Comment by danahertzberg** [comment]
> AZ News Feature view display (and it does seem to be working there). I wonder if you need to add that criterion to the view displays individually.

So weird, on my local I updated the default display and ensured the other displays were using the default when appropriate and it seemed fine there. I'll look into it more. :(

**Comment by danahertzberg** [comment]
I bet it's something with demo content. I'll look again to see if there are overridden views for demo content.

**Comment by danahertzberg** [comment]
To do:
- Export AZ Event changes from probo
- Change AZ Person to update overridden views instead of reverting to default
   - Add back contextual filter

**Comment by bberndt-uaz** [comment]
I noticed that the Small Row View view display from the AZ News view has the Block Name `Sidebar News Block`. It looks like that was changed to `Small Row News Block` in the AZ News view from the az_finder module, but not the original view from the az_news module.

If you want to make that change in this PR (instead of opening another issue for it), here is the relevant line from the issue/3850 branch: https://github.com/az-digital/az_quickstart/blob/issue/3850/modules/custom/az_news/config/install/views.view.az_news.yml#L906.

**Comment by danahertzberg** [comment]
> I noticed that the Small Row View view display from the AZ News view has the Block Name `Sidebar News Block`. It looks like that was changed to `Small Row News Block` in the AZ News view from the az_finder module, but not the original view from the az_news module. If you want to make that change in this PR (instead of opening another issue for it), here is the relevant line from the issue/3850 branch: https://github.com/az-digital/az_quickstart/blob/issue/3850/modules/custom/az_news/config/install/views.view.az_news.yml#L906.
> 
> Also, I wanted to double-check if the AZ News Sidebar Row View should have the "Sticky at top of lists" sorting? I can't recall what we decided on last week. Otherwise, I'm ready to approve this PR once the request above is resolved!

Thanks @bberndt-uaz! I updated the block name -- good catch! And I think the sidebar stickiness we wanted to cover in the meeting to get group consensus.

**Review by bberndt-uaz — APPROVED** [review]

**Comment by danahertzberg** [comment]
- [ ] Need to test on news.arizona.edu after CWS fixes GH action
- [ ] Sidebar row view -- Should this respect sticky articles? **No**

**Review by bberndt-uaz — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by ewlyman — APPROVED** [review]
Joe and Brian have already approved this PR for merge. These comments are only in reference to the effect of these changes on https://news.arizona.edu (UA News).

In addition to providing 'sticky at top of lists' ordering for standard Quickstart views, these changes affect several custom views for News and Event content types that are only used on the UA News site:

- Employee News pages row view
- Super Feature Secondary
- Stories we like
- Awards and Accolades
- Upcoming Events for Home Page
- Ongoing Exhibits & Tours Attachment (Event content type)
- Ongoing Exhibits & Tours Page (Event content type)

Other custom views have 'sticky at top of lists' ordering added, but additional filters on these views prevent this ordering from taking effect.

UA News is only one site out of many Quickstart sites, and most articles are sorted and displayed on UA News using content flags, instead of the 'sticky' promotion checkbox. So display changes will probably happen infrequently, if at all.
Questions about display changes can be handled at the content editor level through documentation/instruction, or programmatically by overriding sticky sorting on individual custom views

**Review by tadean — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
