### PR TITLE
Closes #1491: Removing asset-packagist dependencies for now.

### LINKED ISSUE #1491: asset-packagist is down
## Problem/Motivation
asset-packagist.org is currently down and all Quickstart composer builds are failing.

Seems to be a known issue and one that may not be resolved right away:
https://github.com/hiqdev/asset-packagist/issues/146

### Describe the bug
Anyone trying to build Quickstart with composer right now is running into errors like this one:

```
Error: curl error 28 while downloading https://asset-packagist.org/packages.json: Connection timed out after 10004 milliseconds
```

### To Reproduce
`composer install`

## Proposed resolution
Since it looks like connectitvity to asset-packagist may not be restored right away, we should probably look into mirroring the NPM / Bower packages we need on our own GitHub org temporarily or something.

### Expected behavior

`composer install` should work.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Temporary workaround for asset-packagist connectivity issues.

## Related issues
#1491

## How to test
`composer install`

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [x] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mmunro-ltrr — APPROVED** [review]
Not independently checking that the deletions from `require` have any effects.

**Comment by jwmoore1** [comment]
Does this need to be removed from the scaffolding repo in order to build?

**Comment by joeparsons** [comment]
> Does this need to be removed from the scaffolding repo in order to build?

Yep, definitely does.  Thanks.  Made a PR with a matching branch name: az-digital/az-quickstart-scaffolding#60.

**Comment by mmunro-ltrr** [comment]
Verified a local lando install still works after the changes to both repos.

**Review by jwmoore1 — APPROVED** [review]

**Comment by jwmoore1** [comment]
Now that [asset-packagist](https://asset-packagist.org/) is back up, do we close this PR and revert the [PR](https://github.com/az-digital/az-quickstart-scaffolding/pull/60) in the scaffolding repo, or do we proceed with a long term solution so we don't run into this issue again?

**Comment by mmunro-ltrr** [comment]
@jwmoore1 I'd be for proceeding with a long term solution.

**Review by trackleft — APPROVED** [review]

**Comment by trackleft** [comment]
Should we close this?

**Pull request closed without merging**
