### PR TITLE
CKeditor changes for Standard Text Format

### LINKED ISSUE #306: Create Standard Text Format
**Name:** Standard Text
**Description:** Add standard text, headings, links, buttons, etc.

**Requirements:**
- Undo/Redo
- Styles (same as QS 1.0)
- Bold/Italic/Strikethrough
- Link/unlink
- Align left/center/right
- Insert unordered/ordered list
- Block quote
- Insert grid
- Insert table
- Embed media/blocks/content
- Super/sub script
- Insert special characters
- Remove formatting
- Paste plain text
- View source

### PR DESCRIPTION
**Pull request by jwmoore1**
Create feature parity with QS 1.0, except for Bootstrap Grid.

## Description
Add missing functionality from QS 1.0 to the Standard Text Format, except the Bootstrap Grid button.
Closes #306 

## How Has This Been Tested?
This has only been tested locally, so it needs more review because I could have easily missed something.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] I've added this Pull Request to the AZ Quickstart project in the right column.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by camikazegreen** [comment]
image
We should get rid of one of the E's for Content or Node. They both allow you to embed the same content, but have different display options.

**Comment by geijutsuka** [comment]
Should the text align options be added? I know they're not in the original text format, but should be.

**Comment by danahertzberg** [comment]
Looks like some reordering/re-grouping will need to be done, but we can do that after Bootstrap Grid is added. 

We should also use just the media button (remove the image button) and the Content button (remove the node button)

**Comment by danahertzberg** [comment]
> Should the text align options be added? I know they're not in the original text format, but should be.

Text align options are in the QS 1.0 version and should be added here.

**Comment by smayden** [comment]
This looks great! 

A few notes based on the requirements

- Align options missing as Rebecca & Dana mentioned
- Strikethrough was listed in requirements (although I'd argue we don't need it)
- Remove image button? (since we have the File button here)
- Quotation button does not seem to do anything when I use it on the final page
- Should zero be the default for bottom spacing? Perhaps match to what we do now.

A few questions:
- List under styles doesn't not match what is on Quickstart 1, will those be changed later?
- Do we want to include Standard, Basic, Restricted and Full HTML (I don't see those in requirements)
- There are more paste options than we currently have in QS 1. Do we want to keep Paste, Paste as plain text, and Paste from Word
- Styles are not applied while editing text (only when paragraph is collapsed). Is this expected
- Might make sense to move additional options below the Text area
- I got a little confused by the title of the paragraph thinking it was part of the actual text (see screenshot, probably not specific to this ticket)

image

**Comment by danahertzberg** [comment]
There are definitely some major improvements! Like heading tags stay put when applying styles, hooray!

However, I'm not seeing the bootstrap grid button. And styles are not displaying in the editing interface. I think this should be a requirement since we have that feature now and it's quite difficult to modify text without seeing the modifications.

Here is a demo page with some detailed notes: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-358.probo.build/dana

**Comment by danahertzberg** [comment]
I see that callout styles are added to the dropdown. I recommend removing them from this PR since they aren't available in the QS1 version. They are card-like which may benefit from a future short discussion about where to include those style options if we want them in QS2 post MVP.

**Comment by joeparsons** [comment]
Noticed the Bootstrap Grid button was missing after a fresh ProboCI rebuilt.  I found I was able to add the plugin via the text editors admin UI.  I then exported the editor config for az_standard and compared that to what was already in your branch.  This was the only difference:
```
diff --git a/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml b/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
index c432fb8..dbf74bb 100644
--- a/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
+++ b/modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
@@ -47,6 +47,7 @@ settings:
             - Table
             - HorizontalRule
             - Blockquote
+            - bs_grid
         -
           name: 'Text styles'
           items:
```

**Comment by danahertzberg** [comment]
@jwmoore1 Would you also mind putting the BS grid button first in that section, please?
Screen Shot 2020-11-13 at 10 19 12 AM

**Comment by danahertzberg** [comment]
@jwmoore1 I'm not seeing a probo build (typical). Is this ready for review and should I trigger a build?

**Comment by jwmoore1** [comment]
@danahertzberg Yes and yes, you'll probably have to trigger a rebuild because of the issues we've been having with Probo.

**Comment by danahertzberg** [comment]
I found a few items. 

Bootstrap Grid
1. The insert overlay is still hard to use
2. The grid is inserted in mobile view (stacked) to edit. Seems like the grid won't act as I selected.

Styles
1. Styles aren't applied in the editing interface or in the dropdown list
2. There are still extra and missing styles (below is a complete list)

```
Button Red
Button Blue
Button Outline Red
Button Outline Blue
Button Outline White
Button Link

Text Small
Text White
Text Sky
Text Oasis
Text Azurite
Text Blue
Text Midnight
Text Dark Silver
Text Ash Text

Sanserif Heading
Capitalized Text
UPPERCASED TEXT
lowercased text

Triangle Bullets
Unordered List Pills

Label Red
Label Blue
Label Green
Label Sky
Label Warning
Label Danger

Text size Lead
Text size H1
Text size H2
Text size H3
Text size H4
Text size H5
Text size H6

Text align top
Text align middle
Text align bottom
Text align with zero margin-top
Text align with zero margin-bottom

**Comment by danahertzberg** [comment]
Hey @jwmoore1. Thanks for the continuous updates on this!

Can Heading 1 be added to the format dropdown? And can they be titled to match AZBS at all? (https://digital.arizona.edu/arizona-bootstrap/docs/2.0/content/typography/#headings)

Just a few more updates.. Using more spans will allow for more compatibility with headings.

- Please change `p.small|Text Small` to `span.small|Text Small`
- Please change `p.lead|Text size Lead` to `span.lead|Text size Lead`
- Remove all of these options (since they are confusing and too similar to the Text size H# styles)
     - `p.h1|H1 Heading`
     - `p.h2|H2 Heading`
     - `p.h3|H3 Heading`
     - `p.h4|H4 Heading`
     - `p.h5|H5 Heading`
     - `p.h6|H6 Heading`
- Please change `p.margin-zero-top|Text align with zero margin-top` to `span.mt-0|Zero Margin Top`
- Please change `p.margin-zero-bottom|Text align with zero margin-bottom` to `span.mb-0|Zero Margin Bottom`

Thank you! 🙏

**Comment by danahertzberg** [comment]
@jwmoore1 You should be able to copy paste the following. The only thing I'm having trouble figuring out is the `ul.nav.nav-pills|Unordered List Pills` style because it needs styles applied to the `<li>` and `<a>` within it.

**Styles dropdown**
```
a.btn.btn-red|Button Red
a.btn.btn-blue|Button Blue
a.btn.btn-outline-red|Button Outline Red
a.btn.btn-outline-blue|Button Outline Blue
a.btn.btn-outline-white|Button Outline White
a.btn.btn-link|Button Link
span.text-white|Text White
span.text-sky|Text Sky
span.text-oasis|Text Oasis
span.text-azurite|Text Azurite
span.text-blue|Text Blue
span.text-midnight|Text Midnight
span.text-dark-silver|Text Dark Silver
span.text-ash|Text Ash
span.text-sans|Sanserif Text
span.text-capitalize|Capitalized Text
span.text-uppercase|UPPERCASE TEXT
span.text-lowercase|lowercase text
ul.ul-triangles|Triangle Bullets
ul.nav.nav-pills|Unordered List Pills
span.badge.badge-red|Label Red
span.badge.badge-blue|Label Blue
span.badge.badge-success|Label Green
span.badge.badge-info|Label Sky
span.badge.badge-warning|Label Warning
span.badge.badge-danger|Label Danger
span.small|Text Size Small
span.lead|Text Size Lead
span.h1|Text Size H1
span.h2|Text Size H2
span.h3|Text Size H3
span.h4|Text Size H4
span.h5|Text Size H5
span.h6|Text Size H6
span.align-top|Text Align Top
span.align-middle|Text Align Middle
span.align-bottom|Text Align Bottom
span.mt-0|Zero Margin Top
span.mb-0|Zero Margin Bottom
```

**Allowed HTML tags**
```
<em> <strong> <s> <abbr> <address> <blockquote> <br> <div class="col col-* row"> <ul type class="nav nav-* ul-*"> <ol start type> <li> <dl> <dt> <dd> <h1> <h2> <h3> <h4> <h5> <h6> <sup> <sub> <table> <caption> <tbody> <thead> <tfoot> <th> <td> <tr> <hr> <a href class="btn btn-red btn-outline-red btn-blue btn-outline-blue btn-outline-white btn-link"> <span class="text-* badge badge-* small lead h1 h2 h3 h4 h5 h6 align-* m* p*"> <img src alt data-entity-type data-entity-uuid> <drupal-entity data-entity-type data-entity-uuid data-entity-embed-display data-entity-embed-display-settings data-align data-caption data-embed-button alt title> <drupal-media data-entity-type data-entity-uuid alt title> <div class=* data-* >
```

**Comment by danahertzberg** [comment]
Looking good! One remaining item is to add thhe CKEditor permissions for the Content Administrator role.

I will add a follow up ticket for investigating differences in the format dropdown options.

**Review by danahertzberg — DISMISSED** [review]
Woo hoo! I think this is ready to merge. I will create a follow up ticket to investigate an issue I found with Blockquote (related to differences between BS3 and BS4)

**Review by tadean — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]
Re-approved!

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
