### PR TITLE
Fixes #515 Version indicator changes

### LINKED ISSUE #515: Quickstart version indicator enhancements
## Motivation
In #368 we added a basic Quickstart version indicator to the admin toolbar.  The implementation that was adopted was a very basic, MVP implementation and there are several follow-up improvements that are needed.

## Proposed Resolution

Follow-up items identified in #368 

- Add more specific class and stylesheet to float right
- Link to Quickstart documentation for content editors / Link to Quickstart settings page for content admins ? (Note: a link to quickstart.arizona.edu has been added as of 7/7/21 and there was discussion that it made the most sense for content admins for the link to go to the same place).
- Add more specific version indicator to Quickstart settings page?

### PR DESCRIPTION
**Pull request by tadean**
This PR updates the version indicator on the Quickstart toolbar.

## Related issues
#515

## How to test

- Test locally
- Add version number to `az_quickstart.info.yml`
- Clear cache
- Verify version indicator appears

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [x] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [x] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
Some followups from the original issue:

- **Link to Quickstart documentation for content editors**
Is this still desired now that the **Quickstart 2** link already points to the same location?

- **Add more specific version indicator to Quickstart settings page?**
To do this, we'll need to start tagging actual version numbers. Should we add this functionality in a pipeline? See discussion from @trackleft in issue #515

**Review by trackleft — APPROVED** [review]
I like it! 
image

**Comment by camikazegreen** [comment]
Should the sub-menu items also float right so that there isn't so far to go to reach back across the screen once the menu is expanded?

**Comment by camikazegreen** [comment]
This will also require an update to https://quickstart.arizona.edu/site-admin/analytics with updated screenshots.

**Comment by danahertzberg** [comment]
Could we also reorder the menu items to: Settings | Documentation | Analytics Dashboard

Settings is within this site, where the others are external.

**Review by joeparsons — DISMISSED** [review]
Looks good to me.  Thanks!

**Review by joeparsons — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]
Latest changes look good to me.

**Review by bberndt-uaz — APPROVED** [review]
Tested locally and verified that the version appears in the menu bar:
image

**Comment by joeparsons** [comment]
Verified that we do already have a separate issue for maintaining version info in the .info.yml file: #692

**Review by trackleft — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Pull request merged**
