### PR TITLE
Closes #3113 Standard text format cannot be edited in the UI without removing allowed tags

### LINKED ISSUE #3113: Standard text format cannot be edited in the UI without removing allowed tags
## Problem/Motivation
As an Administrator, attempting to make changes to the configuration of the Standard text format at /admin/config/content/formats/manage/az_standard results in the changes not being applied and an error message being displayed:

> The following attribute(s) are already supported by enabled plugins and should not be added to the Source Editing "Manually editable HTML tags" field: Bootstrap Grid (\<div class\>).

The only way to prevent the error from occurring is to continually remove the specified tags from the "Manually editable HTML tags" field until the error no longer appears. Removing tags in this way will change the HTML output of the site's text areas, causing breaking visual changes.

### Describe the bug
This bug is the result of CKEditor validation added in Drupal 10.2, as described in this Drupal core issue:

- [[10.2 regression] CKEditor 5 breaks when “Source”/Source editing button is added and “Manually editable HTML tags” are specified](https://www.drupal.org/project/drupal/issues/3410100)

This issue was originally identified in Quickstart issue #3102 ([Some CKEditor editable tags are removed and can't be restored](https://github.com/az-digital/az_quickstart/issues/3102)). That issue was resolved by restoring the necessary tags to the allowed_tags setting for the Standard text format. However, the Standard text format can no longer be edited in the UI: it can only be changed by editing the config at modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml.

### To Reproduce

1. As an Administrator, go to /admin/config/content/formats/manage/az_standard
2. Try to make one change to the configuration
3. Click the Save configuration button at the bottom of the page
4. Note the error at the top of the page and observe that the change has not been applied

## Proposed resolution
Find a way of handling the error to allow the form to be saved and the Standard text format configuration to be updated.

### Expected behavior

Administrators should be able to make changes to the Standard text format using the Drupal UI.

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description

Adds a [patch for Drupal core issue 3410100](https://www.drupal.org/project/drupal/issues/3410100#comment-15409300) to revert some updates to CKEditor validation for the source editing "Manually editable HTML tags" field, which is currently preventing the edit form for the Standard text format from being able to be saved.

The patch should be removed once the Drupal core issue is resolved.

## Related issues

Closes #3113

## How to test

Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3114.probo.build

1. Log in as an Administrator user
2. Go to Configuration > Text formats and editors > click the Configure button for the Standard text format ([/admin/config/content/formats/manage/az_standard](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3114.probo.build/admin/config/content/formats/manage/az_standard)).
3. Make one small change and click the Save configuration button at the bottom.
4. Confirm that a "The text format Standard has been updated" message is displayed, indicating that the configuration was saved successfully.
5. Go back to the configuration page to confirm that the change you made was saved.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by joeparsons — DISMISSED** [review]
This looks great to me. I verified that I was able to save the editor config on ProboCI and that the warning message renders as expected.

Nice work!

**Comment by joeparsons** [comment]
Someone submitted a patch on d.o. that provides another potential workaround we could consider using: https://www.drupal.org/project/drupal/issues/3410100#comment-15409300

It reverts the recent changes made to the `SourceEditingRedundantTagsValidator` without disabling it completely.

**Review by joeparsons — APPROVED** [review]
Confirmed I am still able to save the editor config settings on ProboCI with the patch.

**Comment by tadean** [comment]
```
- Applying patches for drupal/core
   ...
    https://www.drupal.org/files/issues/2024-01-23/drupal-revert-source-editing-validation-tightening-3410100-38.patch ([10.2 regression] CKEditor 5 breaks when 'Source'/Source editing button is added and 'Manually editable HTML tags' are specified (3410100))
```
Verified locally that the text format settings can be saved without validation errors with the patch applied.

**Review by tadean — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
