### PR TITLE
Closes #1822 - Move page title block to content_top region

### LINKED ISSUE #1822: Place page title on top of sidebar first region
## Motivation

When navigating on mobile, I want to see the page title above any content.

## Solution

Place page title block above sidebar first region when stacked.

### PR DESCRIPTION
**Pull request by akslay**
## Description
Moves the page title block to the `content_top` region to improve page title clarity and prevent the title from displaying below the `sidebar_first` region on mobile.

Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1834.probo.build/

## Related issues
Closes #1822 

Related to: https://github.com/az-digital/az_quickstart/pull/1835

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by joeparsons — APPROVED** [review]

**Comment by danahertzberg** [comment]
This will update existing sites. Please wait to merge until we run it by leadership.

**Comment by trackleft** [comment]
Patch existing sites like this:
```
"extra": {
    "patches": {
       "az-digital/az_quickstart": {
          "test https://github.com/az-digital/az_quickstart/pull/1834" : "https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/1834.diff"
      }
    }
  }
}
```

**Review by camikazegreen — APPROVED** [review]

**Comment by trackleft** [comment]
Have we testing that this works for existing sites?

**Comment by trackleft** [comment]
image

**Review by trackleft — APPROVED** [review]

**Review by bberndt-uaz — APPROVED** [review]

**Comment by trackleft** [comment]
Quickstart site with update looks like this 
image

**Comment by trackleft** [comment]
BEFORE SCREENSHOT
image

**Comment by trackleft** [comment]
If it isn't totally obvious to everyone, the title block bottom margin combined with the sidebar top margin do bring the sidebar out of alignment with the body content on that particular site.

**Comment by akslay** [comment]
> In case it isn't totally obvious to everyone, the title block bottom margin combined with the sidebar top margin do bring the sidebar out of alignment with the body content on that particular site.

I think that'll be a non-issue once I update https://github.com/az-digital/az_quickstart/pull/1835 and we get it merged.

**Comment by trackleft** [comment]
Cool, just didn't want it to get overlooked.

**Comment by trackleft** [comment]
I'm going to put a blocked by https://github.com/az-digital/az_quickstart/pull/1835 marker on it.

**Review by danahertzberg — APPROVED** [review]

**Comment by danahertzberg** [comment]
Could consider adding a new region for page title that uses the display flex classes. Float right when sidebar is next to it, but fill the whole column when using full width elements at the top of a page (below the title).

**Comment by HenryzGreenberg** [comment]
Thank you Ashley for your time today. I do see value in moving the page title block to the content_top region until we have a solution for mobile navigation that address the multiple levels of navigation question.

**Comment by joeparsons** [comment]
Decided in 2023-08-04 Friday meeting to close this for now.  We can definitely re-open/re-create this if needed later.

**Pull request closed without merging**
