### PR TITLE
Closes #989 edit media from the parent referencing form.

### LINKED ISSUE #989: Add ability to edit media from the parent/referencing entity form.
## Motivation
As a content editor, I would like to edit media on the page or paragraph that uses it.
As it stands, I can only edit media by tracking it down somewhere in the `/admin/content/media` interface.

## Proposed Resolution
Add the https://www.drupal.org/project/media_library_edit module

### PR DESCRIPTION
**Pull request by trackleft**
Adding drupal.org/project/media_library_edit module
Testing can be done here:
https://app.probo.ci/#/dashboard/build/65e02ce3-e071-4d7f-a80b-a6d9680976de/task/5ee0fee94d400004
Media items now look like this: 
image

## Related Issue
Closes #989
Blocks #693 
Blocks #990

## How Has This Been Tested?
Locally ran `lando install`

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by smayden — COMMENTED** [review]
Tested successfully as admin and content admin, but don't get the edit option when testing a content editor. Permission issue? I'm assuming content editors need access too.

**Comment by trackleft** [comment]
Thanks for testing @smayden, It is probably a permission issue, would the solution be to add the appropriate permissions to just the content editor role?

There are two options that might be the culprit, but my suspicion is that it is `Edit any media`.  
image

Could also be the `Update any media` permission, but only the administrator has that permission currently.

**Comment by smayden** [comment]
Agree that it is probably that "edit any media" permission. Might make sense to address as a separate issue? I would think we'd want content editors to be able to edit any media for all media types.

**Comment by trackleft** [comment]
FYI there is this patch that we might consider for editing media on node create https://www.drupal.org/project/media_library_edit/issues/3189250

**Comment by trackleft** [comment]
Additionally, this patch says the module only checks permissions on the first image, which isn't a problem until we try to edit photo galleries and someone else uploaded the first image. https://www.drupal.org/project/media_library_edit/issues/3201011

**Review by smayden — APPROVED** [review]

**Comment by trackleft** [comment]
FYI, I did some looking into the `hide_date: true` setting that appeared by accident within this pull request when I pulled configuration out of my local site, and found that we have a discrepancy between the config for form display for event  in the quickstart folder for az_seo, and the config in az_event.

In az_seo the setting is:  `hide_date: true`
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml#L102

In az_event the setting is `hide_date: false`
https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml#L92

image


I believe we haven't noticed this before because az_seo is enabled by default on most of our sites and test sites, but the correct setting is what appears in az_seo. `hide_date: true`

**Comment by trackleft** [comment]
This is ready for review.

**Review by joeparsons — APPROVED** [review]

**Review by smayden — APPROVED** [review]

**Pull request merged**
