### PR TITLE
Fixes #46: Adds Layout Builder Styles ordering patch.

### LINKED ISSUE #46: Layout Builder Styles Ordering
## Motivation
As of version 8.x-1.0-beta1, the Layout Builder Styles module does not provide a way to control the order which layout builder styles are listed on the Layout Builder interface.

### Is your feature request related to a problem? Please describe.
When adding a block to a page with Layout Builder, the layout builder styles are presented in a seemingly random order.

### Describe the solution you'd like
A [patch](https://www.drupal.org/project/layout_builder_styles/issues/3080384#comment-13482922) has been uploaded to drupal.org by one of the module maintainers that adds weight to layout builder styles allowing manual ordering.  We should try this patch and if it works, update our exported layout builder styles to include weights.

### Describe alternatives you've considered
@akslay and @joeparsons worked on a much simpler patch that would have just applied an alphabetical order to the layout builder styles but the patch now available from the module maintainer looks more promising.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Adds patch submitted by module maintainer which adds weights to layout builder style config entities and updates existing exported layout builder styles with weights to make order more predictable in Layout Builder UI.

## Related Issue

Fixes #46.

## How Has This Been Tested?

Tested locally with Lando.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
Patch applied successfully with composer in ProboCI build:
```
  - Installing drupal/layout_builder_styles (1.0.0-beta1): Loading from cache
  - Applying patches for drupal/layout_builder_styles
    https://www.drupal.org/files/issues/2019-11-06/deprecated-3092650-2.patch (D9 deprecation fixes)
    https://www.drupal.org/files/issues/2020-02-27/3080384-6.patch (Style ordering)
```

**Comment by joeparsons** [comment]
Looks like the patch does add a new deprecation notice 😞:
```
 ------ ----------------------------------------------------------------------------- 
  Line   modules/contrib/layout_builder_styles/src/LayoutBuilderStyleListBuilder.php  
 ------ ----------------------------------------------------------------------------- 
  34     Call to deprecated method getLabel() of class                                
         Drupal\Core\Entity\EntityListBuilder:                                        
         in drupal:8.0.0 and is removed from drupal:9.0.0.                            
         Use $entity->label() instead. This method used to escape the entity          
         label. The render system's autoescape is now relied upon.                    
 ------ ----------------------------------------------------------------------------- 
```

**Comment by joeparsons** [comment]
Ok, this is now using an updated version of the patch that I added to the [drupal.org issue](https://www.drupal.org/project/layout_builder_styles/issues/3080384#comment-13487341) which removes the deprecation warning.

**Comment by tadean** [comment]
The new patch applied successfully in my local testing and removed the drupal-check error:
```
  - Installing drupal/layout_builder_styles (1.0.0-beta1): Loading from cache
  - Applying patches for drupal/layout_builder_styles
    https://www.drupal.org/files/issues/2019-11-06/deprecated-3092650-2.patch (D9 deprecation fixes)
    https://www.drupal.org/files/issues/2020-03-02/3080384-9.patch (Style ordering)
```

```
drupal-check web/modules/contrib/layout_builder_styles/src/LayoutBuilderStyleListBuilder.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%                                                                                                                    
 [OK] No errors                                                                                                         
```

I visited `admin/config/content/layout_builder_style` and confirmed that the styles had a weight available and that the weight seemed to be respected in the style ordering on the layout forms.

**Comment by joeparsons** [comment]
Updated the patch one more time to enable autoescaping of the layout builder style labels in the list view ([see on drupal.org](https://www.drupal.org/project/layout_builder_styles/issues/3080384#comment-13487374)).

**Comment by akslay** [comment]
Is anyone else experiencing the "Array" text as the label instead of the actual label?
Screen Shot 2020-03-03 at 9 00 08 AM

**Comment by joeparsons** [comment]
@akslay, OK, I've reverted my latest change.  That issue should be fixed now.

**Pull request merged**
