### PR TITLE
Closes #1963 Node contextual links missing in views that render content using a display mode.

### LINKED ISSUE #1963: Node contextual links missing in views that render content using a display mode.
## Problem/Motivation
As a content editor, I would like to edit content from a view page via contextual links.

### Describe the bug
At the moment nodes rendered in views do not display contextual links on each piece of node content.

### To Reproduce

With demo content enabled
Go to /news 
Hover over individual news items
See no contextual links for editing or deleting the node.

## Proposed resolution

Add a node.twig.html that adds contextual links to the node template.

### Expected behavior

When I hover over rendered nodes, I should see a gear with links to delete or edit content.

##  Screenshots
image

### PR DESCRIPTION
**Pull request by trackleft**
## Description

According to this ticket on Drupal.org https://www.drupal.org/project/bootstrap_layouts/issues/2788997
Contextual links are added via the node template like this:
```
+  {{ title_suffix.contextual_links }}
```

## Related issues
Closes #1963 
Related #1519 

## How to test
With demo content enabled
Log in
Go to /news 
Hover over individual news items
See contextual links for editing or deleting the node.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by joeparsons — APPROVED** [review]
We may need some follow-ups to improve the UX of multiple contextual links showing up in the same place but we definitely should restore this functionality for nodes IMHO.

**Comment by joshuasosa** [comment]
I think the solution is actually in this Bootstrap Barrio issue:
https://www.drupal.org/project/bootstrap_barrio/issues/3158009

AZQS uses Bootstrap Barrio 8.x-4.30 and this patch was added in with 8.x-4.31. I tested the change in this patch locally and it seems to bring the contextual filters out as expected on event views. Please consider updating Bootstrap Barrio instead of implementing the current change in this PR.

**Comment by trackleft** [comment]
thanks for the feedback, I'll look into it

**Comment by joeparsons** [comment]
> I think the solution is actually in this Bootstrap Barrio issue: [drupal.org/project/bootstrap_barrio/issues/3158009](https://www.drupal.org/project/bootstrap_barrio/issues/3158009)
> 
> AZQS uses Bootstrap Barrio 8.x-4.30 and this patch was added in with 8.x-4.31. I tested the change in this patch locally and it seems to bring the contextual menus out as expected on event views. Please consider updating Bootstrap Barrio instead of implementing the current change in this PR.

Created an alternate PR with your suggestion @joshuasosa: #1981

**Comment by trackleft** [comment]
Closed in favor of https://github.com/az-digital/az_quickstart/pull/1981

**Pull request closed without merging**
