### PR TITLE
Add Cards Paragraph

### PR DESCRIPTION
**Pull request by tadean**
This PR adds a cards paragraph and behavior settings based on @joeparsons `composite-fields` branch.

## Description
This PR adds a cards paragraph and behavior settings based on @joeparsons `composite-fields` branch.

## Related Issue
#289 

## How Has This Been Tested?

- Create page content
- Attempt to add cards paragraph content, and add several cards within the paragraph
- Save content and verify the cards are rendered correctly
- Edit content and determine if the column setting options on the cards paragraphs work correctly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
image

**Comment by tadean** [comment]
- Use "Bordered Cards" for name for default card style.
- Column settings for tablet/mobile views as additional options (possible followup)
- Manual crop strategy (followup)
- Followup - should additional behaviors classes inherit from default?

**Comment by tadean** [comment]
Added additional settings for tablet and phone from @danahertzberg :

image

**Comment by tadean** [comment]
Changed style name of "Card" to "Bordered Card"

**Review by trackleft — COMMENTED** [review]
@akslay maybe we should use this image style for person content type.

**Comment by trackleft** [comment]
I think we can move this image style to the profile so that it can be used in az_person content type as well. https://github.com/az-digital/az_quickstart/pull/373/files/24477c74fdeb6e2b833141955db6a3aab42b02cd#diff-35aa3a69257bb4314f1feb78cd40cc3fa98f21833f462b0c7dd3dbc138ed5e59

**Comment by tadean** [comment]
> I think we can move this image style to the profile so that it can be used in az_person content type as well. https://github.com/az-digital/az_quickstart/pull/373/files/24477c74fdeb6e2b833141955db6a3aab42b02cd#diff-35aa3a69257bb4314f1feb78cd40cc3fa98f21833f462b0c7dd3dbc138ed5e59

FWIW, I'd regard this card image style as a placeholder as it doesn't yet incorporate a to-be-decided solution for manual cropping which is necessary for the card images.

**Comment by tadean** [comment]
Add `card-img-top` class.

**Comment by tadean** [comment]
Replaced usage of `w-100` with `card-img-top` in card formatter plugin.

**Review by mmunro-ltrr — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
Follow-ups:
- Replace hard-coded lists of bootstrap classes with custom "card style" config entities
- Image cropping
- Add entity reference dependencies
- Improve drag & drop ordering for cards
  - Ideal would be cards draggable in "collapsed" paragraph UI
  - We should at least add back collapsible field group wrapper around individual card fields.

**Pull request merged**
