### PR TITLE
Closes #1436: Remove photo caption from AZ Person displays

### LINKED ISSUE #1436: Empty caption/address space on all person images.  Hide space if no caption.
There is a space under person images where a caption or address info goes - but most person images have no caption, yet the space remains.  Hide space if no caption
Screen Shot 2022-03-29 at 9 01 48 AM
Screen Shot 2022-03-29 at 8 25 13 AM
.

### PR DESCRIPTION
**Pull request by danahertzberg**
## Description
Update Person default and row displays so they don't show the caption for the images. 

## Related issues
Closes #1436 

## How to test
1. Add a person with image
2. Add a caption/credit to the used image
3. Verify caption/credit does not appear on any views or people pages
4. Verify extra space does not appear on a person page

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Carris-Toupin** [comment]
I believe they want the removal of both the Caption and the Image Credit as well.

**Review by camikazegreen — APPROVED** [review]

**Comment by sanjanans** [comment]
I reviewed the PR and it works as desired. So I am approving the PR.

Just a thought- what if some websites want to display image credit and/or captions with their person listing? Would it be possible to have a checkbox to make that choice?

**Review by sanjanans — APPROVED** [review]
The PR works as desired. Thanks Dana for taking care of it.

**Comment by danahertzberg** [comment]
> I reviewed the PR and it works as desired. So I am approving the PR.
> 
> Just a thought- what if some websites want to display image credit and/or captions with their person listing? Would it be possible to have a checkbox to make that choice?

I think that's a great follow up ticket!

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
