### PR TITLE
feature/83-az-seo adding the seo modules

### PR DESCRIPTION
**Pull request by camikazegreen**
## Description
This adds the xmlsitemap, redirect, metatag and pathauto contrib modules

## Related Issue
feature/83-az-seo 

## How Has This Been Tested?
Locally. This probably needs more review.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by camikazegreen** [comment]
I opted not to include the settings overrides file, since pathauto was already included in the install profile and had all of the necessary settings already. It makes sense to just exclude pathauto from az_seo entirely.

**Comment by camikazegreen** [comment]
This is now ready for review.

**Comment by joeparsons** [comment]
- Merge main, resolve conflicts
- Remove config overrides file
- Move overrides config files into config/quickstart folder

**Review by tadean — APPROVED** [review]

**Review by jwmoore1 — CHANGES_REQUESTED** [review]
There's a newer version (1.15) of the Metatag module. Should we go ahead and update that now?

**Review by kevcooper — CHANGES_REQUESTED** [review]
I don't think we want to delete these files:

- .ddev/commands/web/install
- .github/workflows/security.yml
- .lando.yml
- .probo.yaml

**Review by kevcooper — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Review by jwmoore1 — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
