### PR TITLE
[Branch for issue/2997-finder-demo-content] Update sidebar styling

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description

This branch of the `issue/2997-finder-demo-content` branch (for [PR #2998](https://github.com/az-digital/az_quickstart/pull/2998)) makes significant changes to the az-bef-sidebar.css file to style the sidebar to be closer to the [Adobe XD mockup](https://xd.adobe.com/view/223ea53b-daf0-42c7-a500-60c0eda3fddc-776d/screen/ae93ab30-2ad1-4bab-9746-f7417b1f73de).

## How to test

https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3164.probo.build/pages/page-list-finder

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joshuasosa** [comment]
Where can we see the Adobe XD mockup referenced here?

Looks pretty good. I think the large gray text (Split Screen, Text, Views) looks strange alongside the large blue text (Events, Photo Galleries, etc). I get that the blue ones seem to represent categories, but it looks off to me color-wise.

It'd be neat if the categories (Cards, Carousels, Events, etc) could have their own checkbox next to them. The expected usage would be checkmarking a parent would checkmark all the child options.

**Comment by danahertzberg** [comment]
Here is the mockup: https://xd.adobe.com/view/223ea53b-daf0-42c7-a500-60c0eda3fddc-776d/screen/794d4a8b-3b85-4224-9024-06a2639be7ce/

I made a few smaller changes to the styles. I would still like to see the following that can be addressed in the main PR.
- [ ] li > ul > li bold if it does not have a nested ul
- [ ] Only have the level-2 expand/collapse, not anything deeper.

**Comment by bberndt-uaz** [comment]
> Where can we see the Adobe XD mockup referenced here?
> 
> Looks pretty good. I think the large gray text (Split Screen, Text, Views) looks strange alongside the large blue text (Events, Photo Galleries, etc). I get that the blue ones seem to represent categories, but it looks off to me color-wise.
> 
> It'd be neat if the categories (Cards, Carousels, Events, etc) could have their own checkbox next to them. The expected usage would be checkmarking a parent would checkmark all the child options.

Thanks for the feedback @joshuasosa! I added the [link to the Adobe XD mockup](https://xd.adobe.com/view/223ea53b-daf0-42c7-a500-60c0eda3fddc-776d/screen/ae93ab30-2ad1-4bab-9746-f7417b1f73de) in the description. I agree that color difference in the large text is strange--we'll be discussing this in the AZ Digital meeting.

**Review by danahertzberg — APPROVED** [review]

**Comment by trackleft** [comment]
Future discussion https://github.com/az-digital/az_quickstart/pull/2998

**Pull request merged**
