### PR TITLE
Closes #647: Use linkit for Card field link elements.

### LINKED ISSUE #647: More Complete Solution for FAPI Internal/External Link Element
## What is the problem that we want to solve?
Some of our Forms and compound Field Widgets have a need to store links, and often these require storage of both internal and external links. This has changed a great deal from D7 and D8-D9 in that there is now a pretty large difference between an absolute link (a string), and an internal route (usually a reference to a specific route and its contained parameters.)

This makes it complicated to create forms that store both kinds of links.

The [FAPI Url element](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Url.php/class/Url/9.1.x) does not handle internal paths.
The [FAPI Path element](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21PathElement.php/class/PathElement/9.1.x) does not handle external paths.

Ideally we would like access to some form element that handles both types.

Core sometimes implements this as an Entity autocomplete field that searches internal routes but also has extra validation that allows it to accept extenal links. (see the Menu add link form).

This need is for **custom forms and form elements**, **it is not applicable** to content types that use the **Field Link** type (which already handles both types).

## Conditions of satisfaction
- [ ] Combination of validation/ajax handlers that allow a form element to handle both internal and external links.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Updates the link element(s) within Card fields to use linkit.

Also adds patch to fix known issue with linkit affecting pages with multiple linkit form elements (https://www.drupal.org/project/linkit/issues/2925828).

Big thanks to @michaelhagedon for originally tracking down the form element provided by the linkit module, to @akslay for adding the linkit module (and linkit profile) to Quickstart, and to @trackleft for finding the linkit patch.

## Related issues
Closes #647 

## How to test
- Add cards with links (link to internal and external URLs)
- Update cards with links

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [x] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
The broken check is addressed in this other PR: #1882

**Comment by joshuasosa** [comment]
Looks and works pretty well.

I see that the Card Link URL now appears outside the individual card editing interface:
image

At the moment, it's a bit confusing. I edited the default card deck page, saw that Card Link URL field, and successfully used linkit to fill in a link. But saving and checking the page, there was no link added. That behavior is due to no Card Link Title being added.

I think the Card Link URL field should at least remain within the card editing interface instead of hanging outside of it. That way the Card Link Title field is more obvious, and there may be a little less confusion as to why a card with a filled in link doesn't get a link.

On the other hand, the card link behavior could be changed to be more like UAQS. In UAQS, a filled in card link with no title will at least show the link as a regular URL. Along those lines, I don't know if linkit supports it, but if it could automatically pull in the page title and either fill it in to the Card Link Title or display it when title is left blank, that'd be a convenient option.

Could a linkit matcher be included by default for webform content type as well?

**Comment by trackleft** [comment]
Worked for me in a card deck paragraph 
Screen Shot 2022-09-02 at 9 52 24 AM

**Comment by joeparsons** [comment]
> I think the Card Link URL field should at least remain within the card editing interface instead of hanging outside of it. That way the Card Link Title field is more obvious, and there may be a little less confusion as to why a card with a filled in link doesn't actually get a link.

Thanks for reviewing and testing @joshuasosa!  I've fixed the issue with the card link field showing up outside the card editing interface.

**Comment by danahertzberg** [comment]
@joeparsons to review PHP deprecation warnings and can't log in

**Comment by bberndt-uaz** [comment]
Error messages from the logs in Probo:

**Error: Class "Robo\Robo" not found in Drush\…**

```
Error: Class "Robo\Robo" not found in Drush\Log\DrushLog->log() (line 66 of /src/az-quickstart-scaffolding/vendor/drush/drush/src/Log/DrushLog.php)
#0 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Logger/LoggerChannel.php(127): Drush\Log\DrushLog->log()
#1 /src/az-quickstart-scaffolding/web/core/includes/errors.inc(175): Drupal\Core\Logger\LoggerChannel->log()
#2 /src/az-quickstart-scaffolding/web/core/includes/errors.inc(83): _drupal_log_error()
#3 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#4 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(571): _drupal_error_handler()
#5 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(571): include('...')
#6 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#7 /src/az-quickstart-scaffolding/vendor/drush/drush/src/Log/DrushLog.php(66): Composer\Autoload\ClassLoader->loadClass()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Logger/LoggerChannel.php(127): Drush\Log\DrushLog->log()
#9 /src/az-quickstart-scaffolding/vendor/psr/log/Psr/Log/LoggerTrait.php(99): Drupal\Core\Logger\LoggerChannel->log()
#10 /src/az-quickstart-scaffolding/web/core/modules/user/user.module(1227): Drupal\Core\Logger\LoggerChannel->notice()
#11 /src/az-quickstart-scaffolding/web/core/modules/user/src/Controller/UserController.php(319): user_logout()
#12 [internal function]: Drupal\user\Controller\UserController->logout()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#16 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#17 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(159): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#19 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#21 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#22 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#24 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#25 /src/az-quickstart-scaffolding/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#26 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle()
#27 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#28 {main}
```

**Deprecated function: Return type of Drupal\linkit\…**

```
Deprecated function: Return type of Drupal\linkit\Suggestion\SuggestionCollection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 571 of /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#1 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(571): _drupal_error_handler()
#2 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(571): include('...')
#3 /src/az-quickstart-scaffolding/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#4 /src/az-quickstart-scaffolding/vendor/drush/drush/src/Log/DrushLog.php(66): Composer\Autoload\ClassLoader->loadClass()
#5 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Logger/LoggerChannel.php(127): Drush\Log\DrushLog->log()
#6 /src/az-quickstart-scaffolding/vendor/psr/log/Psr/Log/LoggerTrait.php(99): Drupal\Core\Logger\LoggerChannel->log()
#7 /src/az-quickstart-scaffolding/web/core/modules/user/user.module(1227): Drupal\Core\Logger\LoggerChannel->notice()
#8 /src/az-quickstart-scaffolding/web/core/modules/user/src/Controller/UserController.php(319): user_logout()
#9 [internal function]: Drupal\user\Controller\UserController->logout()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#11 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#12 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#14 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(159): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#15 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#16 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#17 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#18 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#19 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#21 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#22 /src/az-quickstart-scaffolding/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle()
#24 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#25 {main}
```

**Comment by joeparsons** [comment]
Looks like a fix for the deprecation warning has already been committed by the Linkit module maintainers but not yet included in a release: https://www.drupal.org/project/linkit/issues/3262401

I added the patch to this PR.

**Review by trackleft — APPROVED** [review]

**Review by joshuasosa — APPROVED** [review]
Works well testing in the probo site.

Any comment about adding webform as a matcher?

**Comment by joeparsons** [comment]
> Any comment about adding webform as a matcher?

Thanks for testing again, @joshuasosa!  Re: adding a webform matcher, yes, I think that would be a good improvement to make in a separate issue/PR.  We spent a lot of time refining the current matchers during a Wednesday workshop before merging #1836 but we didn't think to add a matcher config for webforms.  Would you mind creating a separate issue for adding that?

**Review by tadean — APPROVED** [review]

**Pull request merged**
