### PR TITLE
Closes #1841: "Downgrade" ctools to 8.x-3.11.

### LINKED ISSUE #1841: Downgrade ctools module to 8.x-3.11
## Problem/Motivation
Back in #1717 we updated ctools to 4.0.0.  Later we updated to 4.0.1 in #1791 because the ctools 4.0.0 release was unpublished.

Since that time the module maintainer has made it clear that 8.x-3.11 is the latest version that all sites should be using and that 4.x releases are not supported:
https://www.drupal.org/project/ctools/issues/3300682#comment-14647155

## Proposed resolution
Downgrade ctools to latest 3.x version.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
https://www.drupal.org/project/ctools/issues/3300682#comment-14647155

## Related issues
Closes #1841 

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [x] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
I was getting those errors, and had to run distro update in full reset mode  on all quickstart config

**Comment by joeparsons** [comment]
> I was getting those errors, and had to run distro update in full reset mode on all quickstart config except the theme to fix, so I suppose there is something wrong with our config, but I wasn't able to narrow it down to the exact problem.

You've still been seeing the error referenced in the d.o. issue since we made the changes in #1791?

**Comment by trackleft** [comment]
> You've still been seeing the error referenced in the d.o. issue since we made the changes in https://github.com/az-digital/az_quickstart/pull/1791?

I saw them on https://live-azs-cs.pantheonsite.io which had QS 2.4.1

**Comment by joeparsons** [comment]
Confirmed that the stored module schema version for the 4.x releases is the same as it is for the 8.x-3.x releases so we shouldn't need to worry about reverting that:
```
mysql> select collection, name, convert(value using utf8) from key_value where collection = "system.schema" and name = "ctools";
+---------------+--------+---------------------------+
| collection    | name   | convert(value using utf8) |
+---------------+--------+---------------------------+
| system.schema | ctools | i:8000;                   |
+---------------+--------+---------------------------+
1 row in set (0.05 sec)
```

**Review by tadean — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
