### PR TITLE
Fixes #280, fixes #277 Remove Layout Builder Customizations

### LINKED ISSUE #277: Remove Display Suite
We've decided we'll be using Paragraphs for flexible pages and not Layout Builder so we should be able to remove Display Suite now that it was mainly needed for our Layout Builder based Flexible Page implementation.

### LINKED ISSUE #280: Remove Layout Builder Customizations
## Motivation
We've elected to use paragraphs for our primary content generation, and thus many of the layout builder customizations that are geared towards using inline layout builder blocks as content are no longer necessary and should be removed.

## Proposed Resolution
Removal of layout builder customizations and the associated inline blocks.

### Describe the solution you'd like
The layout builder customizations should be removed, and ideally a placeholder paragraphs field should be added to the page type, as the implication of removing the layout builder customizations is that there won't really be any way for a page to have "content" in the gap until paragraphs are added.

### Describe alternatives you've considered
We did a thorough examination of gutenberg, layout builder, and paragraphs, and elected to use paragraphs for our content.

### PR DESCRIPTION
**Pull request by tadean**
This PR removes our Layout Builder customizations and replaces them with a placeholder paragraph reference field to prepare for our transition to paragraphs.

## Description
Configuration related to our Layout Builder customizations has been removed, paragraphs has been added, and the Page content type has been given a paragraph reference field in order to provide a placeholder for our paragraphs implementations.

Since removing the Layout Builder customizations effectively leaves Page without any way to add content, a simple placeholder paragraph bundle has been added (`az_text`).

This placeholder implementation follows the same pattern as the D7 implementation: `az_content_chunks` contains the modules related to the paragraph bundles, and the individual paragraph bundles are submodules inside it, in this case `az_content_chunks_text`.

The placeholder `az_content_chunks` module provides library loading functionality such as we originally had on our inline blocks for Layout Builder (ie. it's possible to load CSS and JS for a specific paragraph bundle.)  The placeholder `az_text` bundle has a CSS file defined, not because it's necessary, but just to demonstrate the functionality for furture work.

Display Suite has been removed as it was no longer required for anything, which fixes #277 

Flexible pages will have paragraphs available only for the `az_content_chunks` submodules that are currently enabled.

## Related Issue
#280 #277 

## How Has This Been Tested?
Attempt to create a Flexible Page using the provided paragraph bundle.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
image
image

**Comment by tadean** [comment]
A test should ideally be added before merging, as there used to be one present in the layout builder customizations.

**Comment by joeparsons** [comment]
Looks like the Deprecated Code check failures are all due to classes extending base classes provided by modules that we don't include in Quickstart.  I'm assuming the Entity Reference Revisions and Paragraphs module classes provide optional functionality that is only available if the modules providing the base classes are installed but do you think we should consider adding any of these modules?

- Diff
- Entity Browser
- Feeds

**Comment by trackleft** [comment]
> * Diff
> * Entity Browser
> * Feeds

I think I like all of those modules.

**Comment by tadean** [comment]
I'd be open to including those if it squelches the warnings, they all seem like pretty useful utility modules in general to have in our toolkit.

**Comment by trackleft** [comment]
Hey Troy how do you feel about using an object oriented approach to this, as seen in the attached module?
[az_components.zip](https://github.com/az-digital/az_quickstart/files/5163792/az_components.zip)

**Comment by tadean** [comment]
> Hey Troy how do you feel about using an object oriented approach to preprocessing paragraphs, as seen in the attached module?
> [az_components.zip](https://github.com/az-digital/az_quickstart/files/5163792/az_components.zip)

I like it! I'll update to do something similar.

**Comment by tadean** [comment]
Updated with D9 changes from master.

`feeds` and `entity_browser` both have their own deprecation warnings when they're added to the build to attempt to solve the deprecation warnings. FWIW, feeds doesn't have a stable release yet, either. I'll look into if maybe there are any patches floating around that solve the original issues.

**Comment by tadean** [comment]
- Added basic unit test
- Switched preprocessing of paragraphs to being in a Drupal service per @trackleft 's suggestion.

**Review by trackleft — DISMISSED** [review]

**Comment by tadean** [comment]
Updated pull request to change the name of `az_content_chunks` to `az_paragraphs`.

**Comment by tadean** [comment]
image

**Review by joeparsons — DISMISSED** [review]

**Review by trackleft — DISMISSED** [review]

**Comment by tadean** [comment]
Updated to change the label of the text area of the placeholder paragraph from `AZ Text Area` to `Text`.
image

Updated to change the description/name of the placeholder paragraph bundle module from `Plain Text` to `Text`, to support the requirements of the proposed final Text paragraph.
image

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
Per 2020-09-09 PR meeting & 2020-09-11 Friday meeting: new deprecation warnings will be addressed in followup issue.

**Pull request merged**
