### PR TITLE
Closes #1489: Fix media permission denied for authenticated user role.

### LINKED ISSUE #1489: Media permission denied for authenticated user role
## Problem/Motivation
Content using Media on a site that allows anonymous viewing would have the expectation that authenticated users could also see the same media. On a clean install, authenticated users cannot see media, such as on a news article or person profile.

### Describe the bug
For the permission "View media," the checkbox is checked for 'Anonymous user' but not for 'Authenticated user'. An authenticated user would have to have the role of 'Content editor' and/or 'Administrator' to be able to view media. There should be no reason to deny this permission to generic authenticated users when anonymous users get the permission.

### To Reproduce
1. Clean install AZQS (used scaffolding)
2. Enable AZQS demo content
3. Create a test user with no other roles
4. Log into the test user and navigate to News or People to see missing imagery

## Proposed resolution
Enable "View media" for "Authenticated user" and export the change for new installs. Optionally add an update hook to enable the permission on existing sites.

### Expected behavior
Authenticated users should be able to view media.

##  Screenshots
**Logged out as an anonymous user:**
image
image

**Logged in as a generic authenticated user with no roles:**
image
image

### PR DESCRIPTION
**Pull request by Carris-Toupin**
## Related issues
This PR is to fix issue #1489  [Media permission denied for authenticated user role](https://github.com/az-digital/az_quickstart/issues/1489)

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
> I don't believe this will update sites retroactively but I think that is fine.

It should get updated via config distro update, though.

**Comment by trackleft** [comment]
> It should get updated via config distro update, though.

For most sites at least

**Review by bberndt-uaz — APPROVED** [review]
Looks good!
image

**Review by tadean — APPROVED** [review]

**Review by joshuasosa — APPROVED** [review]
Looks good! Thanks for fixing!

**Pull request merged**
