### PR TITLE
Fixes #3030 Link Publication Titles to Node.

### LINKED ISSUE #3030: Link Publication Titles to Node
## Motivation
@ejsamboy passed along a request from a stakeholder site that publication titles should link to their respective node.

## Proposed Resolution
Publication titles could link to their node if they do not have an external reference/file (potentially they could link to their DOI entry also, if there is a DOI number)

### Describe alternatives you've considered
Not linking to the node.

### PR DESCRIPTION
**Pull request by tadean**
## Description
This PR adds functionality that causes generated citations to link the publication title to the node page if no other link applies. If the publication contains an uploaded file or external link, that will continue to be linked in preference to the node page.

## Related issues
#3030 

## How to test
- enable `az_publication`
- create publications
- create view of publications if desired
- verify that references link publication title to node page
- Give some publications a link or publication file
- Verify that the more specific links are chosen over the node link in those cases

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [x] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
**Topics for discussion:**
- Do we want this to always happen? Should there be a required triggering circumstance? (e.g. maybe 'only link to the node page if the publication has an Abstract or cover page to see, otherwise don't link it')
- The reference containing a link to the node means that the node page has a link to itself when rendering the reference. Do we need to alter this? If so, how?

**Comment by trackleft** [comment]
My vote is optionally or conditionally linking instead of always linking.

**Comment by tadean** [comment]
Added a conditional check that causes the self-referential link to not happen if viewing the full node (only). Maybe there's some way to make that configurable - not sure if pseudofields can have display settings.

**Comment by tadean** [comment]
Based on discussion on 1/3, added a potential commit that causes the fallback link to the full node page to happen only if the pub has a cover page or abstract, as otherwise the node potentially has nothing more to see than the reference. This may be modified in the future if the display mode of the full node eventually has more to see than the reference entry.

**Review by danahertzberg — APPROVED** [review]

**Review by sanjanans — APPROVED** [review]

**Comment by sanjanans** [comment]
I couldn't find az_publications module in the list. Did you mean enable "Quickstart Publication" in your instructions for how to test?

**Review by bberndt-uaz — APPROVED** [review]

**Pull request merged**
