### PR TITLE
Closes #902: Removing basic restricted html permissions

### LINKED ISSUE #902: Limit basic and restricted html to administrators
Only administrators should be able to use the basic and restricted html text editors. 

## Conditions of satisfaction
- [ ] Content editors will only have standard option
- [ ] Content admins will have standard and full html
- [ ] Administrators will have all four text editors

### PR DESCRIPTION
**Pull request by smayden**
This PR removes permission for restricted html (for the anonymous role) and basic html (for authenticated role).

## Description
Currently content editors and admins are seeing the basic and restricted html as text format options when editing content.

It appears that this is because basic html and restricted html are permitted for anonymous/authenticated roles (and all content editors/admins also have those roles).

Current permissions in QS 2:

Anonymous - restricted html
Authenticated - basic html
Content editor - standard
Content admin - full html (would also be able to use standard as they are assigned editor role as well)
Administrator - restricted, basic, standard, full

This PR changes things to:
Anonymous - none
Authenticated - none
Content editor - standard
Content admin - full html (would also be able to use standard as they are assigned editor role as well)
Administrator - restricted, basic, standard, full

## Related Issue
#902 

## How Has This Been Tested?
Tested locally and in Probo

Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-904.probo.build/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by smayden** [comment]
Well, that didn't work

**Review by trackleft — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by trackleft** [comment]
You'll want to change these files as well 

https://github.com/az-digital/az_quickstart/blob/main/config/install/filter.format.basic_html.yml#L12
https://github.com/az-digital/az_quickstart/blob/main/config/install/filter.format.restricted_html.yml#L8

**Review by trackleft — CHANGES_REQUESTED** [review]
remove the permissions set directly on the filters

**Comment by smayden** [comment]
This should be ready to review (aside from the tests not running):

Review here: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-904.probo.build/

**Review by trackleft — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
