### PR TITLE
Closes #1570: Ensure better_exposed_filters module is installed.

### LINKED ISSUE #1570: az_news views now require better exposed filters module
## Problem/Motivation
The changes we made in #1539 added a module configuration dependency to `views.view.az_news` but we did not include a DB update to ensure the module is installed.

### Describe the bug
Encountered while testing 2.3.0-beta1 on an existing site and trying to run `config-distro-update`:

```
[error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Configuration <em class="placeholder">views.view.az_news</em> depends on the <em class="placeholder">Better Exposed Filters</em> module that will not be installed after import. in Drupal\Core\Config\ConfigImporter->validate() (line 750 of /code/web/core/lib/Drupal/Core/Config/ConfigImporter.php). 

In ConfigImportCommands.php line 360:
                                                                               
  The import failed due to the following reasons:                              
  Configuration <em class="placeholder">views.view.az_news</em> depends on th  
  e <em class="placeholder">Better Exposed Filters</em> module that will not   
  be installed after import.   
```

## Proposed resolution
Add DB update to `az_news` module to ensure BEF is installed.

### PR DESCRIPTION
**Pull request by joeparsons**
## Related issues
Closes #1570 
Introduced in #1539

## How to test
- Add PR diff as composer patch to existing site
- Run drush updatedb

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Looks good so far 
image

**Comment by trackleft** [comment]
Don't we want the number to be 930103

**Comment by joeparsons** [comment]
> Don't we want the number to be 930103

Don't think so.  This is the first `az_news` database update for the 2.3.x branch...

**Comment by trackleft** [comment]
For reference  https://github.com/az-digital/az_quickstart/issues/1350

**Comment by trackleft** [comment]
image
Update applied successfully,

**Comment by trackleft** [comment]
And I was able to update config successfully with no errors.

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
Worked for me in my testing on an existing site as well.

**Review by danahertzberg — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Pull request merged**
