### PR TITLE
az-digital/az-icons#17: Update icon font with vimeo icon

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Adding updated icon font
renamed:    png/pintrest.png -> png/pinterest.png
deleted:    .gitignore
modified:   az-icons-styles.css
modified:   fonts/az-icons.eot
modified:   fonts/az-icons.svg
modified:   fonts/az-icons.ttf
modified:   fonts/az-icons.woff
renamed:    png/pintrest.png -> png/pinterest.png
new file:   png/vimeo.png
new file:   svg/vimeo.svg
deleted:    "png/Icon\r"

## Related issues
[#add vimeo icon](https://github.com/az-digital/az-icons/issues/17)

## How to test
Enable global footer add icons to menu.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [x] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelhagedon** [comment]
Quickstart has its own copy of az-icons? (Sorry if this came up in discussion today -- I was definitely multi-tasking...)

**Comment by camikazegreen** [comment]
@michaelhagedon It does for now. See https://github.com/az-digital/az-icons/pull/22 for a potential fix to that.

**Comment by trackleft** [comment]
Yes there is a config setting for az_barrio that allows switching between remote or local
For better performance, local is desired supposedly
Also, if the cdn ever goes down you should be able to switch to local
image

**Comment by michaelhagedon** [comment]
Ah, thanks, yeah I just found that setting too. I was just surprised -- we got the vimeo icon as soon as it was merged, but we're set to external. 

That local setting is a bit of extra work!

**Comment by trackleft** [comment]
> Ah, thanks, yeah I just found that setting too. I was just surprised -- we got the vimeo icon as soon as it was merged, but we're set to external.
> 
> That local setting is a bit of extra work!

The things we do to eek out performance and stability.

**Comment by trackleft** [comment]
This works https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1464.probo.build/

**Review by bberndt-uaz — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
