### PR TITLE
Closes #3233 Auto-Import for Trellis Events

### LINKED ISSUE #3233: Auto-Import for Trellis Events
## Motivation
Users would like to be able to save recurring searches that they want to automatically be imported into their site.

### Is your feature request related to a problem? Please describe.
Currently, keeping a site up to date with a specific event search requires manual intervention when new events meeting those criteria have been added.

## Proposed Resolution
We'd like for the user of the Trellis Event Importer to be able to designate that a given set of search settings is intended to be recurring and will periodically be imported automatically.

### PR DESCRIPTION
**Pull request by tadean**
## Description
This PR provides a configuration entity that is used to store details of saved Trellis event searches to allow them to periodically be re-imported. These searches are executed when the periodic cron trellis event migration is run and the collected event IDs are passed to the migration.

## Related issues
Closes #3233 

## How to test

- enable `az_enterprise_attributes_import` and `az_event_trellis`
- visit `/admin/config/az-quickstart/settings/az-recurring-import-rule` and verify a new import rule can be created
- save the rule and click the `View Results` button and verify that the results are displayed
- visit `/admin/trellis-event-importer`
- perform a search, and verify that an import can be created from the view page by clicking `Create Recurring Import` after your search results have returned
- run the `az_trellis_events` migration from drush with `drush migrate:import az_trellis_events` and verify that your events from your saved searches are imported

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
Added recurring import button and matching modal configuration form on the event import page. Note that typically this would be done with a form AJAX callback, but [exposed forms do not support AJAX callbacks](https://www.drupal.org/project/drupal/issues/2842525) because they are GET forms.

Instead, this PR takes the approach of a separate controller that is called and returns a command to open the modal.

**Review by danahertzberg — DISMISSED** [review]
We will still need to update documentation separately. 
> Does this feature run the import on save? Or is that a separate feature? Will run with cron

**Review by trackleft — DISMISSED** [review]

**Comment by bberndt-uaz** [comment]
When testing in Probo, I saved a new import rule and then clicked the View Results button. The next page seemed to load the correct results, but these error messages were displayed at the top of the page:

image
<div>&nbsp;</div>
Expanding the first message shows this:

> Drupal\views\Plugin\views\filter\FilterPluginBase->acceptExposedInput(Array) (Line: 89)
> az_event_trellis_gather_filter_options(Array, Object) (Line: 128)
> az_event_trellis_form_views_exposed_form_alter(Array, Object, 'views_exposed_form') (Line: 545)
> Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'views_exposed_form') (Line: 841)
> Drupal\Core\Form\FormBuilder->prepareForm('views_exposed_form', Array, Object) (Line: 284)
> Drupal\Core\Form\FormBuilder->buildForm('\Drupal\views\Form\ViewsExposedForm', Object) (Line: 134)
> Drupal\views\Plugin\views\exposed_form\ExposedFormPluginBase->renderExposedForm() (Line: 1253)
> Drupal\views\ViewExecutable->build() (Line: 392)
> Drupal\views\Plugin\views\display\PathPluginBase->execute() (Line: 196)
> Drupal\views\Plugin\views\display\Page->execute() (Line: 1645)
> Drupal\views\ViewExecutable->executeDisplay('page_1', Array) (Line: 81)
> Drupal\views\Element\View::preRenderViewElement(Array)
> call_user_func_array(Array, Array) (Line: 111)
> Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 859)
> Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 421)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 240)
> Drupal\Core\Render\Renderer->render(Array, ) (Line: 238)
> Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 627)
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 231)
> Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
> Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
> Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
> call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
> Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 186)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
> Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
> Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
> Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
> Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
> Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
> Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

There appears to be an error message for each search filter I did **not** set as part of my import rule (Owner, Host, Event ID, etc.).

**Comment by tadean** [comment]
Thanks @bberndt-uaz !

This line in the calling stack seems to suggest that it happens in the form alter that tries to gather the form options for a form that was submitted by the view results button:

```
> az_event_trellis_gather_filter_options(Array, Object) (Line: 128)
> az_event_trellis_form_views_exposed_form_alter(Array, Object, 'views_exposed_form') (Line: 545)
```

**Review by bberndt-uaz — APPROVED** [review]
I went through the How to Test steps in Probo and everything looks good!

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
