### PR TITLE
Closes #2023 - Add `HTML administrator` role and shift permissions

### LINKED ISSUE #2023: Create `HTML administrator` role and shift permissions
## Problem/Motivation
Users with the `Content administrator` role are able to switch to the `Full HTML` text format when using a text editor. This is undesirable on sites where the "HTML" paragraph type module is not enabled. Separating out the "HTML" permission from the rest of the "content administrator" permissions would be more desirable.

## Proposed resolution
- Create `HTML administrator` role
- Remove the `Use the Full HTML text format` permission from the `Content administrator` role
- Add the `Use the Full HTML text format` permission to the `HTML administrator` role

Screen Shot 2022-10-25 at 4 09 38 PM

### PR DESCRIPTION
**Pull request by akslay**
## Description
- Adds the `HTML administrator` role
- Removes the `Use the Full HTML text format` permission from the `Content administrator` role
- Adds the `Use the Full HTML text format` permission to the `HTML administrator` role

This change should be communicated to site owners/administrators so they can ensure they re-assign the the new `HTML` role to those that previously had access.

Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2024.probo.build/

## Related issues
Closes #2023 

## How to test
- [ ] Use masquerade (or log in/out manually) to verify that `Content administrator` no longer has access to use the `Full HTML` text format in a text editor. Verify that `HTML administrator` does have access.
- [x] Need to test in multi-dev on a "live" site to ensure updates show up in config distro (assigned to Ashley)

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- **Minor release changes**
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by akslay** [comment]
Tested on Campus Rec site in a multi-dev environment. User role changes appear in config distro and apply cleanly.

**Review by joeparsons — DISMISSED** [review]
This looks good to me.  The only thing I'm not sure about is whether we should consider a different role name (possibly `HTML Editor`?), but I think this is a good, flexible solution to the problems we have with "unexpected" access to the `Full HTML` text format presently.

**Comment by akslay** [comment]
Follow-up tasks:

- Add user role to Probo
- Investigate the core patch to see if it's still needed/used: https://github.com/az-digital/az_quickstart/blob/c334d784053ad18e3f813714f77d62c06edf0b68/composer.json#L143

**Review by joeparsons — APPROVED** [review]

**Comment by akslay** [comment]
Follow-up task:

Update documentation on [Quickstart under the "Roles" heading](https://quickstart.arizona.edu/site-admin/managing-users) so it includes the new role.

**Review by camikazegreen — APPROVED** [review]
I have confirmed that even with the HTML Paragraph type enabled, Content Admins will not be able to add/edit HTML:
Screen Shot 2022-10-31 at 10 07 02 AM

**Review by trackleft — APPROVED** [review]

**Pull request merged**
