### PR TITLE
#469: Fix Github PR template to be more clear

### PR DESCRIPTION
**Pull request by jwmoore1**
## Description
Currently, the first item under Checklist is not clear and often confusing, especially to new contributors. This PR hopes to make the contribution process more clear.

## Related Issue
#469 

## How Has This Been Tested?
This has not been tested as it is simply a change to the template markdown file.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] I've added this Pull Request to the AZ Quickstart project in the right column.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by michaelhagedon — APPROVED** [review]
As one of the mentioned new contributors who tripped over this... is it valid for me to review and approve? Please correct me if not...

Either way, this is clearer IMO.

**Review by trackleft — APPROVED** [review]

**Comment by trackleft** [comment]
I'm glad you found the right file and not the ALL CAPS FOLDER ```https://github.com/az-digital/az_quickstart/tree/main/.github/PULL_REQUEST_TEMPLATE```

**Comment by michaelhagedon** [comment]
> I'm glad you found the right file and not the ALL CAPS FOLDER `https://github.com/az-digital/az_quickstart/tree/main/.github/PULL_REQUEST_TEMPLATE`

LOL, why are there two?

**Comment by trackleft** [comment]
> > I'm glad you found the right file and not the ALL CAPS FOLDER `https://github.com/az-digital/az_quickstart/tree/main/.github/PULL_REQUEST_TEMPLATE`
> 
> LOL, why are there two?

Github idiosyncrasy, they are like we have this handy dandy way of sharing .github templates with a repo like this: 
https://github.com/az-digital/.github

Then they are like, we don't think it should function as you expect though.

**Comment by jwmoore1** [comment]
> As one of the mentioned new contributors who tripped over this... is it valid for me to review and approve? Please correct me if not...
> 
> Either way, this is clearer IMO. Thank you!

It's certainly valid for you to review and approve, and much appreciated.

**Comment by michaelhagedon** [comment]
> Github idiosyncrasy, they are like we have this handy dandy way of sharing .github templates with a repo like this:
> https://github.com/az-digital/.github
> 
> Then they are like, we don't think it should function as you expect though.

How tricky of them!

**Review by danahertzberg — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
