### PR TITLE
Remove `az_google_tag`'s dependency on `ctools` and remove `ctools` from `az_quickstart`.

### PR DESCRIPTION
**Pull request by trackleft**
### Release notes:

Remove dependency on ctools, Removing Chaos Tools
```
~~**IMPORTANT**: Chaos Tools (`ctools`) dependency  removed from Quickstart 2.~~

Quickstart no longer has a runtime dependency on the ctools module, and the module has been slated for removal. This might cause problems if other modules implicitly use ctools functionality without depending on it.

Note that for backwards compatibility, the composer definition still depends on the ctools project, but it's no longer installed on new projects and existing projects may uninstall it if they are not using it.

The composer definition is there so that existing sites do not automatically have the code removed underneath them and continue to work. This will be removed in the future in a new major version. It is recommended to either add an explicit dependency on ctools if you plan to keep using it or uninstall it.

To fully remove ctools from the project, add a replace section to the root composer.json:

 "replace": {
        "drupal/ctools": "*"
    },
Note that this will also skip it in case another module depends on it and the definition will need to be removed then.

Before uninstalling ctools, verify that no configuration dependencies remain on views or other config entities. Views should have that dependency removed automatically when resaving them.
```

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joeparsons** [comment]
```
# composer why drupal/ctools
az-digital/az_quickstart dev-dependabot/composer/drupal/ctools-4.1.0-remove-ctools requires drupal/ctools (*) 
drupal/pathauto          1.12.0                                                    requires drupal/ctools (*) 
```

**Comment by joeparsons** [comment]
FWIW, I think we could just make this change directly to the mian branch (change the target branch for this PR) as an alternative to the dependabot PR instead of targeting the dependabot PR branch.

**Review by joeparsons — APPROVED** [review]

**Comment by trackleft** [comment]
```
www-data@8ded398cc170:/app$ composer why drupal/ctools
az-digital/az_quickstart  2.10.4  requires  drupal/ctools (3.14.0)  
drupal/pathauto           1.12.0  requires  drupal/ctools (*)       
```

**Review by tadean — APPROVED** [review]

**Comment by trackleft** [comment]
Add to https://github.com/az-digital/az_quickstart/blob/main/az_quickstart.install#L80-L83

**Review by joeparsons — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Pull request merged**
