### PR TITLE
Close #2424 Adding badge display for all default taxonomy vocabularies.

### LINKED ISSUE #2424: Implement az_badge view mode for all taxonomy vocabularies that are enabled by default.
It would make sense to implement an `az_badge` display for each taxonomy that is enabled by default.

So far we only have an implementation for [az_person_categories](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories.az_badge.yml) and `az_person_categories_secondary`

IMHO, we can just make 3 copies of the linked file.
```
core.entity_view_display.taxonomy_term.az_news_tags.az_badge.yml
core.entity_view_display.taxonomy_term.az_event_categories.az_badge.yml
core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
```

Extra credit, create the same display for additional vocabularies that are off by default.

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Implemented the az_badge display for all default taxonomy vocabularies so that we can use them in additional displays.

## Related issues
Related to #2406 
Related to #2423 
Related to #2398

## How to test
Add taxonomy as rendered entity to any display mode, and choose Badge.

## Types of changes
Enhancement.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Enabled vocabs by default 
image

Event categories
image

Page Categories
image

News tags
image

Person categories
image

Person categories (secondary)
image

**Comment by camikazegreen** [comment]
This seems like a greate change, but I can't figure out how to test this.

If anyone else is able to "Add taxonomy as rendered entity to any display mode, and choose Badge", I will be happy to review it.

**Review by joeparsons — APPROVED** [review]
Good improvement.  Don't see any issues with adding these.

**Comment by bberndt-uaz** [comment]
@trackleft I'm not sure what's in the scope of this PR, but I wanted to note a couple things:

1. It looks like the terms are displayed as one per row: maybe we want them to display next to each other like the tags on Person pages?
image
  
### 
2. In the HTML markup, there appear to be some extra `<a>` elements which don't have any children. From the example above (on the [Page Grid](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2425.probo.build/page-grid) page):


```html
<div class="field field--name-field-az-page-category field--type-entity-reference field--label-hidden field__items"><a href="/pages/split-screen-no-sidebar" class="field-group-link card-body p-0" hreflang="en">
  </a>
  <div class="field__item"><a href="/pages/split-screen-no-sidebar" class="field-group-link card-body p-0" hreflang="en"></a>
    <div id="taxonomy-term-67" class="taxonomy-term vocabulary-az-page-categories"><a href="/pages/split-screen-no-sidebar" class="field-group-link card-body p-0" hreflang="en">

      </a>
      <div class="content"><a href="/pages/split-screen-no-sidebar" class="field-group-link card-body p-0" hreflang="en">
        </a><a href="/page-categories/split-screen" class="field-group-link badge badge-light badge-link" hreflang="en">
          <div>
            <div class="field field--name-name field--type-string field--label-hidden field__item">Split Screen</div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="field__item">
    <div id="taxonomy-term-65" class="taxonomy-term vocabulary-az-page-categories">

      <div class="content">
        <a href="/page-categories/no-sidebar" class="field-group-link badge badge-light badge-link" hreflang="en">
          <div>
            <div class="field field--name-name field--type-string field--label-hidden field__item">No Sidebar</div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>
```

For the Person taxonomy terms, it looks like we added a [field template](https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/templates/field/field--node--field_az_person_category--az_person.html.twig) and [custom CSS](https://github.com/az-digital/az_quickstart/blob/a0c58c5eb170c98a78ee663d862efc1df8295b03/modules/custom/az_person/css/az_person.css#L1-L4).

**Review by joeparsons — APPROVED** [review]
I'm thinking it'd be good to merge this sooner rather than later and figure out additional implementation details like the things @bberndt-uaz mentioned as a follow-up.

**Pull request merged**
