### PR TITLE
Closes #907: Point Quickstart indicator to quickstart.arizona.edu

### LINKED ISSUE #907: Link to Quickstart documentation from admin toolbar
## Motivation
Content editors need to be able to quickly get to the documentation site. Providing a link from the admin toolbar will make it easy to find documentation as they are editing sites.

## Proposed Resolution

Make existing link in the Quickstart toolbar link to the documentation site (quickstart.arizona.edu). Currently this links to a page with a link to Quickstart settings, but that same link can be found under Configuration (and is not usable by content editors).

### Roles and Permissions considerations
The link should be seen/used by:
- Content editor
- Content administrator
- Administrator

## Additional context
This was discussed in a meeting with several content editors from campus and was agreed as helpful!

### PR DESCRIPTION
**Pull request by smayden**
This PR changes the 'Quickstart 2' link in the admin toolbar to point to the documentation site quickstart.arizona.edu

## Related Issue
#907 

## How Has This Been Tested?
Tested locally and in Probo

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by trackleft — APPROVED** [review]

**Comment by trackleft** [comment]
Looks good to me

**Review by mmunro-ltrr — APPROVED** [review]
Looked at the Probo review site.

**Review by tadean — APPROVED** [review]

**Comment by camikazegreen** [comment]
This is ready to merge as soon as unrelated Probo issues are resolved to run the final tests.

**Comment by joeparsons** [comment]
Was there already discussion about this?  I'm not sure I like the idea of losing the one click access to the Quickstart settings page.  Maybe we could consider adding a link to quickstart.arizona.edu on that page instead?

**Comment by smayden** [comment]
There was discussion about this both in the content owner's working group and Friday meeting. I think the use case of editors needing documentation is much greater than the needing the configuration page (especially since that would only be content admins).

If we aren't comfortable changing the link, then I think we should add a second link in the same area.

**Comment by camikazegreen** [comment]
> Was there already discussion about this? I'm not sure I like the idea of losing the one click access to the Quickstart settings page. Maybe we could consider adding a link to quickstart.arizona.edu on that page instead?

There was a discussion about this. The thought is that it's better to have consistent behavior for both Content Editors (currently get a 403) and Content Administrators. It does give up the one-click access, but that page is still accessible via the Configuration page (and that page isn't as cluttered for Content Admins.)

**Comment by joeparsons** [comment]
I'd be OK with merging this and then revisiting whether we need to add a second link later.

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
