### PR TITLE
Closes 743: Updating image styles and display modes

### PR DESCRIPTION
**Pull request by smayden**
This PR adds needed image styles, view modes, and displays for using images at different sizes (more closely matching QS1)

## Description
Currently some image styles/displays are missing or do not work properly. This PR:

- Adds view mode, image style, and display for "small" - set to 360px (same as QS1)
- Adds image style and updates display for "square" - set to 220x220 (same as QS1)
- Updates image style for medium to 760px (to match QS1, was 360px)
- Updates which embed media is used by Standard text formatter (now: default, small, medium, large, original, card image)
- Set default display to use the small image style (default in QS1 is small)

Some questions/issues:
- Images do not scale based on the column width of where the are placed (I believe they do in QS1, but not sure how that is achieved. (Note: discussed at PR review on 6/2 and seemed like we may be ok with just going with set pixel sizes for now as long as responsive on small screens)
- Should the default be small? Should default view mode be removed as an option?
- Should card image be a selectable option? (It is not in QS1)
- Are all sizes correct?

## Related Issue
#743 

## How Has This Been Tested?
Locally and in Probo
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-817.probo.build/image-sizes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by smayden** [comment]
This css from QS1 might be relevant: https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.x/modules/custom/uaqs_fields/uaqs_fields_media/css/uaqs_fields_media.css

**Comment by smayden** [comment]
Looking into turning on alignment for images here as well. In Drupal 9 the default for image alignment is set to center (yuck). This Drupal.org issue has a patch that would change to 'none': https://www.drupal.org/project/drupal/issues/3099878

**Comment by smayden** [comment]
Updates needed:
- Remove card image from standard text formatter
- Update Square to reflect 220x220
- Investigate whether bootstrap utilities being added to stand text formatter are needed

**Review by mmunro-ltrr — APPROVED** [review]

**Comment by danahertzberg** [comment]
Just a nitpick. Since Default isn't really descriptive, should we also remove that option from the list? If we remove it, do you know what the new default would be? Large?

**Comment by smayden** [comment]
Made Dana's suggested change on removing default from the list of options. Embedding an image initially still sets it to display as default (which is sent in the image manage display to render as "small"). But when you edit media you should no longer see default as an option.

Ready for final review

**Review by danahertzberg — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Pull request merged**
