### PR TITLE
Closes #1322: Add core patch to fix issue with CKEditor fields not always saving.

### LINKED ISSUE #1322: Changes sometimes lost when editing html source in standard editor
## Problem/Motivation
In prepping content for the Arizona.edu launch we are noticing that content edits sometimes don't save when editing multiple paragraphs at the same time.

### Describe the bug
On pages with multiple paragraphs, some changes are lost when editing the html source in the ckeditor (when the standard editor is still selected). Only the last paragraph edited in this way seems to save.

### To Reproduce

1. Create a page
2. Add several text paragraphs with content in them
3. Save your page
4. Edit the page
5. Edit multiple paragraphs and make edits by clicking on "Source" in the ckeditor to edit the source code
6. Make changes to styles in the HTML code (e.g. classes on a paragraph, or heading styles) on multiple paragraphs
7. Save the page
8. Notice where changes actually occur.

## Proposed resolution
I don't know a resolution, but right now we are having to save the page after editing each paragraph as a workaround.

### Expected behavior

Ideally changes would not be lost...

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Adds Drupal core patch from existing d.o. issue: https://www.drupal.org/project/drupal/issues/3102249 that addresses issue with the `DrupalMedia` CKEditor plugin provided by the Drupal media module.

## Related issues
#1322 

## How to test

1. Create a page
2. Add several text paragraphs with content in them
3. Save your page
4. Edit the page
5. Edit multiple paragraphs and make edits by clicking on "Source" in the ckeditor to edit the source code
6. Make changes to styles in the HTML code (e.g. classes on a paragraph, or heading styles) on multiple paragraphs
7. Save the page
8. Edit the page
9. Add images to two or more of the paragraphs
10. Save the page
11. Edit the page
12. Make changes to the images using the "Edit media" button (change alignment or size or both)
13. Make a text change in source mode to one of the paragraphs
14. Save the page
15. See if all changes were saved.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [x] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by smayden** [comment]
I've done some testing in Probo and I can still recreate the issue with this patch... One interesting discovery is that the issue I'm having with editing things like classes via Source on multiple paragraphs only seems to happen when an image is embedded in those paragraphs (which also matches the use cases where I've seen this bug on Arizona.edu).

Steps I took to recreate the issue:

1. Created three paragraphs with text/headings on a page
2. Edited the source of multiple paragraphs adding classes for color/sizing.
3. Saved the page - all changes took.
4. Edited page again and added images to all three paragraphs.
5. Saved the page - all changes took.
6. Edited page again and edited image embeds on all three paragraphs to different sizes/alignment (done via "Edit Media" button not source code).
7. Saved the page - only the last paragraphs changes displayed.
8. Edited page again and edited source code to change classes on the text for multiple paragraphs.
9. Saved the page - only the text changes for the last paragraph displayed. 

Test page is here: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1461.probo.build/sho-page

**Comment by smayden** [comment]
Also once images are on the page this seems to happen with:
-simple text changes - for example losing edits to an image if a simple text (not in Source) edit happens on a different paragraph
-paragraphs without images (if an image exists elsewhere on the page)
-changes made via editor toolbar to formatting (not just in soure)

**Comment by joeparsons** [comment]
Thanks for testing @smayden

**Comment by joeparsons** [comment]
Updated PR to use alternate core patch from other d.o. issue that sounds related to @smayden's additional findings: https://www.drupal.org/project/drupal/issues/3102249

**Comment by joeparsons** [comment]
Since changing this PR to use the patch from https://drupal.org/project/drupal/issues/3102249 which addresses and issue with the CKEditor plugin provided by the Drupal media module, I have not been able to reproduce the problems @smayden described.  I think this may be the fix we were looking for 🤞🏻.

Definitely needs more testing.  @smayden @Carris-Toupin @natebyerley (or anyone else) if you have time to help test this, it would be most appreciated.

**Comment by joeparsons** [comment]
It's possible that there are actually 2 different issues in play - one affecting changes made in "source" mode and one affecting changes made to images added with the `DrupalMedia` CKEditor plugin/button but I'm only applying the patch for the `DrupalMedia` button issue for now.  If problems modifying fields in "source" mode still exist but the `DrupalMedia` button problems are gone, we may need to add both patches...

**Review by Carris-Toupin — APPROVED** [review]
I checked adding images, and changing images to both a text area and a text area on a card and all seems to work perfectly. I checked adding video too. All works well now.

**Comment by natebyerley** [comment]
I tried to reproduce the issue of media not being saved - I cannot reproduce it, despite opening numerous text blocks, adding media, changing media, adding more blocks, modifying media, then saving.  Approved!

**Review by smayden — APPROVED** [review]
tested this briefly and I can no longer recreate the issue. happy to test more next week too if needed

**Review by trackleft — APPROVED** [review]

**Pull request merged**
