### PR TITLE
Fixes #2805 Update Trellis API Endpoints.

### LINKED ISSUE #2805: Update Trellis Endpoints
## Conditions of satisfaction
The Trellis team has deployed the events functionality we have been testing with to their production environments. We should consider adding the new endpoints into Quickstart to replace usage of the development endpoints.

### PR DESCRIPTION
**Pull request by tadean**
This PR updates the Trellis API Endpoints to point to the versions that have recently been deployed to production by the Trellis team.

## Description
This PR contains updates to the configuration entities that contain the references to the Trellis API endpoints.

## Related issues
#2805 

## How to test

- enable `az_enterprise_attributes_import`
- enable `az_event_trellis`
- verify that enterprise attributes exist at `/admin/structure/taxonomy/manage/az_enterprise_attributes/overview`
- verify that the event import form can still be used, search, and import data successfully at `/admin/trellis-event-importer` 

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by bberndt-uaz — COMMENTED** [review]
I'm not sure if this is related to the endpoints, but on the Probo site the category filter doesn't seem to work when searching--no results are returned. For example:

**Events updated in last 7 days**
image

**Events updated in last 7 days, category Orientation & Onboarding**
image

**Events updated in last 7 days, audience Staff**
image

The other filters seemed to work as expected.

**Comment by tadean** [comment]
Thanks @bberndt-uaz ! I'm looking into this and passed it along to the Trellis team as well.

**Comment by tadean** [comment]
After some testing, the issue with the Category filter currently appears in both the qa endpoint (which was what was in use prior to this PR) and the production endpoint, and in hand-constructed calls to the event search API outside of the Quickstart view.

Kim on the Trellis team has created a ticket for this on the Trellis side. The issue doesn't seem related to this PR. Thanks @bberndt-uaz !

**Comment by danahertzberg** [comment]
Question to be answered with a follow up issue if even possible.
- Can the import button only appear if there are results to select?
- Does there need to be a "No results found" message when applicable?

**Review by danahertzberg — APPROVED** [review]

**Review by bberndt-uaz — APPROVED** [review]
Glad to hear that the Trellis team is working on the Category filter issue!

I agree that Dana's suggestions would be good follow-up issues:

- Hiding the Import button at least until a successful search has been performed makes sense to me. Instead, you could gray out and disable the button, but I'm not sure if there are other instances of that behavior in the admin UI.
- I think a "No results found" message after searching would be helpful.

**Pull request merged**
