### PR TITLE
Add admin user credentials to contributing doc

### LINKED ISSUE #199: Update admin Drupal user passwords to match usernames
## Motivation
Probo, Lando, and DDEV all create Drupal users with different passwords for no real reason, so updating them to match the user names will make development easier.

## Proposed Resolution
Update the passwords to be the same as the usernames. Also, put the credentials in the contributing documentation so it is easier to find than looking through the Lando/DDEVProbo config files.

### PR DESCRIPTION
**Pull request by jwmoore1**
Resolves #199

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart project in the right column.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joshuasosa** [comment]
Curious, is there a purpose why the pw is different across the different installs (lando, ddev, probo)? Any reason not to just make it admin / admin?

**Comment by trackleft** [comment]
> Curious, is there a purpose why the pw is different across the different installs (lando, ddev, probo)? Any reason not to just make it admin / admin?

Changing them to be uniform makes total sense to me

**Comment by jwmoore1** [comment]
@joshuasosa I'm assuming it's just because that was how it was setup. I agree, making them all the same would be great!

**Comment by tadean** [comment]
I believe it was patterned after the credentials used in D7 probo/localdev. I'd also be in favor of making them all identical.

**Comment by jwmoore1** [comment]
Do we want to keep azadmin, or just make it admin/admin? Also, do we care about the test user accounts created by Probo? Is it OK to make the password changes as part of this PR and just change the issue?

**Comment by joeparsons** [comment]
I'd also be OK with making the credentials the same across Probo/lando/ddev but using `azadmin` (and originally `uaqs_admin`) instead of a generic `admin` username was definitely an intentional choice after some discussion in a Friday meeting a long time ago.

**Comment by joeparsons** [comment]
I'd also be OK with using the username as the password for all of the ProboCI accounts (azadmin:azadmin, azcontentadmin:azcontentadmin, azcontenteditor:azcontenteditor) but would probably prefer to keep `azadmin` as the username over `admin`.

**Pull request merged**
