### PR TITLE
Closes #1309 Adding quick node clone

### LINKED ISSUE #1309: Add feature to duplicate content
## Motivation
I want to duplicate a node and its content into a new node.

## Proposed Resolution
Add contrib module

### Describe alternatives you've considered
- https://www.drupal.org/project/quick_node_clone
- https://www.drupal.org/project/node_clone
- https://www.drupal.org/project/entity_clone
- https://www.drupal.org/project/replicate

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Content editor
- Content administrator
- Administrator

## Additional context
https://www.intracto.com/nl-be/blog/modules-to-avoid-drupal-8

### PR DESCRIPTION
**Pull request by trackleft**
## Description
Adding https://www.drupal.org/project/quick_node_clone

## Related Issue
Closes #1309 

## How Has This Been Tested?
login to site as admin
https://80c62fc3-a6ad-4e08-aa2f-13eb8cfc37f1.probo.build/user

Enable the quick_node_clone module
Enable the az_demo module

go to https://80c62fc3-a6ad-4e08-aa2f-13eb8cfc37f1.probo.build/pages/text-media
click on clone
scroll to bottom of page and click save.

You are done .

Node clone config is here: https://80c62fc3-a6ad-4e08-aa2f-13eb8cfc37f1.probo.build/admin/config/quick-node-clone
The permissions included with the module are

image

I think this could be a powerful way to quickly create pages, one thought I had was that a team could create a template or starter node that they always clone when making new pages.  This could be useful with newsletters for example.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
Looks like this is working as an admin! I can't remember if we can package permissions with a module? 

Documentation notes: media items are not cloned (just referenced), and permissions would need to be updated.

**Comment by trackleft** [comment]
Additionally embedded content is not cloned.

**Comment by danahertzberg** [comment]
I'm thinking these should be enough permissions.
image

**Comment by trackleft** [comment]
I added the permissions via a hook_modules_installed() in az_core since we can't use our normal role config file for adding permissions for optional modules.

**Comment by tadean** [comment]
> > I added the permissions via a hook_modules_installed() in az_core since we can't use our normal role config file for adding permissions for optional modules.
> 
> Interesting idea. Did you see this @tadean? Might be an alternative we could consider for how to handle permissions for Drupal 9.3.0+ (?)

Sort of, that's what I had in mind but a manual version of what I think could eventually be an automated process. I was picturing code that stands between our bulk permission `.yml` files and the config provider, tests if the permission exists, and then filters them out if they don't exist. The same thing ends up happening essentially.

**Comment by trackleft** [comment]
Please remove permissions from this PR and addresss in #1339

**Review by joeparsons — APPROVED** [review]

**Review by bberndt-uaz — APPROVED** [review]
In the latest Probo build, I enabled Quick Node Clone and cloned the Text on Media page: everything looked the same to me on the cloned page. I added the cloned page to the menu for a 1:1 comparison (so the sidebar would appear on both). I also cloned an event, since that would be another use case: that seemed to work fine as well.

**Review by smayden — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Review by jwmoore1 — APPROVED** [review]

**Pull request merged**
