### PR TITLE
Add full html paragraph

### LINKED ISSUE #287: Create HTML paragraph
**Name:** HTML
**Description:** Add full HTML

**Requirements:** 
- Preview/view source code
- Use HTML text format

**Notes:**
Should this just be a plain field that allows for full HTML without any text editing buttons? Having all the same Text paragraph type buttons could be confusing

_**Approved by AZ Digital on 9/15/2020**_

### PR DESCRIPTION
**Pull request by trackleft**
Add initial PR for review with group that includes 
HTML paragraph type
Full HTML field

## Description
Copy text area settings and rename a bunch of strings

## Related Issue
Closes #287 

## How Has This Been Tested?
Not at all currently

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by danahertzberg** [comment]
- Add Ace Editor in core install profile instead of at the paragraph level (via @tadean )
- Reference ace editor in HTML paragraph
- Administrator permissions only by default
- Module not enabled by default

**Comment by trackleft** [comment]
In my latest push, I 
- Removed unecessary .module file
- Removed unecessary src folder and plugins
- Removed .libraries file
- Added full_html text format back 
- Moved az_markup filter settings to az_quickstart changed to full_html
- Changed field name from Markup to HTML and changed machine name from az_markup to az_full_html
- Moved ace_editor requirement to install profile level.

**Review by smayden — APPROVED** [review]
I tested this out and it worked well for me. Able to embed from instagram and youtube with the expected results after saving.

**Review by camikazegreen — APPROVED** [review]
I've opened a separate ticket to resolve the jQuery issues: Ensure HTML Paragraph supports jQuery#365

Other than that, this looks ready to go!

**Review by tadean — APPROVED** [review]

**Review by kevcooper — APPROVED** [review]

**Review by mmunro-ltrr — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]

**Review by danahertzberg — APPROVED** [review]

**Pull request merged**
