### PR TITLE
Fixes #3305 Provide Attribute Filtering for News Export

### LINKED ISSUE #3305: Provide Enterprise Attribute Filtering for News Export
## Motivation

1. News articles in CatCloud _must_ have Enterprise Attributes to display correctly in CatCloud.
2. Sometimes we want to create News articles on our website that don't get imported to CatCloud.

## Proposed Resolution
_**Due in July 2024**_

### Describe the solution you'd like
We could make it so that only articles that are tagged with Enterprise Attributes get included in the Export.

### Describe alternatives you've considered
We could add a "Do not broadcast" checkbox, that shares that information with Trellis.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Anonymous user
- Authenticated user
- Content editor
- Content administrator
- Administrator

### PR DESCRIPTION
**Pull request by tadean**
This PR adds a views filter to the News Export API that understands how to translate Enterprise-wide attribute keys to local taxonomy terms.

## Related issues
#3305 

## How to test

- enable `az_demo`, `az_enterprise_attributes_import`, `az_news_export`
- Clear the cache
- Tag `Black Holes Come to the Big Screen` as audience `External Media`
- **Visit the following URLs and verify the content appears:**
  - `/az_quickstart/export/az_news/v1/az_news.json?filter=not+empty`
  - `/az_quickstart/export/az_news/v1/az_news.json?filter=or&attribute[]=External+Media`
- **Verify the Black Holes content is absent:**
  - `/az_quickstart/export/az_news/v1/az_news.json?filter=empty`

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [x] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
**Topics for discussion/testing:**

- Currently, the JSON feed of news might be used for a variety of purposes that we aren't aware of on Quickstart sites
- Does this change merit an additional display to constitute a new version number of the API?
- Should we provide alternate displays that still show news without attributes?

The impact of the above may be affected by the fact that this API is relatively new and it is likely that CatCloud is likely the primary or only stakeholder at this time.

**Review by trackleft — DISMISSED** [review]

**Comment by trackleft** [comment]
Should we add a dependency here on `az_enterprise_attributes_import`? https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_news/az_news_export/az_news_export.info.yml

**Comment by tadean** [comment]
> Should we add a dependency here on `az_enterprise_attributes_import`? https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_news/az_news_export/az_news_export.info.yml

Attributes are provided by `az_core` - only the bulk creation of the individual terms comes from `az_enterprise_attributes_import`

**Review by trackleft — DISMISSED** [review]

**Comment by tadean** [comment]
Refactored to avoid usage of `hook_field_views_data_alter()` as this being a term reference field in conjunction with that hook invites the taxonomy module to replace our plugin.

This avoids needing to alter module weight.

**Review by bberndt-uaz — APPROVED** [review]
Tested in Probo using the "How to test" steps from the PR description.

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
We should update the documentation here:
https://quickstart.arizona.edu/site-admin/integrations/catcloud-news-export

**Pull request merged**
