### PR TITLE
Closes #556 Creating custom flexible block (new and improved: fixing branching problems)

### LINKED ISSUE #556: Create Flexible Block block type
Goal: Block type with all enabled paragraph types available. Match Quickstart 1.

### PR DESCRIPTION
**Pull request by smayden**
This PR creates a custom block type to match QS1 flexible block.

## Description
- This PR add a custom block type called Flexible Block that includes the same paragraphs as Page
- Also creates a new module az_flexible_block where the associated files are stored)
image

Further improvements needed (either on this PR or future tickets):
-Other fields to add? QS 1 has label, title, revision settings, view mode, and URL redirects, along with Bean stuff I don't totally understand)
-Make block viewable when you click on it from the list (currently goes to edit screen)

## Related Issue
#556

## How Has This Been Tested?
Tested locally and on Probo build

How to test: 

First create a flexible block:
1. Create a flexible block by going to Structure > Block Layout > Custom Block Library and then click the +Add Custom Block button
2. Choose Flexible Block
3. Enter a block description (should not display)
4. Add paragraphs with content
5. Save the block

Embed the block on a page:
1. Create a new page
2. Add a text area
3. Add a custom block using the E button on the editor toolbar
4. Choose the flexible you created
5. Save the page and make sure the block appears as expected

Or place the block:
1. Go to Structure > Block Layout
2. Choose a region and click the Place Block button
3. Select the flexible block you created
3. Specify the page/content type the block should/should not appear on (default would be all pages)
4. Make sure the block appears as expected

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
Question: Not sure where files should ideally be stored - particularly the block file.

**Comment by smayden** [comment]
This PR is still very much a work in progress (and the probo build still not working correctly). Some notes for me to pick up on post vacation of if anyone else wants to follow up):
- Created custom block type az_flexible_block and added paragraphs - appears to be working in my local build but not probo
- After conferring with Chris created a module az_flexible_block and put the associated files inside
- Module was not enabled in the Probo build
- After enabling the module, I can create a flexible block on the Probo build, but nothing displays when I added it to a page (either in the CK editor or by placing the block
- Still need to add other possible fields (title, etc.)

**Comment by smayden** [comment]
There are still some questions about improvements on this PR, but I think it is now working and ready for initial review.

**Comment by barrettbaffert** [comment]
This is looking great!

I think (assume?) the HTML paragraph type needs to be included as an option here /admin/structure/block/block-content/manage/az_flexible_block/fields/block_content.az_flexible_block.field_az_content

I enabled the HTML paragraph module (not available by default config) and it wasn't an option for flexible block. (It was available for flexible page paragraph options)

**Comment by smayden** [comment]
Updated the paragarphs field on the block to not select any paragraphs by default (which selects all).

I believe this is ready for final review!

**Comment by danahertzberg** [comment]
Looking good to me! I found a bug that needs to be addressed separately and I will create a ticket for it.

https://6ed4fc09-9ee4-4ab6-9a5e-26d354df918b.probo.build/dana

image

**Review by danahertzberg — APPROVED** [review]

**Comment by trackleft** [comment]
The only issue i can see going down the road is an issue with cloning a view.
Cloning this view will not result in the same view because this relies on a specifically named view template.
I can't see a way around this, just something to note.

The problem is with flexbox needing very specific markup in order to set columns on the grid.

**Review by danahertzberg — DISMISSED** [review]

**Comment by smayden** [comment]
Made update changing field name from az_content to az_main_content

image

Probo build: https://3f873c18-1229-4cde-a667-7468dac491ce.probo.build/test-page-flex-block-embedded

PR is ready for final review (and if no additional issues), merging

**Review by joeparsons — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
