### PR TITLE
#534 & #539: Add patch to resolve issue where user can't switch view modes on embedded media

### PR DESCRIPTION
**Pull request by barrettbaffert**
## Related Issue

https://github.com/az-digital/az_quickstart/issues/534
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by barrettbaffert** [comment]
With patch in place, viewmodes chosen in config, and allowed html, this seems to be working as expected

https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-608.probo.build/there-image-viewmode

**Comment by barrettbaffert** [comment]
Before the patch [screencast](https://arizona.box.com/s/4ofmgcrl479jk6svs6715dcwx6eipyel)

After the patch [screencast](https://arizona.box.com/s/go5r5o52mn8wu72y26olkxliana2py1l)

**Review by smayden — APPROVED** [review]
Tested and was able to select view modes for different image sizes: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-608.probo.build/shoshana-view-mode-fun-page

A few issues that are probably outside of the scope for this ticket:
- I notice that right now an editor has to embed the image, then select edit media again to choose the view mode. Would be great to select before you embed. Is there a ticket for that?
- Should this be working with video yet? I tried applying a view mode to an embedded video, but the sizing did not change.

**Review by danahertzberg — APPROVED** [review]

**Comment by barrettbaffert** [comment]
- [ ]  @joeparsons is investigating PHP warnings /admin/reports/dblog

**Review by trackleft — APPROVED** [review]

**Comment by joeparsons** [comment]
> * [ ]   @joeparsons is investigating PHP warnings /admin/reports/dblog

I was worried that the PHP errors and warnings might be caused by the core patch being used but from what I can tell, that doesn't seem to be be the case.  I wondering if the errors/warnings are due to a content problem (e.g. a media item that was removed after it was added to a page or something?)

**Review by tadean — APPROVED** [review]

**Comment by joeparsons** [comment]
Sample errors/warnings recorded in Probo dblogs:

```
Warning: array_filter() expects parameter 1 to be array, null given in Drupal\media_library\Plugin\views\field\MediaLibrarySelectForm->viewsFormValidate() (line 134 of /src/az-quickstart-scaffolding/web/core/modules/media_library/src/Plugin/views/field/MediaLibrarySelectForm.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(305): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /src/az-quickstart-scaffolding/web/core/modules/media_library/src/Plugin/views/field/MediaLibrarySelectForm.php(134): array_filter()
#3 /src/az-quickstart-scaffolding/web/core/modules/views/src/Form/ViewsFormMainForm.php(162): Drupal\media_library\Plugin\views\field\MediaLibrarySelectForm->viewsFormValidate()
#4 /src/az-quickstart-scaffolding/web/core/modules/views/src/Form/ViewsForm.php(179): Drupal\views\Form\ViewsFormMainForm->validateForm()
#5 [internal function]: Drupal\views\Form\ViewsForm->validateForm()
#6 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array()
#7 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormValidator.php(273): Drupal\Core\Form\FormValidator->executeValidateHandlers()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm()
#9 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(589): Drupal\Core\Form\FormValidator->validateForm()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm()
#11 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormBuilder.php(219): Drupal\Core\Form\FormBuilder->buildForm()
#12 /src/az-quickstart-scaffolding/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2265): Drupal\Core\Form\FormBuilder->getForm()
#13 [internal function]: Drupal\views\Plugin\views\display\DisplayPluginBase->elementPreRender()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(101): call_user_func_array()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\Core\Render\Renderer->doTrustedCallback()
#16 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\Core\Render\Renderer->doCallback()
#17 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender()
#18 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender()
#19 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(241): Drupal\Core\Render\Renderer->render()
#21 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#22 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(242): Drupal\Core\Render\Renderer->executeInRenderContext()
#23 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(132): Drupal\Core\Render\MainContent\HtmlRenderer->prepare()
#24 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse()
#25 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
#26 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#27 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(163): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#28 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#29 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#30 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#31 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#32 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#33 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle()
#34 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#35 /src/az-quickstart-scaffolding/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#36 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle()
#37 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#38 {main}
```
```
Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 261 of /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php)
#0 /src/az-quickstart-scaffolding/web/core/includes/bootstrap.inc(305): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(261): array_flip()
#3 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(245): Drupal\Core\Entity\EntityStorageBase->loadMultiple()
#4 /src/az-quickstart-scaffolding/web/core/modules/media_library/src/MediaLibraryEditorOpener.php(66): Drupal\Core\Entity\EntityStorageBase->load()
#5 /src/az-quickstart-scaffolding/web/core/modules/media_library/src/Plugin/views/field/MediaLibrarySelectForm.php(126): Drupal\media_library\MediaLibraryEditorOpener->getSelectionResponse()
#6 [internal function]: Drupal\media_library\Plugin\views\field\MediaLibrarySelectForm::updateWidget()
#7 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php(69): call_user_func_array()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/EventSubscriber/FormAjaxSubscriber.php(109): Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse()
#9 [internal function]: Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber->onException()
#10 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#11 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(219): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#12 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#14 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#15 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#16 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#17 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle()
#18 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#19 /src/az-quickstart-scaffolding/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#20 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle()
#21 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#22 {main}
```

```
Error: Call to a member function uuid() on null in Drupal\media_library\MediaLibraryEditorOpener->getSelectionResponse() (line 72 of /src/az-quickstart-scaffolding/web/core/modules/media_library/src/MediaLibraryEditorOpener.php)
#0 /src/az-quickstart-scaffolding/web/core/modules/media_library/src/Plugin/views/field/MediaLibrarySelectForm.php(126): Drupal\media_library\MediaLibraryEditorOpener->getSelectionResponse()
#1 [internal function]: Drupal\media_library\Plugin\views\field\MediaLibrarySelectForm::updateWidget()
#2 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php(69): call_user_func_array()
#3 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/Form/EventSubscriber/FormAjaxSubscriber.php(109): Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse()
#4 [internal function]: Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber->onException()
#5 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#6 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(219): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#7 /src/az-quickstart-scaffolding/vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
#8 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle()
#9 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle()
#10 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#11 /src/az-quickstart-scaffolding/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#12 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle()
#13 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#14 /src/az-quickstart-scaffolding/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#15 /src/az-quickstart-scaffolding/web/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle()
#16 /src/az-quickstart-scaffolding/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#17 {main}
```

**Pull request merged**
