### PR TITLE
Bug/471 field az addresses

### PR DESCRIPTION
**Pull request by trackleft**
I was having problems making the PR agains the bug/471 branch, hopefully it works now.

Change field type to "Text (formatted, long)" with Plain text only,
Change machine name to "field_az_address",

### CODE REVIEW

**Comment by camikazegreen** [comment]
This PR is also updating the Twig template for the Person content type to use:
- field_az_body instead of field_az_bio
- field_az_attachments instead of field_cv_documents

**Review by camikazegreen — APPROVED** [review]
Everything that this PR touches looks correct on Probo.

**Comment by smayden** [comment]
Two questions on this one:

- Is the address supposed to be plain text now? (I still see CKeditor)
- Is it just me or is there now slightly more spacing between address and phone number now?

image

**Comment by trackleft** [comment]
> * Is the address supposed to be plain text now? (I still see CKeditor)
Oops, I did the configuration, but forgot to export it lol
> * Is it just me or is there now slightly more spacing between address and phone number now?
Address elements add style to things, we could  keep the `<address>` element out for now.

**Review by smayden — APPROVED** [review]
Address field now set to plain text for person content type and everything displaying as expected.

**Pull request merged**
