### PR TITLE
Fixes #3074, Fixes #3568 Course Importer Missing Content, Course Instructor Person Links

### LINKED ISSUE #3074: AZ Course Importer Bugs
## Problem/Motivation
Issues discovered during 2.9 Alpha 1 testing.  Based on reviewing sites on 2.8.3, I don't believe this issue was introduced in 2.9

### Describe the bug
- Certain courses will not import
- When trying to import these unimportable courses, it seems that import 'log' message is inconsistent and inaccurate

### To Reproduce

[https://qs29alpha1-azs-quickstart.pantheonsite.io](https://qs29alpha1-azs-quickstart.pantheonsite.io)

- Attempt to import course: AED 195B
- Attempt to import course: AGTM 100

Screenshots below post-import shows that each course shows as 'updated,' but it is not importing/imported (i.e. courses not showing in site content.

Screenshot 2024-01-09 at 2 57 20 PM (1)

Screenshot 2024-01-09 at 3 41 58 PM (1)

In a different test, @bberndt-uaz tried this on his local machine:

"When I tested this locally, those two courses are not imported but my status message says “Processed 0 items”."

image (3)

### Are courses not being imported because they are not included in the Spring 2024 schedule of courses? 

@bberndt-uaz suggests:

"As far as I can tell, those courses are not included in the Spring 2024 schedule of classes, so I believe it is correct that they are not imported. AED 210 and AGTM 170A1 are available for Spring 2024, and I was able to import those courses successfully. I’m not sure why the status message is different on my local environment compared to the Quickstart multidev.

If you search Spring 2024 courses from [this UAccess link](https://studentcenter.arizona.edu/app/ui/academics/class-search) with “Show Open Courses Only” switched OFF, you can see which courses are available this semester. I’m not sure if there is a better link to use."

### Re: Which courses can be imported?

- If there are restrictions as to what courses people can import, let's document that here: [https://quickstart.arizona.edu/site-admin/integrations/uaccess-course-import](https://quickstart.arizona.edu/site-admin/integrations/uaccess-course-import)

- If there are restrictions as to what courses can be imported, let's update our testing requirements to fit - namely, where can one find a list of importable courses? 

### Re: Course import 'log' messages

- If a course can't be imported, log should indicate as a Fail, or Ignore.

### LINKED ISSUE #3568: Courses Instructor Person Links
## Motivation
With the addition of #3561 , it should be possible to automatically link the Course instructor field to the relevant Person if they exist on the site.

## Proposed Resolution
In course import, link the instructor field of a course to the relevant person, if one is found with a matching NetID.

### Describe the solution you'd like
When a course is imported, an entity query could be performed on the existing Person nodes on the site, to determine if a Person exists that has a matching netid of the netid of the instructor.

If so, the link field of the relevant delta could be set up to link automatically to the correct person.

### PR DESCRIPTION
**Pull request by tadean**
## Description
This PR adds functionality to the course module that links up instructors of courses to Person nodes on the site if they exist. It also makes the instructor field appear on the node display.

## Related issues
#3568 
#3074 

## How to test

- Enable `az_demo` `az_http` and `az_course`
- log in and visit `/admin/config/az-quickstart/courses`
- Enter a single course that exists to import, such as `MATH 100`
- Click `Save and import courses`
- Select one of the demo content Person nodes and edit them. Give them a netID matching one of the instructors of the course
- Save the person node.
- Visit `/admin/config/az-quickstart/courses` again
- Click `Save and import courses`
- Verify that the node is updated.
- Edit the node and check if the netid you selected is now linked to the person.
- **Note:** now that the display changes are in #3677 , the instructor links are not visible on the node view. You need to edit the course node to look at the hidden link field to see the links

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by tadean** [comment]
**Tasks/To be determined:**

- [ ] UX of how instructor field should be displayed

**Comment by joshuasosa** [comment]
I haven't tried this (Probo site wasn't loading for me), but it sounds like you enter a netid on the course and it'll link up if there's a matching netid in a person. Can it support course sections like 100-001, 100-002, etc with different instructors? Can it support multiple instructors per course/section?

Some ideas/examples:
In PTYS, we have it set up with content types for semester, course and section connected with entity relations. For sections, entity relation is used to select faculty based on person nodes, and multiple faculty can be selected. While there are hundreds of people nodes, not all of them should be selectable as an instructor (e.g., staff). An entity reference view display is used with person to select specific categories of people. In the course section, there's also an additional field to add non-PTYS instructors to append people outside the dept who don't have a PTYS person profile page.

**Comment by tadean** [comment]
> I haven't tried this (Probo site wasn't loading for me), but it sounds like you enter a netid on the course and it'll link up if there's a matching netid in a person. Can it support course sections like 100-001, 100-002, etc with different instructors? Can it support multiple instructors per course/section?
> 

This PR specifically affects the schedule of classes migration importer; when classes are imported from the schedule it now automatically links the instructor field up a person that has a NetID record as instructor of any session. It does not cover any functionality for hand editing the course node page (there, the instructor field could be linked to whatever the editor wants, it is a multivalue link field).

It is aware of the notion of courses having multiple instructors, but does not contain any section information. e.g., a course with 5 sections will be imported as a single course with five instructors (the instructors of the five sessions).

Back in the original courses PR, #1576 it was decided at the time that the Quickstart course module should not contain sections. This was because of concerns of essentially reimplementing the schedule of classes, and also performance concerns of the webservice we are drawing the class information from. So, currently, the course content type represents an aggregate of all sections of the course, and there is no corresponding entity for a specific section.

There are a few academic units on campus that are using a customized version of Courses for section-based information in Quickstart 2. I wouldn't object to revisiting that original decision about Courses/Sections to add a section context if that seems desirable.

**Comment by tadean** [comment]
Switched to full names for instructors.

**Comment by tadean** [comment]
With the switch to full names and the user of name/netid data, need to make some changes to make the list remove duplicates.

- [ ] Remove duplicates from instructor list

**Comment by tadean** [comment]
Refactored import approach to allow for every instructor from each section to be added, with pruning duplicate results.

**Review by joeparsons — APPROVED** [review]

**Comment by camikazegreen** [comment]
Trying to test this after the most recent changes. The netids of the instructors aren't displayed anywhere on the course node (it's now instructor full name). Is NetID still the connection, and if so do I need to look those up from an outside system or is there somewhere to see instructor netids inside the imported content?

Example page here: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3570.probo.build/course/gist/314

**Review by camikazegreen — APPROVED** [review]

**Comment by danahertzberg** [comment]
Would something like this make sense on the front-end?

image

```
<div class="mb-5 row">
  <div class="col-12 col-md-8">
    <div class="clearfix text-formatted field field--name-field-az-course-description field--type-text-long field--label-hidden field__item">
      <p>Cartography is a fundamental tool of geography; it is also a science and art in its own right. Cartography uses principles of design, perception, statistics, and communication. This course introduces students to the design, production and interpretation of maps, a fundamental skill in GIST. Laboratory exercises give students additional experience with GIS-based skills, through the use of ArcGIS software.</p>
    </div>
  </div>
  <div class="col-12 col-md-4">
    <div class="card card-body">
      <div class="field field--name-field-az-course-units field--type-integer field--label-inline">
        <div class="field__label font-weight-bolder trailing-colon">Course Units</div>
        <div class="field__item">3</div>
      </div>
      <h2 class="bold mb-0 text-body text-size-h6">Instructor(s)</h2>
      <ul class="field field--label-hidden field--name-field-az-course-instructor field--type-link field__items mb-0">
        <li class="field__item"><a href="/person/albertina-quack">Chris Lukinbeal</a></li>
        <li class="field__item"><span>Jennifer Mason</span></li>
      </ul>
    </div>
  </div>
</div>
```

**Comment by tadean** [comment]
Changes to course display to be moved to a separate issue in #3676

**Comment by tadean** [comment]
The remaining pending issue of some instructors being missing appears to be due to a namespace/xpath selector issue where the xpath query was seeming not to find some elements. Refactored to change the base selector of the migration which seems to potentially resolve the issue.

This refactored change may also resolve #3074

**Comment by tadean** [comment]
- [ ] Sort instructors by last name

**Comment by tadean** [comment]
Filtered out empty responses, and applied a patch for a `migrate_plus` issue that causes the Xml parser's predicate selectors to not work correctly.

**Review by joeparsons — APPROVED** [review]

**Review by bberndt-uaz — APPROVED** [review]

**Comment by bberndt-uaz** [comment]
I did some further testing in Probo and imported these courses: MATH 100, CHEM 241A, ISTA 116, and BNAN 599. The import successfully linked instructors to Person nodes both when creating and updating course nodes. When I removed a NetID from a Person or edited it to be incorrect, the next import removed the instructor link to that Person node.

**Pull request merged**
