### PR TITLE
Closes #1584: Fix sidebar nav top margin calculation

### LINKED ISSUE #1584: Sidebar nav top margin calculation issue
- White space/top margin calculation issue on campus rec test site
- https://2-3-0-sasg-rec.pantheonsite.io/ 
- Needs more testing – apply to site with full-width content and sidebar already existing
- Ashley looking into new query fix

### PR DESCRIPTION
**Pull request by bberndt-uaz**
## Description

Closes #1584 by ensuring that bottomMargin is a number and that sidebarTopMargin is a string ending in "px". Previously, when bottomMargin was a string like "48px", the sidebarTopMargin value would be incorrect. As part of this change, a default value of 0 was added for the CSS custom property --sidebar-top-margin.

## Related issues

#1584 

## How to test

Create a page with fullwidth paragraphs that also have a bottom margin set. Add the page to a menu so that a sidebar will be displayed. The sidebar should be pushed down just below the last fullwidth element.

### Arizona Quickstart (install profile, custom modules, custom theme)
- Patch release changes
   - [X] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- Minor release changes
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- [ ] Other or unknown

### Drupal core
- Patch release changes
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major or minor level update
- [ ] Other or unknown

### Drupal contrib projects
- Patch release changes
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- Minor release changes
   - [ ] Major level update
- [ ] Other or unknown

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by trackleft — DISMISSED** [review]

**Comment by trackleft** [comment]
Thanks @bberndt-uaz !!

**Comment by bberndt-uaz** [comment]
> Thanks @bberndt-uaz !!

Thank you @trackleft and @akslay for all your help!

**Review by trackleft — APPROVED** [review]
Looks like the default works.
image

**Review by akslay — APPROVED** [review]

**Review by joeparsons — APPROVED** [review]
Changes look good to me.

**Pull request merged**
