### PR TITLE
Fixes #411: Add cropping module to Install Profile

### LINKED ISSUE #411: Add cropping module to AZQS install profile
## Motivation
The current version of Quickstart offers cropping capabilities to editors; similar functionality should be available in Quickstart 2.0 as well. Current version also allows you to select a focal point so cropping centers on a person's face, for example.

## Proposed Resolution
Select a copping module that is compatible with D9 and add it to AZQS install profile. Cropping capabilities should be available on the Person content type (profile image) and on the Text on Media paragraph type.

### Roles and Permissions considerations
All site editors should have access to cropping functionality. 
- Content editor
- Content administrator
- Administrator

### PR DESCRIPTION
**Pull request by tadean**
Adds cropping functionality to Quickstart.

## Description
This PR adds the [Crop API](https://www.drupal.org/project/crop) and [Image Widget Crop](https://www.drupal.org/project/image_widget_crop) modules to the installation profile, which are the current most common cropping implementations in D9. A crop is added for card images, which are in use on the card paragraph type and the view at `/people`.

## Related Issue
#411 

## How Has This Been Tested?
To test, do the following:

- Go to `/admin/config/media/crop` and verify that the Card Image crop type exists.
- Go to `/admin/config/media/image-styles/manage/az_card_image` and verify that the card image style is using the Card Image crop.
- Add a Person, fill out required fields
- Click `Add media`
- Upload an image and fill out alt text
- Verify that the `Crop Image` dropdown exists on the media browser below the image
- Open the `Crop Image` dropdown.
- Drag the handles and crop window around to the desired cropping points for the image
- Save the image
- Fill out any other required Person fields
- Save content
- go to `/people` and verify your selected crop is in use.

**Note: the crop UI uses vertical tabs to show different available crops. Claro has some current quirks with vertical tabs, so the spacing on the crop messages is a little tight currently until contrib modules are updated. This can also be seen on the entity settings for media entities and other places. This is unrelated to this PR. See the issues [here](https://www.drupal.org/project/gin/issues/3192316) and [here](https://www.drupal.org/project/image_widget_crop/issues/3192318). We should apply a patch for this when available.**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart project in the right column.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tadean** [comment]
**Examples:
Crop UI:**
image

**Full content (not cropped)**
image

**Directory (cropped)**
image

**Review by smayden — APPROVED** [review]
I was able to successfully follow the testing instructions and crop an image that then appeared on the grid view. Looks good to me. 

A few thoughts for future improvements (after prerelease):
- We might want to add some help text so content editors know where to expect the crop to appear. I was initially surprised my crop didn't show on the node since that's where I went after saving.
- I didn't see anyway from the editing screen to get back and edit the image to change the crop. If that's not possible we'll need to make sure we have good documentation for content editors on how to find and edit images.

**Comment by tadean** [comment]
> I was able to successfully follow the testing instructions and crop an image that then appeared on the grid view. Looks good to me.
> 
> A few thoughts for future improvements (after prerelease):
> 
> * We might want to add some help text so content editors know where to expect the crop to appear. I was initially surprised my crop didn't show on the node since that's where I went after saving.
> * I didn't see anyway from the editing screen to get back and edit the image to change the crop. If that's not possible we'll need to make sure we have good documentation for content editors on how to find and edit images.

I agree with both of the above - I think it might be possible to figure out a way to force the media reference widgets to display specific versions of the image that has their crop in use on node edit pages in specific content type cases.

**Comment by joeparsons** [comment]
I had the same experience as @smayden.  The cropping UX was great but I was initially confused as to why the person node did not show the cropped image in either its default/full view mode (at node/<nid>) or in the main admin content listing.

**Comment by tadean** [comment]
> I had the same experience as @smayden. The cropping UX was great but I was initially confused as to why the person node did not show the cropped image in either its default/full view mode (at node/123) or in the main admin content listing.

In regard to the person default view mode, the content type is currently set to use the Media entity's default version in the default display (The card image version is only currently used on the `Card Image` person display). It'd be possible to change the default to the Card Image if desirable.

In regard to the main content listing, this is because D9 cropped media can contain multiple unrelated crops per media entity, one for each "Crop type," which are independent from each other. The actual entity is the full image, and each crop is a transformation on that image.

**Review by joeparsons — APPROVED** [review]

**Review by barrettbaffert — APPROVED** [review]
I see cumulative hours of my life being saved by this pull request

**Review by trackleft — APPROVED** [review]

**Pull request merged**
