### PR TITLE
#3737: Backport coding standards fixes from #3738 to 2.10.x.

### PR DESCRIPTION
**Pull request by joeparsons**
## Description
Backports #3738 to 10.2.x branch.

## Related issues

#3737

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [x] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by bberndt-uaz** [comment]
I believe the changes to AZFinderTaxonomyIndexTidWidget from #3662 will also be required for this PR.

**Comment by joeparsons** [comment]
> I believe the changes to AZFinderTaxonomyIndexTidWidget from #3662 will also be required for this PR.

I think the latest change I just made might be sufficient (?) (I restored the 10.2.x namespace of the AZFinderIcons class in the use statement in that AZFinderTaxonomyIndexTidWidget class).  🤞🏻

**Comment by bberndt-uaz** [comment]
> > I believe the changes to AZFinderTaxonomyIndexTidWidget from #3662 will also be required for this PR.
> 
> I think the latest change I just made might be sufficient (?) (I restored the 10.2.x namespace of the AZFinderIcons class in the use statement in that AZFinderTaxonomyIndexTidWidget class). 🤞🏻

Yep, I think you're right!

**Review by bberndt-uaz — APPROVED** [review]

**Comment by trackleft** [comment]
Did you see the PHPUnit error?
```
92
93
94Time: 05:09.477, Memory: 12.00 MB
95
96There was 1 failure:
97
981) Drupal\Tests\az_core\Functional\ConfigOverrideTest::testConfigOverrideAfterInstall
99Failed asserting that null matches expected 'php_mail'.
100
```

**Comment by joeparsons** [comment]
> Did you see the PHPUnit error?
> 
> ```
> 92
> 93
> 94Time: 05:09.477, Memory: 12.00 MB
> 95
> 96There was 1 failure:
> 97
> 981) Drupal\Tests\az_core\Functional\ConfigOverrideTest::testConfigOverrideAfterInstall
> 99Failed asserting that null matches expected 'php_mail'.
> 100
> ```

Yes.  This is affecting all new PRs against 2.10.x.  See #3780.

**Review by trackleft — APPROVED** [review]

**Review by tadean — APPROVED** [review]

**Pull request merged**
