### PR TITLE
Closes #2139 Update logger_channel object type

### LINKED ISSUE #2139: Type checking LoggerChannel creates errors when trying to install Monolog
## Problem/Motivation
In [AZConfigOverride.php](https://github.com/az-digital/az_quickstart/blob/5f52816a69abb8cc3e304bcea30ea5f16231a6c8/modules/custom/az_core/src/AZConfigOverride.php#L82) the logger is being type checked for `Drupal\Core\Logger\LoggerChannel`. This is pretty high up in the Class hierarchy and from what I can tell from the code could be replaced with `Psr\Log\LoggerInterface`. This causes an error when trying to install the Monolog Drupal module (cli output shown below).  

### Describe the bug
When I try and install the Drupal Monolog module I get a TypeError error.

### To Reproduce

1. Install Drupal contrib module [Monolog](https://www.drupal.org/project/monolog)
2. Enable the module

## Proposed resolution
Change the LoggerChannel type check in [AZConfigOverride.php](https://github.com/az-digital/az_quickstart/blob/5f52816a69abb8cc3e304bcea30ea5f16231a6c8/modules/custom/az_core/src/AZConfigOverride.php#L82) to a type check for `Psr\Log\LoggerInterface`.

### Expected behavior

I wouldn't expect Type errors when enabling the Monolog module.

### Cli output

Drupal 9.5, using lando (truncating the stack trace):

```
✗ lando drush pm:enable monolog   
[2023-01-17T22:39:17.955596+00:00] php.ERROR: TypeError: Drupal\az_core\AZConfigOverride::__construct(): Argument #7 ($logger_channel) must be of type Drupal\Core\Logger\LoggerChannel, Drupal\monolog\Logger\Logger given, called in /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 262 in Drupal\az_core\AZConfigOverride->__construct() (line 82 of /app/web/profiles/custom/az_quickstart/modules/custom/az_core/src/AZConfigOverride.php)
```

### PR DESCRIPTION
**Pull request by caosborne89**
Closes #2139 by changing the type for the logger_channel object to Psr\Log\LoggerInterface.

## Description
Closes #2139 by changing the type check for the logger_channel object to `Psr\Log\LoggerInterface`. This allows additional types of loggers (like Monolog) to be used.

## Related issues
- #2139

## How to test

This shouldn't have any user-facing changes. It should allow users to utilize different loggers in code. The most visual change I could see is a Type error when trying to enable the Monolog Drupal contrib module. That error seems to be gone now. The error didn't actually stop me from using the module, but just a pesky error when enabling the module.

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [x] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by trackleft** [comment]
FYI in the docs for https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Logger%21LoggerChannelInterface.php/interface/LoggerChannelInterface/10

"This interface defines the full behavior of the central Drupal logger facility. However, when writing code that does logging, use the generic \Psr\Log\LoggerInterface for typehinting instead (you shouldn't need the methods here)."

**Comment by caosborne89** [comment]
I need to look at those errors in ProboCI-dev but I can't get the page to load (gets stuck on a loading page). Also trying to run the phpunit tests locally, but it's taking a while. I assumed az_core.services.yml didn't need to change, since it's just a type checking update, but maybe I'm wrong about that...

**Comment by caosborne89** [comment]
All the phpunit tests I ran locally passed.

**Comment by trackleft** [comment]
@caosborne89 This looks good, we've reviewed it an found that it is a change we would like to merge, would you please  put this PR on the az-digital/az_quickstart repo instead of your fork?  Our CI doesn't work with forks at the moment unfortunately.

In the future you should be able to use branches on the az-digital/az_quickstart repo for Merge Requests.

Thanks for this.

**Pull request closed without merging**
