### PR TITLE
Closes #3576 Add new demo AZ News node with embedded media and extra paragraphs

### LINKED ISSUE #3576: Add demo content to test media embed displays
## Motivation
We need more comprehensive demo content with embedded media so we can test the displays of in-line media.

### Is your feature request related to a problem? Please describe.
Yes, this issue is foundational work for #3439 

### Describe the solution you'd like
Add or adjust existing demo content to include more in-line media items (i.e. images, remote video).

## Additional context
I used ChatGPT to generate a press release using the prompt: “generate a fake press release about some medical breakthough at the University of Arizona" The following is the fake press release it generated:

**FOR IMMEDIATE RELEASE**

**University of Arizona Unveils Pioneering Treatment for Type 1 Diabetes: A Game-Changer for Patients**

*Tucson, AZ – July 31, 2024* – The University of Arizona has announced a groundbreaking medical breakthrough in the treatment of Type 1 diabetes, unveiling a revolutionary new therapy that holds the potential to dramatically alter the management of this chronic condition. The innovative treatment, known as Insulix-21, has demonstrated remarkable success in early clinical trials, offering new hope to millions of individuals living with Type 1 diabetes.

Developed by the University of Arizona's Center for Endocrine Research, Insulix-21 is a novel therapy that combines cutting-edge stem cell technology with advanced immunomodulation techniques. This dual-action approach not only aims to restore the body's ability to produce insulin but also prevents the autoimmune response that attacks insulin-producing cells in the pancreas.

Dr. Maria Alvarez, the principal investigator and Professor of Endocrinology at the University of Arizona, elaborated on the breakthrough: "Insulix-21 represents a significant advancement in Type 1 diabetes treatment. By leveraging stem cells to regenerate pancreatic beta cells and incorporating immunomodulatory agents to protect these cells from immune system attacks, we are addressing the root causes of the disease."

In a recent clinical trial involving 120 participants, Insulix-21 demonstrated a 65% reduction in insulin dependence and a 50% improvement in glycemic control over a 12-month period. Patients also reported enhanced quality of life and reduced incidence of diabetes-related complications.

Dr. Alvarez expressed her excitement about the potential impact of Insulix-21: "This breakthrough has the potential to not only manage Type 1 diabetes more effectively but also offer a path towards long-term remission for many patients. The early results are incredibly promising, and we are eager to continue our research and bring this transformative therapy to the wider community."

The University of Arizona is now preparing for larger-scale trials and is in discussions with leading pharmaceutical companies to accelerate the development and availability of Insulix-21. Additionally, the university has established a comprehensive support program to assist patients and families in accessing this cutting-edge therapy and managing their diabetes effectively.

This achievement highlights the University of Arizona's dedication to advancing medical research and improving patient outcomes. The Insulix-21 team is optimistic about the potential of this new treatment to make a significant difference in the lives of individuals affected by Type 1 diabetes.

For further information about Insulix-21 and ongoing research at the University of Arizona, please contact:

**Press Contact:**

Rachel Thompson  
Director of Communications  
University of Arizona  
Phone: (520) 621-1986  
Email: rachel.thompson@arizona.edu  
Website: [www.arizona.edu/insulix21](http://www.arizona.edu/insulix21)

---

**About the University of Arizona:**

The University of Arizona is a leading institution in research, education, and community service. Committed to addressing global challenges through innovation and discovery, the university strives to enhance the well-being of individuals and communities worldwide.

**###**

### PR DESCRIPTION
**Pull request by djcelaya**
## Description

Introduces a new AZ News demo node that contains an embedded media (image) item and two "Extra Page Elements" paragraphs. This press release is modeled after one of the news release we've produced in UAHS Communications, but I've replaced all references to UAHS with fake data that ChatGPT produced.

## Related issues

#3576 

## How to test

1. Create a new AZ Quickstart site
2. Run `drush pm:install az_demo`. This will install demo content, including the new AZ News node with embedded images and additional paragraphs.
3. Navigate to `/news/university-arizona-unveils-pioneering-treatment-type-1-diabetes-game-changer-patients`. The new AZ News item should look like:
Screenshot 2024-08-12 at 3 33 45 PM
Screenshot 2024-08-12 at 3 34 07 PM

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [X] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

### CODE REVIEW

**Comment by djcelaya** [comment]
I've noticed the exceedingly large vertical space under the embedded image's caption and credit area. I was not expecting that spacing problem to be this extreme but if I add another embedded image (that was not introduced with this PR) and adjust it to have a credit field, the same spacing behavior appears. I will explore correcting that problem in a follow up issue unless we feel that something I've done here has introduced this undesirable behavior.

**Comment by joeparsons** [comment]
Direct link to page with updated demo content on ProboCI build for PR:
https://a6f91014-dbd8-4f1e-96cb-ca20299cb2f2.probo.build/news/university-arizona-unveils-pioneering-treatment-type-1-diabetes-game-changer-patients

**Review by danahertzberg — DISMISSED** [review]

**Review by trackleft — DISMISSED** [review]

**Comment by djcelaya** [comment]
Per our discussion today, I will replace rachel.thompson@arizona.edu with wilmawildcat@arizona.edu in case there's ever a legit Rachel Thompson here. I will also find better placeholder images on Adobe Stock or the DAM to be more consistent with our other demo content that has "real" images.

**Comment by djcelaya** [comment]
FYI, press release initially generated by ChatGPT and modeled after: https://healthsciences.arizona.edu/news/releases/bhattacharya-named-inaugural-executive-director-cami

**Comment by djcelaya** [comment]
List view of news stories: https://a827580c-a656-4fb5-823e-4b29a520b5cb.probo.build/news
Detail view of new News story: https://a827580c-a656-4fb5-823e-4b29a520b5cb.probo.build/news/university-arizona-unveils-pioneering-treatment-type-1-diabetes-game-changer-patients

**Comment by trackleft** [comment]
Image source https://assets.arizona.edu/resource/folder/index/48d1b6b0883303883433965db09d7c3d
Image source https://assets.arizona.edu/resource/folder/index/48d1b6b0883303883433965db09d7c3d

**Review by trackleft — APPROVED** [review]

**Review by camikazegreen — DISMISSED** [review]
This demo content looks great

**Review by joeparsons — APPROVED** [review]

**Comment by djcelaya** [comment]
Featured Image: https://assets.arizona.edu/resource/folder/index/48d1b6b0883303883433965db09d7c3d?browseID=3d5fc9afb804ea1da60b1a76c88e3377
In-line Image: https://assets.arizona.edu/resource/folder/index/48d1b6b0883303883433965db09d7c3d?browseID=dabb876eac6914fb3c57245ed229f475

**Comment by djcelaya** [comment]
With updated photo credit: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3631.probo.build/news/university-arizona-unveils-pioneering-treatment-type-1-diabetes-game-changer-patients

**Review by danahertzberg — APPROVED** [review]
I think definitely a separate ticket. But the caption/credit on the image in the body field has 2 extra blank paragraphs adding extra space to it.

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
